- scalyr_agent/builtin_monitors/windows_process_metrics.py
- scalyr_agent/builtin_monitors/windows_system_metrics.py
based on what is needed in dashboards.
> Added a few new metrics to windows process and system monitors

- scalyr_agent/config_main.py
- scalyr_agent/scalyr_client.py
> Fleshed out Windows upgrade command and hooked up to real

- build_package.py
- win32/scalyr_agent.wxs
> Really fix the bugs with the third party license distribution

- setup.py
win32 FileVersion information was not being set correctly for pre release versions due to using a non-supported version format.
This meant py2exe was leaving off version information for exe files, which was then causing versioning conflicts when upgrading an official release (which had correction FileVersion strings) to a pre release (which had no version information).
> making sure exe files have version information set for pre releases

- scalyr_agent/builtin_monitors/docker_monitor.py
- scalyr_agent/builtin_monitors/windows_event_log_monitor.py
this prevents problems when seeking directly to records in large log files
> now reading from end of event logs 

- scalyr_agent/log_processing.py
- scalyr_agent/tests/log_processing_test.py
Fix that allows utf8 log content to work correctly with redaction rules
> Utf8 fixes for redaction rules

- Dockerfile
- Dockerfile.build_from_source
> Upgrade docker base image to xenial

- scalyr_agent/tests/scalyr_logging_test.py
The test case was ignoring the fact that log_write_rate had been set to 0 so all log records would be dropped thereafter the limit is reached. Added one more test
> fix unit test case

- docker/README.md
> Update README.md for Docker Integration

- scalyr_agent/builtin_monitors/docker_monitor.py
- scalyr_agent/builtin_monitors/kubernetes_monitor.py
Added extra debugging information to help diagnose problems with missing containerIDs
> K8s preview

- scalyr_agent/builtin_monitors/docker_monitor.py
Adding back support for the metrics_only config item
> metrics only support

- scalyr_agent/builtin_monitors/linux_process_metrics.py
Fixed up a couple of other places that might raise exceptions when a process exits.
> fixed ioerror when process not found

- scalyr_agent/builtin_monitors/mysql_monitor.py
Fixed a problem mentioned by @johnpadilla, where the agent exits if it is configured to use the mysql_monitor but mysqld hasn't started yet.
If connecting to the database fails, the agent prints a warning and then continues to try and connect to the db every gather_sample.
> mysql monitor no longer aborts agent if mysqld is not running

- scalyr_agent/agent_main.py
- scalyr_agent/builtin_monitors/garbage_monitor.py
- scalyr_agent/configuration.py
Initial version of the garbage monitor.
See class documentation for details on how to run.
> garbage monitor

- scalyr_agent/builtin_monitors/kubernetes_monitor.py
Fix some of the attribute names used to send information to Scalyr
to conform to what's being used server side.
Add feature to exclude logs and metrics from kube-system pods
by default.
Fixes to ensure that we only collect pod metrics for those pods
we are collecting logs.
> Some k8s integration fixes

- scalyr_agent/builtin_monitors/kubernetes_monitor.py
- scalyr_agent/monitor_utils/k8s.py
This commit detects when a pod is owned by a DaemonSet and (optionally) includes the daemonset name and labels with each log line uploaded.
Note the name and labels are currently uploaded as 'deployment' information.
If users wish to include daemonset information, they need to set the kubernetes_monitor config option `include_daemonsets_with_deployments` to `true`  (note: `include_deployment_info` must also be `true` for this option to have effect).
> handling daemonsets

- scalyr_agent/builtin_monitors/kubernetes_monitor.py
- scalyr_agent/copying_manager.py
- scalyr_agent/monitor_utils/k8s.py
- scalyr_agent/scalyr_logging.py
Also fixed a few issues with creating objects in the monitors
initialize method.
> Added more debug tracing

- scalyr_agent/builtin_monitors/docker_monitor.py
- scalyr_agent/builtin_monitors/syslog_monitor.py
- scalyr_agent/builtin_monitors/windows_event_log_monitor.py
- scalyr_agent/line_matcher.py
- scalyr_agent/log_watcher.py
- scalyr_agent/tests/empty_monitor.py
- scalyr_agent/tests/line_matcher_test.py
- scalyr_agent/tests/run_monitor_test.py
- scalyr_agent/tests/syslog_monitor_test.py
While looking in to the docker stuff, I noticed a bunch of files still listed my non-scalyr email in the authorship field, so I just whipped up a quick PR to change them all to my scalyr email.
> updated authorship

- scalyr_agent/builtin_monitors/kubernetes_events_monitor.py
- scalyr_agent/monitor_utils/k8s.py
This is a middle group solution that will only have the
leader create the extra cache.
> Only create K8sCache for event leader

- scalyr_agent/builtin_monitors/windows_event_log_monitor.py
Added EventID to log messages.
Also fixed duplicate logs if config changes
> Ticket #AGENT-52

- scalyr_agent/builtin_monitors/windows_event_log_monitor.py
Please make sure to use the updated win32evtlog.pyd binary on the build machine (sent via email), otherwise the agent will crash when an attempt is made to read events from a remote machine.
> allow event collection from remote machines

- scalyr_agent/builtin_monitors/kubernetes_events_monitor.py
- scalyr_agent/builtin_monitors/kubernetes_monitor.py
- scalyr_agent/configuration.py
- scalyr_agent/monitor_utils/k8s.py
> k8s global cache

- scalyr_agent/builtin_monitors/kubernetes_events_monitor.py
Added documentation about node leaders for the kubernetes events monitor
> k8s events documentation

- scalyr_agent/builtin_monitors/docker_monitor.py
- scalyr_agent/builtin_monitors/syslog_monitor.py
This fixes a problem when the parser is not set/overwritten when the parser is
not set at the top level of the log_config
> Ticket: #AGENT-62

- scalyr_agent/agent_status.py
- scalyr_agent/tests/agent_status_test.py
With the expansion of environment variable support ([AGENT-38)](https://scalyr.myjetbrains.com/youtrack/issue/AGENT-38), we should list environment vars to facilitate debugging and customer support.
- Important variables should be listed up front
- Missing important variables should be listed as missing
- SCALYR_API_KEY and other sensitive values should be redacted
- The rest should be displayed in sorted order (ignoring case)
- When displayed, do not alter case (to reflect actual environment)
As long as there is a formula for all scalyr-related env variables, there is no need to programmatically derive a comprehensive list of keys.   Except for `K8S_EVENT_DISABLE`,  as of now,  all env variables start with `SCALYR_`.    **We must preserve this invariant** as we define new custom …
> AGENT-84: Display environment variables in agent status-v

- scalyr_agent/builtin_monitors/docker_monitor.py
- scalyr_agent/builtin_monitors/kubernetes_monitor.py
- scalyr_agent/config_util.py
- scalyr_agent/json_lib/__init__.py
- scalyr_agent/tests/configuration_test.py
Follow on fixes to AGENT-38:
1. container_globs needs to become an ArrayOfStrings + unit tests
2. Add limit_key to the 2 log lines that use limit_once_per_second but fail to add the limit_key
> AGENT-85: Follow-on minor fixes to AGENT-38.

- scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py
https://github.com/scalyr/scalyr-agent-2/pull/168 introduced a regression in `test_user_agent_fragment` (see https://circleci.com/gh/scalyr/scalyr-agent-2/714?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
This PR fixes it by simply adding the k8s-runtime sub-fragment to the unit test.
> AGENT-116: Fix regression in test_user_agent_fragment

- docker/Dockerfile
- docker/Dockerfile.build_from_source
- docker/Dockerfile.k8s
- docker/README.md
Switched to a Docker image which doesn't require a Python install (because it's already installed :-)).
Updated instructions how to build the image.
> Small improvements

- scalyr_agent/builtin_monitors/kubernetes_monitor.py
Add option to allow docker to be used for listing containers even when use of api master is disabled.
> Force use of docker

- scalyr_agent/test_base.py
- scalyr_agent/tests/util_test.py
- scalyr_agent/util.py
Implements a rate limiter that blocks caller threads.
> AGENT-154: Rate Limiter

- scalyr_agent/connection.py
Fixed it.  I figure it'd take me less time because I've already got everything set up.
> no body for gets

- scalyr_agent/builtin_monitors/kubernetes_monitor.py
- scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py
Two commits.
The first one contains just the test that reproduces the problem (which will fail - or rather hang).
The second one contains the code that fixes the problem.
> Option b/already warm

- scalyr_agent/builtin_monitors/kubernetes_events_monitor.py
While validating the option-b/master branch, I noticed a lot of pod-not-found exceptions. However, the exception is caught outside the for line in lines loop. This means any lines that come after the offending line will be skipped.
- Move K8sApiException and general exception inside the `for line in lines` loop
- Keep `ConnectionError` outside the main loop because it is very often triggered by `for line in lines` iterator.
- Add another catch-all exception outside the loop to handle generic exceptions (e.g. those triggered at the `for line in lines` iterator itself.
> AGENT-242: Move exception into k8s_events_monitor main loop

- scalyr_agent/tests/scalyr_client_test.py
> Add unit test to catch missing log id issue

- scalyr_agent/builtin_monitors/journald_monitor.py
A leftover from using JsonObject.
> Change bad `get` call

- build_package.py
related ticket- AGENT-326 Combing coverage reports is not working
> Fix coverage version in docker builds.

- scalyr_agent/builtin_monitors/journald_monitor.py
- scalyr_agent/scalyr_logging.py
- scalyr_agent/tests/scalyr_logging_test.py
Private methods was trying to be used by another class, obviously that does not work.
> CT-18 Can't start agent with `journal_fields` configured

- benchmarks/README.md
This PR fixes two typos from review in #419.
> Fix typos in benchmarks/README.md

- scalyr_agent/scalyr_logging.py
I believe this PR should fix the issue @czerwingithub observed on staging server.
This pull request makes str (aka six.binary_type) also a valid type for metric names and values.
An alternative would be to enforce that those values are always of a text type (unicode) in place where ``emit_value()`` method is called, but that is harder to enforce, especially if there are any third party monitors which are written by the end users (they would all need to be updated).
> Fix type checks in the emit_value() method

- .github/ISSUE_TEMPLATE/pull_request_template.md
This proposed change adds a GitHub issue template to provide some reminders of what info is useful when creating a new PR.
Thoughts and proposed changes are welcome!
Fixes # N/A
N/A
> GitHub PR Template

- .circleci/config.yml
- scripts/circleci_usage_data.py
This pull request includes some formatting improvements to the Circle CI usage data script which makes it a bit easier to read.
In addition to that, I limited number of most recent branches we report usage data for (3) so the email doesn't get too long.
> Formatting improvements in the Circle CI usage data script

- .circleci/config.yml
Missed yet another thing in #505 which has regressed in #497.
> Fix incorrect Circle CI job requires dependencies

- .pre-commit-config.yaml
- README.md
This pull request includes the following changes:
* Adds the new ``bandi`` lint check to pre-commit file
* Add information on how to run a subset of tests to the README
* Add information on CI and how to trigger a whole build before merging a PR to the readme.
> README and tox improvements

- setup.py
Fix issue caused by passing in a `set` instead of a `list`.
> Fix issue with dynamic module includes

- scalyr_agent/util.py
- tests/unit/util/util_test.py
I'm conflicted on if we should check for bytes vs bits here, as someone might get tripped up on that without realizing.
> Method to parse strings representing data rates

- scalyr_agent/builtin_monitors/kubernetes_monitor.py
- tests/unit/builtin_monitors/kubernetes_monitor_test.py
When the k8s monitor is using the docker socket for querying containers, it misses out on short-lived pods.
The reason this happens is that when we query the docker socket, we query all containers (running and stopped), but filter them by containers started after the previous time we queried the containers.
This allows us to pick up short-lived containers that started and stopped since our previous query.
However, since the k8s ratelimiter changes were added, if no matching pod is found in the k8s cache then the container is also skipped. This will always happen the first time a pod is queried on the cache, and so it means that short-lived pods are now ignored, because they won't show up when we next query the list of running containers, because it will only show containers created after …
> AGENT-373 K8 agent doesn't collect logs from a CronJob 

- scalyr_agent/agent_main.py
I believe this should fix the issue we are seeing on Windows.
> Don't fail if extra_config_dir is not defined

- .sonarcloud.properties
- scalyr_agent/agent_main.py
- scalyr_agent/builtin_monitors/docker_monitor.py
- scalyr_agent/builtin_monitors/graphite_monitor.py
- scalyr_agent/builtin_monitors/journald_monitor.py
- scalyr_agent/builtin_monitors/kubernetes_monitor.py
- scalyr_agent/builtin_monitors/mysql_monitor.py
- scalyr_agent/builtin_monitors/postgres_monitor.py
- scalyr_agent/builtin_monitors/windows_event_log_monitor.py
- scalyr_agent/builtin_monitors/windows_system_metrics.py
- scalyr_agent/configuration.py
- scalyr_agent/monitors_manager.py
- scalyr_agent/platform_posix.py
- scalyr_agent/scalyr_logging.py
- scalyr_agent/util.py
- tests/distribution/python_version_change_tests/common.py
- tests/smoke_tests/verifier.py
- tests/unit/syslog_monitor_test.py
This pull request includes various code styling changes for issues reported by sonar cloud.
In addition to styling / code organization issues, it also caught an actual issue with Python 3 incompatible in one code path of postgresql monitor.
---
If we feel safer that way, we can merge this after the release (even though it should have no negative impact, but just in case).
> Fix small style related issues detected by Sonar Cloud

- scalyr_agent/agent_main.py
- scalyr_agent/agent_status.py
- scalyr_agent/configuration.py
- scalyr_agent/copying_manager.py
- scalyr_agent/log_processing.py
- scalyr_agent/scalyr_client.py
- scalyr_agent/util.py
- tests/unit/agent_main_test.py
- tests/unit/agent_status_test.py
Still needs tests, and there is some more manual testing I need to do.
> AGENT-397: Improved logging for investigating skipped bytes

- CHANGELOG.md
- RELEASE_NOTES.md
AGENT-396 related changes should be noted here.
> AGENT-406: Add rate limiting related changes to CHANGELOG and RELEASE_NOTES

- RELEASE_NOTES.md
Provide some specific examples.
> Tweaking maximum send rate release notes

- docker/Dockerfile.k8s
- scalyr_agent/agent_main.py
- scalyr_agent/configuration.py
- scalyr_agent/copying_manager.py
- tests/unit/configuration_test.py
- tests/unit/copying_manager_test.py
Discussion about this here: https://github.com/scalyr/scalyr-agent-2/pull/596#discussion_r454222334
> Remove `enable_health_check` option and have it always be on.

- .circleci/config.yml
- benchmarks/micro/conftest.py
- benchmarks/micro/test_compression_algorithms.py
This pull request includes a couple of small fixes and improvements to our custom py.test hooks.
I noticed those issues while working on a different repo.
> pytests hooks clean up

- .circleci/config.yml
- .circleci/docker_unified_smoke_unit/smoketest/smoketest.py
- .circleci/modernize/modernize.py
- .circleci/smoketest_docker.sh
- .circleci/smoketest_standalone.sh
- CHANGELOG.md
- README.md
- lint-configs/python/mypy.ini
- scalyr_agent/agent_main.py
- scalyr_agent/copying_manager.py
- tests/smoke_tests/standalone_test.py
- tests/smoke_tests/verifier.py
- tests/unit/copying_manager_test.py
- tests/unit/test_smoke_test_verifier.py
This pull request builds on top of #638 and adds mock based unit tests.
> Fix merging of active checkpoint data into full checkpoint data on full checkpoint write

- CHANGELOG.md
Asking Yan to review since it is late for Tomaz and Arthur.
@Kami @ArthurKamalov Please take a look at these changes since you are most familiar with them.  Tomaz - I hope you don't mind - I did some minor word smithing on your change log.
> Update CHANGELOG.md for Celaeno October 15, 2020 agent release

- .circleci/config.yml
- scalyr_agent/agent_status.py
- scalyr_agent/configuration.py
- scalyr_agent/copying_manager/copying_manager.py
- scalyr_agent/copying_manager/worker.py
- scalyr_agent/scalyr_client.py
- scalyr_agent/util.py
- tests/ami/scripts/partial/ssl_checks.sh.j2
- tests/ami/scripts/test_windows.ps1.j2
- tests/smoke_tests/standalone_test_rate_limited.py
- tests/smoke_tests/verifier.py
- tests/unit/agent_status_test.py
- tests/unit/configuration_test.py
- tests/unit/copying_manager_tests/common.py
- tests/unit/copying_manager_tests/copying_manager_new_test.py
- tests/unit/copying_manager_tests/copying_manager_test.py
- tests/unit/copying_manager_tests/copying_manager_worker_test.py
- tests/unit/copying_manager_tests/test_environment.py
- tests/utils/agent_runner.py
- tests/utils/log_reader.py
- tests/utils/tests/test_log_reader.py
* Fix stale checkpoint spam issue
* rename consolidated checkpoint file back to `chqekpoints.txt`.
> Fix stale checkpoint spam issue

- .circleci/config.yml
- .sonarcloud.properties
Working on getting sonar code coverage numbers in sync with codecov.io.
> Code coverage sonarcloud testing, update sonar scanner version

- scalyr_agent/agent_main.py
- scalyr_agent/configuration.py
- tests/ami/scripts/partial/restart_agent_and_remove_logs.ps1.j2
- tests/ami/scripts/test_windows.ps1.j2
- tests/unit/agent_main_test.py
- tests/unit/configuration_test.py
Add a missing negation for the tty check.
> Fix stdout isatty check, update win32_max_open_fds logic to be more robust

- CHANGELOG.md
- RELEASE_NOTES.md
- tests/smoke_tests/monitors_test/mysql_test.py
Add k8s container name change to release notes
> Release naming and notes for 2.1.19

- CHANGELOG.md
CHANGLOG updates for 2.1.22 release
> Update CHANGELOG for 2.1.22 release

- docker/scripts/container_builder_base.sh
This adds back in the code to build the container images using
normal `docker build` instead of the `docker buildx` approach
that was recently added.  To support both modes, we check to see
if `docker buildx` is supported.  If not, then we use the legacy,
otherwise buildx.
This is necessary to address issues with Jenkins in the Scalyr
build pipeline.
> Do not require buildx to build container images

- .github/workflows/agent-build.yml
- .github/workflows/docker-and-k8s.yml
This pull request enables workflow which publishes new Docker images to a testing Docker Hub account.
> Publish Docker images to testing Docker Hub account

- lint-requirements.txt
- scalyr_agent/builtin_monitors/docker_monitor.py
- scalyr_agent/builtin_monitors/openmetrics_monitor.py
- scalyr_agent/configuration.py
- scalyr_agent/copying_manager/copying_manager.py
- scalyr_agent/copying_manager/worker.py
- scalyr_agent/date_parsing_utils.py
- scalyr_agent/monitor_utils/k8s.py
- scalyr_agent/pytest_util.py
- scalyr_agent/scalyr_logging.py
- scalyr_agent/test_base.py
- scalyr_agent/util.py
- scripts/circleci_usage_data.py
- tests/unit/configuration_test.py
Stable version of black has been released (https://twitter.com/llanga/status/1487530230512295940.).
This pr upgrades to this latest stable version and re-formats code with it.
> Upgrade black to the latest stable version

- .github/workflows/agent-build.yml
- .github/workflows/publish-docker-images.yml
Small change to notify us on GHA job failures on Slack.
> Update GHA jobs to notify us on build failures on slack

- tests/ami/packages_sanity_tests.py
- tests/ami/scripts/test_rpm.sh.j2
Switch centos8 ami to the vault repo source, due the distro's EOL
> Fix centos 8 ami

- build_package.py
- scalyr_agent/build_info.py
More fixes to trying to get Jenkins pipeline and upgrade tests to pass.
> Jenkins CI build fixes

- scalyr_agent/monitor_utils/k8s.py
- tests/unit/builtin_monitors/kubernetes_monitor_test.py
This pull request fixes small debug log message formatting issue from #857.
> Fix small debug log message issue in the k8s utils

- CHANGELOG.md
- installer/scripts/postinstall.sh
- installer/scripts/preinstall.sh
This PR includes changes from #867.
I opened a new PR so we can make sure all the tests run and pass.
> Fix handling of Python >= 3.10 in rpm/deb package post install script

- scripts/circleci/run-ami-tests-in-bg.sh
- tests/ami/packages_sanity_tests.py
This PR cherry picks some AMI test changes and improvements from #875.
> AMI tests changes and improvements

- CHANGELOG.md
- scalyr_agent/builtin_monitors/kubernetes_events_monitor.py
- tests/ami/scripts/test_rpm.sh.j2
This pull request fixes a small user reported bug in the Kubernetes Events monitor.
I'm working on a release right now so sadly I don't have time for more detailed testing and automated tests, but I think this change should be fairly safe and I plan to do a deeper dive in the future when I have more time.
For now, I just wanted to include a small and safe bug fix which can make it into the upcoming release.
> Bug fix for Kubernetes Events Monitor

- CHANGELOG.md
- scalyr_agent/agent_main.py
- tests/unit/agent_main_test.py
This PR fixes bug with empty command for the agent_main.py script.
> Fix empty command parsing in agent_main.py

- CHANGELOG.md
Update the release timestamp to today, when we start the release process.
> Update release timestamp in changelog

- .github/workflows/lint.yml
This is a direct port of the circleci lint job. I'm going to restrain myself from adding fancy frills like reports. There are too many other things that need to be ported for me to go nuts with polish on each one. I can iterate on these later. 
CT-575
> CT-575 Create lint GHA workflow

- k8s/default-namespace/scalyr-agent-2.yaml
- k8s/no-kustomize/scalyr-agent-2.yaml
- k8s/scalyr-agent-2-envfrom.yaml
- k8s/scalyr-agent-2.yaml
This PR is just to merge the release branch back into master (ref: https://www.notion.so/sentinelone/Release-management-6c14b353ea08417fab69c58cba4c2790)
> Agent release 2.1.34

- CHANGELOG.md
- agent_build/docker/Dockerfile
- agent_build/docker/Dockerfile.base
- agent_build/tools/environment_deployments/deployments.py
- agent_build/tools/environment_deployments/steps/build_base_docker_image/slim-bullseye.sh
This PR updates base image version for agent docker images.
> [DSET-1476] update python image for docker images

- config/agent.json
Hi There, not much to say, just making it valid JSON as my editor didn't like the malformed version.
> Fix of malformed JSON

- .github/workflows/agent-build-windows.yml
> First pass at building agent windows installer on GHA

- .github/workflows/secrets-scanner.yaml
This pull request adds a workflow which uses trufflehog to automatically scan files and commits for secrets on push, PR and as part of a daily cron trigger.
>  Add secrets scanning workflow #96 

- .github/workflows/reusable-agent-build-container-images.yml
This is an attempt to fix the Docker Image tag publish to make sure docker image tags don't include ``v`` prefix.
Not tested, may not work.
> Try to fix Docker image tag publishing to make sure "v" prefix is not present

- .github/actions/install-k8s-agent/action.yml
- .github/workflows/reusable-agent-build-container-images.yml
- tests/e2e/k8s_events_monitor/cronjob_v1.yaml
- tests/e2e/k8s_om_monitor/scalyr-agent-2-daemonset.yaml
- tests/e2e/scalyr-agent-2-daemonset.yaml
* Making the K8s related GHAs a bit faster and more stable
* Adding CRI-O to the Kubernetes Monitor and OpenMetrics Monitor tests
> Optimizing and stabilization of K8s related GHAs

- agent_build_refactored/utils/docker/buildx/remote_builder/__init__.py
https://sentinelone.atlassian.net/browse/DTIN-3952
> GHA workflows failing on deleting a docker builder

- scalyr_agent/copying_manager/worker.py
> DTIN-4182: Added safety check when handling pending addEvents task
