scalyr_agent/run_monitor.py, scalyr_agent/tests/empty_monitor.py, scalyr_agent/tests/run_monitor_test.py
The MonitorsManager.build_monitor function changed its interface (3 parameters instead of 2), but run_standalone_monitor was not updated to reflect this, and this was preventing monitors from being run in a standalone fashion using
```
python -m scalyr_agent.run_monitor scalyr_agent.builtin_monitors.<my_monitor>
```
This PR calls ```build_monitor``` correctly, and adds a unit test calling run_standalone_monitor, which fails using the previous code, and passes with this fix.
=> run_standalone_monitor not working

docs/docker.md, scalyr_agent/builtin_monitors/docker_monitor.py
Setting the serverHost for each docker container to the serverHost in the config file.
=> Using serverHost from global config

scalyr_agent/log_processing.py, scalyr_agent/tests/log_processing_test.py, scalyr_agent/util.py
=> [Ready For Review] Add Hashing option for the redacted data

scalyr_agent/platform_tests/README.md, scalyr_agent/platform_tests/alpine/Dockerfile, scalyr_agent/platform_tests/jessie/Dockerfile, scalyr_agent/platform_tests/run_platform_test.py, scalyr_agent/platform_tests/wheezy/Dockerfile
Running the Scalyr Agent tests on different platforms. This structure can be expanded to cover all major Python/OS distributions. 
The base Docker images for Python are listed at https://store.docker.com/images/python
This should cover a lot of ground.
TODO:
=> Run platform tests on differnt Python/Linux distributions

scalyr_agent/agent_main.py, scalyr_agent/configuration.py, scalyr_agent/run_monitor.py, scalyr_agent/tests/configuration_test.py
This is especially useful for automated server spinups using a base template like cloudformation, ECS template etc. where the API Key can be baked in those templates as AWS templates have an easy interface to set up environment variables using JSON. The agent.json file doesn't need to be custom built
=> allow users to easily configure `scalyr_api_key` via env variables

scalyr_agent/builtin_monitors/docker_monitor.py
adding the duplkicate logger cause multiple file descriptors to be added that exhausted the  number of file descriptors the system can allot.
=> do not add duplicate docker logger

.circleci/config.yml, dev-requirements.txt, scalyr_agent/builtin_monitors/linux_process_metrics.py, scalyr_agent/tests/linux_process_metrics_test.py, scalyr_agent/tests/scalyr_client_test.py, scalyr_agent/tests/util_test.py
This PR attempts to add a functionality for allowing:
1) optionally allow multiple processes to be aggregated (with or without) inclusion of child processes
2) optionally allow a single process to include child processes.
There are 2 new configuration options that are added for the [Linux Process Metrics](https://www.scalyr.com/help/monitors/linux-process-metrics):
1) `aggregate_multiple_processes` (optional/default False) that allows multiple processes (if they match) to be aggregated.
2) `include_child_processes` (optional/default False) that includes the child processes for both single/multi process situations.
=> Process metrics

scalyr_agent/agent_main.py
This way the agent won't claim to have verified the connection when in fact it was started with `--no-check-remote-server`.
(When I run the tests using the command in `.circleci/config.yml`, 20 errors and 47 failures are reported, both before and after this change. If you'd like me to do any of this differently, don't hesitate to ask!)
=> Split status update message into three parts

scalyr_agent/builtin_monitors/linux_process_metrics.py
When the Linux process metrics monitor is turned on, the agent process is also monitored for process metrics. If this process forks, the current process dies and starts a child process. 
We were eagerly resolving the current process before the process actually forked, so the agent process being monitored was the parent process that died. The solution is to keep the magic value `$$` till we need the metrics so the child process can resolve to its PID. 
The errors were:
```
15:16:26.925 prodeu-log-6a /var/log/scalyr-agent-2/agent.log 2017-12-04 23:16:26.925Z ERROR [monitor:linux_process_metrics(agent)] [scalyr_logging.py:440] Exception while collecting metrics for PID: 11966 of type: <type 'instance'>. Details: TypeError("'NoneType' object is not iterable",) :stack_trace:
Traceback (most …
```
=> do not resolve $$ to current PID eagerly

scalyr_agent/builtin_monitors/linux_process_metrics.py
We were not parsing the right lines of the /proc/pid/status output. Tested agent release `2.0.33.pre34.1` with this change and the logs look better with around 20MB of resident memory usage. Thanks for catching the bug.
https://www.scalyr.com/events?filter=%22app.mem.bytes%22%20agent%20resident%20!peak_resident&teamToken=Sibg6CTKzry90OELNQjD3Q--&logSource=*ip-10-0-13-78*&originalStartTime=4%20hours&startTime=Dec%2011%2C%202017%207%3A19%3A18%20AM&source=autoRefresh&liveTail=true&endTime=Dec%2011%2C%202017%2011%3A19%3A18%20AM
=> parsing right lines of /proc/pid/status

docker/Dockerfile.custom_k8s_config, docker/k8s-config/agent.d/docker.json, scalyr_agent/builtin_monitors/docker_monitor.py, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/copying_manager.py, scalyr_agent/log_processing.py, scalyr_agent/monitor_utils/__init__.py, scalyr_agent/monitor_utils/k8s.py
The kubernetes monitor is currently based entirely off the
docker monitor, with support added for querying the k8s API
to retrieve information about the pods currently running.
Eventually common functionality between the docker and k8s
monitors needs to be factored out.
=> k8s monitor

docker/Dockerfile.k8s_config, docker/k8s-config/agent.d/api-key.json, docker/k8s-config/agent.d/docker.json, k8s/scalyr-agent-2.yaml, scalyr_agent/builtin_monitors/docker_monitor.py
This pull request updates the docker_monitor to log the raw docker logs of all containers from the files on disk rather than through the docker API.  The 'logfile' field will be reset to /docker/<container name>.log
It also includes a new Dockerfile to create a Docker image that is suited for running under Kubernetes.  When building this Docker image, the image name should be scalyr/scalyr-k8s-agent.  It differs from the main scalyr-docker-agent in that it uses the docker_monitor instead of the syslog_monitor to log container output, and it also uses the above raw logging features.
Finally, this request includes a k8s .yaml file that can be used to create and schedule the scalyr-agent to run as a Daemonset on a Kubernetes cluster.
=> k8s config file and updates to docker monitor

scalyr_agent/builtin_monitors/kubernetes_monitor.py
Provide the option to disable ssl certificate verification when performing queries on the internal k8s api.
This is added because some older versions of k8s appear to fail verification, so this gives people using legacy versions of k8s a workaround for that.
@czerwingithub, @johnpadilla can provide more details.
=> added option to disable ssl verification for internal k8s api queries

scalyr_agent/log_processing.py, scalyr_agent/scalyr_client.py, scalyr_agent/tests/copying_manager_test.py, scalyr_agent/tests/log_processing_test.py, scalyr_agent/tests/scalyr_client_test.py, scalyr_agent/tests/util_test.py, scalyr_agent/util.py
This commit fixes up most of the failing unit tests.
There are still a couple of tests that hang in the end-to-end tests of the copy_manager as a result of the pipelining changes.  Currently these are skipped.
=> fixed unit tests

scalyr_agent/builtin_monitors/journald_monitor.py
When initialising the `journald` monitor with a missing `journal_path`, the exception initialisation is erroneous, thus leading to an unreadable error message.
Given an erroneous configuration, such as:
{
"module": "scalyr_agent.builtin_monitors.journald_monitor",
"id":     "journald",
"journal_path": "/this_file_does_not_exist"
}
The follow error will appear:
Error reading configuration file: __init__() takes exactly 3 arguments (2 given)
Terminating agent, please fix the configuration file and restart agent.
This is due to a missing argument in `journald_monitor.py` where I suspect `journal_path` argument is missing. With it, you finally get the proper error which is:
journal_path '/var/log/journal' does not exist or is not a directory
Error reading configuration file: journal_path …
=> Fixed an issue encountered when initializing the journald monitor

scalyr_agent/agent_main.py, scalyr_agent/configuration.py
If this config option is False, and stdout is not a tty, then the agent will not ping the remote scalyr servers when it starts
=> added config item check_remote_if_no_tty

scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/monitor_utils/k8s.py
Here is the option for disable annotation configs.
I've also updated the inline documentation for the kubernetes monitor.
It's rebased of the current master (but not with the network stats).
Let me know if you'd like me do rebase it off the k8s network metrics changes instead.
=> annotation config can be disabled, plus documentation

scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/configuration.py, scalyr_agent/copying_manager.py, scalyr_agent/log_processing.py
Contains several fixes related to performance issues.  This is meant to reduce CPU usage for customers, especially those with a large number of files being monitored by the agent.
The fixes include:
* Remove unnecessary debug lines that were sucking up CPU
* Reduce redundant calls to get current time.
* Do not write entire checkpoint file on every iteration.  Instead, write a smaller "active" checkpoint file and merge them only one in a while
* Provide an option to not parse the json logs for k8s client side.  This is meant to just investigate related performance issues.
=> Fix several performance issues

docs/monitors/journald_monitor.md, scalyr_agent/builtin_monitors/journald_monitor.py
According to the documentation for the journal.Reader class
https://www.freedesktop.org/software/systemd/python-systemd/journal.html#systemd.journal.Reader
the path flag is optional. If the path is set to `None` it defaults to the system journal.
=> Allow unspecified Journal Paths

k8s/scalyr-agent-2.yaml
Allows easier configuration if your Scalyr account is in the EU.
Also added option for the include_daemonsets_as_deployments fix
though should only be needed if customers wish to disable
this behavior.
=> Allow configuration scalyr_server via k8s configmap

scalyr_agent/agent_main.py, scalyr_agent/configuration.py, scalyr_agent/tests/configuration_test.py
Forces https for the scalyr server, unless the `--force-http option` is
passed on the command line.
The code for this has been placed in the Configuration object, to ensure
that anywhere that queries the scalyr_server from the config will be
given the https version of the url.
=> Ticket #AGENT-32

scalyr_agent/copying_manager.py
Don't add logs dynamically if a log path or glob already exist that match the
path.
The purpose of this is so that log entries specified in `agent.json` or
`agent.d/*.json` can override the parser and other attributes of dynamically
added logs.
This is a temporary solution.  The real solution is to allow people to override
log config options in docker labels, similar to how it works with k8s
annotations.
=> Ticket: AGENT-44

scalyr_agent/log_processing.py
Fixed the redaction formatter to use explicit parameter values for the hash
because python 2.6 doesn't support implicit parameter values.
=> Ticket #AGENT-20

scalyr_agent/builtin_monitors/postgres_monitor.py
The postgres monitor was keeping a connection and cursor open per instance of
the monitor.  By default statements executed by a connection are executed
inside of a transaction.
To ensure consistency, all database statistics remain constant inside a single
transaction and so when we were querying the statistics because it was still
in the same transaction, the same values were being returned.
I've fixed this by opening and closing the db connection each gather_sample.
=> Ticket #AGENT-14

scalyr_agent/builtin_monitors/docker_monitor.py
This updates the docs regarding setting the parser via docker labels.
This only changes the class documentation in the DockerMonitor.  I'm not sure if there are references in any other documentation we have.
=> updated docs for parser

scalyr_agent/configuration.py, scalyr_agent/scalyr_client.py
The ability to disable send requests already exists in the agent, but under an
obscure flag `disable_leak_send_requests`.
Rather than have users specify an option with `disable_leak...` I've changed the
name of this option to `disable_send_requests`.
=> Ticket: #AGENT-54

dev-requirements.txt, scalyr_agent/util.py
IIUC the json lib includes have to account for various situations where json lib may or may not exist. If Json lib doesn't exist, use the fallback `json_lib`.
`scalyr_client_test.py` are currently breaking because of extra space. I think this occurs in the following scenario in development/CI:
- `ujson` library is missing
- `json` lib version adds spaces by default when encoding (to eliminate spaces, you need to add 
```
json.dumps(separators=(',', ':'))
```
The solution, I _think_, is to include ujson in `dev-requirements.txt`. Doing so now results in all tests passing.
Question: if a customer setup mimics the current breaking tests (i.e. customer has `json` installed, there will be extra spaces in the JSON. Does this break anything when it's sent over? (I would not think so?)
=> Fix unit tests by including ujson in development

docker/README.md, scalyr_agent/agent_main.py, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/configuration.py, scalyr_agent/copying_manager.py, scalyr_agent/monitor_utils/k8s.py, scalyr_agent/monitors_manager.py, scalyr_agent/scalyr_client.py, scalyr_agent/scalyr_logging.py, scalyr_agent/scalyr_monitor.py, scalyr_agent/tests/monitors_manager_test.py, scalyr_agent/tests/scalyr_client_test.py
Fixes k8s aspect of AGENT-40, wherein additional `user-agent` fragments are periodically polled from monitors and added to global connection settings.
Marketing team wants additional insight as to whether events are coming from k8s, docker. Currently, the `user-agent` only contains local host platform info. This PR seeks to refactor the code to enable extraction of said info from monitors. Additionally, a fix is implemented for k8s.
1. Refactor the monitor manager/monitors such that `MonitorsManager` periodically polls all agents for additional user-agent "fragments". Fragments are immediately applied to global connection settings. Thereafter, all events from this agent will reflect those fragments.
2. Unless I'm missing something, `MonitorsManager` was not a thread (it merely started up …
=> AGENT-40 k8s user-agent info

scalyr_agent/builtin_monitors/url_monitor.py, scalyr_agent/log_processing.py, scalyr_agent/tests/log_processing_test.py, scalyr_agent/tests/syslog_monitor_test.py, scalyr_agent/util.py
Removes python 2.7 specific formatting code from the log processor and related
tests.
Also updates the `md5_digest` utility function to return a hex string by default
rather than returning the raw md5 bytes, which could contain null-bytes and
other invalid ASCII.
=> Ticket: #AGENT-20

scalyr_agent/monitors_manager.py
AGENT-74 documents the initiative to eliminate unnecessary pauses in unit test.
I tracked one cause to when the `MonitorManager` waits for each monitor to shutdown, even if `wait_on_join` is False.
`MonitorsManager.stop_manager` currently accepts a wait_on_join parameter. This parameter defaults to True.  Some unit tests set this to False (I don't think we need to wait for all threads to shutdown in orderly fashion since `stop_manager` is typically called at the end of a unit test).
I don't fully understand why there are 2 loops here that call `monitor.stop()`.  I assume there is a reason for this.  Even so, I don't see the need to call `monitor.stop()` a second time when `wait_on_join` is False.
https://github.com/scalyr/scalyr-agent-2/pull/163/files#diff-9aba7b5c6dac7e1f8002bc4dd5fbe524R …
=> AGENT-74: Eliminate unnecessary pause in MonitorsManager.stop_manager 

dev-requirements.txt, scalyr_agent/json_lib/objects.py, scalyr_agent/json_lib/parser.py, scalyr_agent/json_lib/tests/encode_decode_test.py, scalyr_agent/json_lib/tests/serializer_test.py, scalyr_agent/log_processing.py, scalyr_agent/tests/log_processing_test.py, scalyr_agent/util.py
1. Json encoder/decoder issue breaking `TestLogFileProcessor.test_log_attributes`
2. _fallback_json_encode missing `sort_keys` 
Error for (1) is 
```
======================================================================
ERROR: test_log_attributes (scalyr_agent.tests.log_processing_test.TestLogFileProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/echee/Documents/code/scalyr/scalyr-agent-2/scalyr_agent/tests/log_processing_test.py", line 1448, in test_log_attributes
log_attributes=vals['attributes'])
File "/Users/echee/Documents/code/scalyr/scalyr-agent-2/scalyr_agent/log_processing.py", line 1330, in __init__
self.__base_event = Event(thread_id=self.__thread_id, attrs=log_attributes)
File …
```
=> AGENT-65 and AGENT-66 - Broken unit test (json encoding)

scalyr_agent/builtin_monitors/docker_monitor.py, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/builtin_monitors/tests/__init__.py, scalyr_agent/builtin_monitors/tests/docker_monitor_test.py, scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py, scalyr_agent/test_base.py, scalyr_agent/test_util.py, scalyr_agent/tests/copying_manager_test.py, scalyr_agent/tests/monitors_manager_test.py, scalyr_agent/util.py
This is a follow up to recently merged PR https://github.com/scalyr/scalyr-agent-2/pull/150.
In this PR, I add the following:
1. user-agent support for docker
-  returns fragment as `docker=true` if docker_monitor is running but version cannot be determined.
- no specific support for ECS yet
2. modify user-agent support for k8s by returning `k8s=true` if k8s_monitor is running but version cannot be determined.
3. Unit tests to lock-down expected behavior for what k8s & docker monitors are expected to return.
In this PR, I add user-agent fragment support for Docker.  As discussed with @imron, there is potential for race condition between manager and monitor.  To handle this as well as potential failure during version API call, I follow a lazy-instantiation "self-healing" approach that's …
=> AGENT-40: Docker user-agent fragment

scalyr_agent/builtin_monitors/kubernetes_events_monitor.py, scalyr_agent/builtin_monitors/kubernetes_monitor.py
Fixes a problem where we were checking the existence of a key in a dict, but the
variable could sometimes be None.
I'm still not sure of the root cause of this, but I suspect it could be caused
if there is a container that uses a non-json logging driver, meaning it won't
have a log path, and the lack of the log path was causing the monitor not to
create the abovementioned dict.
I've fixed the stack trace and also added extra debug information to help
identify the root cause of the issue.
=> Ticket #AGENT-88

scalyr_agent/log_processing.py, scalyr_agent/tests/log_processing_test.py
Fixed problem with hashed redaction rules, where lines that didn't match any
rule were discarded, and also problems where lines were truncated after the
final matched group of a line.
I'm not sure how many customers use this feature, but from what I can tell, it's
been broken like this since the very beginning.
=> Ticket: #AGENT-83

scalyr_agent/tests/log_processing_test.py
Fixes unit tests by making sure to do a 'scan' of the test file before
attempting to read from it.  This makes sure that processing of the file isn't
"shortcircuited" because it (incorrectly) assumes there are no bytes available.
This does not affect the main agent which does period scans of the files being
monitored.
=> Ticket: #AGENT-71

.circleci/config.yml, dev-requirements.txt, scalyr_agent/all_tests.py, scalyr_agent/builtin_monitors/redis_monitor.py, scalyr_agent/json_lib/tests/encode_decode_test.py, scalyr_agent/json_lib/tests/objects_test.py, scalyr_agent/json_lib/tests/parser_test.py, scalyr_agent/json_lib/tests/serializer_test.py, scalyr_agent/platform_tests/run_platform_test.py, scalyr_agent/scalyr_logging.py, scalyr_agent/test_base.py, scalyr_agent/test_util.py, scalyr_agent/tests/auto_flushing_rotating_file_test.py, scalyr_agent/tests/configuration_test.py, scalyr_agent/tests/copying_manager_test.py, scalyr_agent/tests/line_matcher_test.py, scalyr_agent/tests/log_processing_test.py, scalyr_agent/tests/monitors_manager_test.py, scalyr_agent/tests/redis_monitor_test.py, scalyr_agent/tests/scalyr_client_test.py, scalyr_agent/tests/syslog_monitor_test.py, scalyr_agent/tests/syslog_request_parser_test.py, scalyr_agent/tests/url_monitor_test.py, scalyr_agent/tests/util_test.py
This PR establishes the framework for multi-python-version unit tests.
It's not meant to fix all tests to be python 24,25,26 compatible. But I do fix one problem (using unittest2 instead of unittest) as an example.  One outstanding incompatibility for python26 has been noted with a comment (pertains to `str.decode`) and I've requested input from @imron 
We need testing across versions.  After attempting various permutations including statically vs dynamically compiled versions of older python, I believe this is best tradeoff that I can get working that will move us forward:
1. create a custom docker image with pre-compiled python 2.x  (for now stored in edwardchee public docker repo but easily moved to scalyr repo later)
2. parallelize CircleCI to run different version tests
3. Include …
=> AGENT-93: circle python versions

scalyr_agent/tests/configuration_test.py, scalyr_agent/tests/linux_process_metrics_test.py
Low hanging fruit fixes for 26 test code compatibility.
1. Sets should be initialized as set([])
2. Dict comprehensions should not be used.
=> AGENT-94: Fix set init and dict comprehension in unit tests

scalyr_agent/builtin_monitors/tests/docker_monitor_test.py, scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py, scalyr_agent/tests/configuration_test.py
Remove Counter and context manager usage from unit tests
for 2.4, 2.5 compatibility.
=> AGENT-95: Backport mock/patch syntax & remove Counter

scalyr_agent/builtin_monitors/redis_monitor.py
Python 2.6 unittests are failing because of 2 issues.
This addresses one of them, namely `str.decode` errors="replace" should be passed as an arg, not a kwarg (only 2.7 onwards supports kwargs)
=> AGENT-101: Pass errors='replace' as an arg for pre-2.7 compatibility.

scalyr_agent/copying_manager.py, scalyr_agent/tests/copying_manager_test.py
Changed monitor.module_name to monitor_name - this was a side effect of some
refactoring (we used to pass in the monitor) that didn't get picked up.
=> Ticket: #AGENT-100

scalyr_agent/tests/configuration_test.py
Follow up to this discussion: https://github.com/scalyr/scalyr-agent-2/pull/173#discussion_r278401848
Consolidating some test classes that were duplicated because of prior divergence between code branches (sitting in review)
=> AGENT-96: Deduplicate some test classes

docker/README.md
A community-posted PR alerted us to the fact that our docker README.md is outdated. 
This PR explains in detail how to run both json/syslog versions.
I have tested the instructions locally and verified end-to-end logging.
=> AGENT-105: Fix docker readme

.circleci/config.yml, .circleci/smoketest_docker.sh
This PR adds smoketests for docker json & docker syslog.
CircleCi launches 3 images -- agent, uploader, verifier.  All processes synchronize on scalyr backend state in qatesting.
Note: The python3 `smoketest.py` code is not included in this PR, pending further stabilization and inclusion of k8s testing capability.  In the near future, we will move `smoketest.py` into this repo.  (This PR is really about getting CircleCI to launch the currently self-contained docker image that in turn contains `smoketest.py`.)
=> AGENT-99: docker syslog/json smoketests

scalyr_agent/builtin_monitors/kubernetes_monitor.py
This will show more detailed information about the reason container inspection is failing.
This should be the minimum item we need in the preview build for the customer to check why it is failing.
=> Showing more detailed error message

k8s/scalyr-agent-2.yaml, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/configuration.py, scalyr_agent/log_processing.py, scalyr_agent/monitor_utils/k8s.py, scalyr_agent/monitor_utils/tests/k8s_test.py, scalyr_agent/tests/configuration_test.py, scalyr_agent/tests/log_processing_test.py
This commit adds support for container runtimes other than docker.
By default, the monitor will detect whether docker is being used or whether
another CRI compatible runtime (e.g. containerd) is running.  You can force the
use of the CRI codepath with the option `k8s_always_use_cri`.
When using the CRI codepath, you need to map in both `/var/log/containers` and
`/var/log/pods` so that the agent can read the log files from disk.
=> Ticket AGENT-42

scalyr_agent/test_util.py
A month back I introduced unit tests that create multithreaded monitors_manager.
I thought I had solved a hanging issue by deterministically shutting down all started threads (that were blocking the unit test from finishing).
My fix involved passing num_waiters threads to FakeClockCounter and then in sleep_until_count_or_maxwait, we block until those threads all complete.
The fix definitely eliminated the _**frequent**_ hanging. However, now, there is very very occasional hanging. I don't know if this remnant hanging is related but in case it is, I'm going to try to set threads to daemon threads (only in test). This might help eliminate the problem.
No good way to tell except to check this in and observe over time. 
Note that the broken unittest-27 is orthogonal and fixed in [AGENT-116 …
=> AGENT-113 : Unittests still hang non-deterministically (infrequent)

.circleci/config.yml, scalyr_agent/all_tests.py, scalyr_agent/scalyr_logging.py, scalyr_agent/tests/configuration_test.py
I created a new `scalyr/scalyr-agent-ci-unittest` image which fixes the permissions problem.
This image installs python 2.4,5,6,7 using `pyenv`.
With this one image, we can unittest (and potentially smoketest) all versions.
(I will look to combining unittest/smoketest in one image shortly)
This now works for Python 26, 25 and 24.
=> AGENT-102: Use unittest docker image running as user Scalyr

build_package.py, docker/Dockerfile, docker/Dockerfile.build_from_source, docker/Dockerfile.k8s, docker/Dockerfile.syslog, docker/README.md
@imron @czerwingithub I have incorporated @till's  and modified slightly to install ujson.
Latest more complete docker/README.md merged from master.
I ran the docker json/syslog smoketests locally and they passed.
Tested k8s manually and verified logs are uploaded to qatesting.
=> AGENT-103: Reduce docker images (alpine + python27 + ujson)

k8s/scalyr-agent-2-configmap.yaml, k8s/scalyr-agent-2-envfrom.yaml
Current k8s Daemonset and instructions for defining configMap do not use envFrom to import all environment variables in a configMap. (Instead, individual variables from a configMap are explicitly mapped to an environment variable) using the env directive.
Now that we support an expanded list of environment variables, we should be directing customers toward the strategy of defining all desired environment variables in the (same) scalyr-config configMap, but instead of selectively mapping the keyvals -> environment variable, we should just stock import all keyvals.
The difference is that the configMap keys must now be the actual environment variable name, not an arbitrary string.
I hope to release this with 2.0.47.
The reason I would like this with 2.0.47 is in a couple of days we will …
=> AGENT-125: Daemonset and configMap for envFrom

scalyr_agent/builtin_monitors/docker_monitor.py, scalyr_agent/builtin_monitors/tests/data/containers-running.json, scalyr_agent/builtin_monitors/tests/docker_monitor_test.py
Added the `container_globs_exclude` option to the docker monitor, which is a
blacklist of containers to exclude from monitoring, based on container name.
The blacklist is applied *after* processing `container_globs` to see which
containers should be included.
If `None` then no additional exclusions will be applied.
=> Ticket #AGENT-115

scalyr_agent/configuration.py, scalyr_agent/monitor_utils/k8s.py
To avoid query stampeding the API master, fuzz when
we issue queries to fill and revalidate the cache.
We have two separate controls, one for the start delay
and one for the revalidation.
These are default to off.  We will evaulate if we need
to set them based on K8s cluster size.
=> Add fuzz factors in K8s cache

scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/monitor_utils/k8s.py
Removed the dependency on the agent container id, which allowed
me to remove newly added filesystem code.  This hopefully
eliminates one more thing that can go wrong.
Also warn when critical required environment variables are missing.
=> Remove dependency on container id and warn on missing required env vars

scalyr_agent/builtin_monitors/linux_process_metrics.py, scalyr_agent/tests/linux_process_metrics_test.py
I forgot to implement __hash__ and __eq__ for the `Metric` class when fixing our unit tests to work with earlier versions of Python. 
The `Metric` object was being used as keys in a dictionary.  Without those proper dunder methods the dictionary just keeps growing.
This manifests as multiple duplicate metrics (of the same key), leading to eventual omission by the Agent (which has protections against too much metrics data).  This symptom can be seen in the uploaded logs as follows:
**/var/log/scalyr-agent-2/linux_process_metrics.log .... Warning, skipped writing 810 log lines due to limit set by `monitor_log_write_rate` option...`**
Implement __eq__ and __hash__
A straightforward unit test that asserts a dictionary doesn't grow with repeat puts to the same key
=> Fix Metric object memory leak

scalyr_agent/builtin_monitors/linux_process_metrics.py
Unittest 24 are failing from recent Metric memory leak.
This PR fixes that for 2.4 by limiting via modulo.
=> Downcast Metric hash long to int for python 2.4

scalyr_agent/configuration.py
While firefighting Bukalapak's problems we looked into changing compression_type via environment but realized it wasn't environment aware because there is no __verify_or_set_optional_string call on it.
Audit all global config variables to eliminate this problem.
I have gone through configuration.py and found only 2 config params that do not have verify_or_set_xxx called on them. They are:
1. raw_scalyr_server
2. compression_level
I think compression_level should be made env_aware.
raw_scalyr_server seems to just be the original value of scalyr_server so I don't think a verify_or_set is needed/appropriate.
=> AGENT-136: Audit global config params for __verify_or_set

scalyr_agent/builtin_monitors/kubernetes_monitor.py
A trivial PR to remove what seems to be an unused config param in thee kubernetes monitor.
(I think this was copied over from docker monitor?)
=> AGENT-124: Remove metrics_only config param from k8s monitor

k8s/scalyr-agent-2-configmap.yaml, k8s/scalyr-agent-2.yaml, scalyr_agent/builtin_monitors/kubernetes_events_monitor.py, scalyr_agent/configuration.py, scalyr_agent/tests/configuration_k8s_test.py
Currently there is ad-hoc code that looks for `K8S_EVENTS_DISABLE` environment variable. 
There was a todo to make this a global param that's environment-aware. 
This PR adds that global param, taking in from `SCALYR_K8S_EVENTS_DISABLE`. 
It leaves `K8S_EVENTS_DISABLE` in place, thus allowing legacy customers to specify either.
It changes the k8s configmap to set `SCALYR_K8S_EVENTS_DISABLE`.
Additionally, I have updated AGENT-132 to signify the need to adjust documentation. 
Unit tests. Also successful ran in minikube using the updated daemonset yaml that takes in from `SCALYR_K8S_EVENTS_DISABLE`
=> AGENT-139: Make k8s_events_disable an environment-aware global param

scalyr_agent/all_tests.py, scalyr_agent/builtin_monitors/docker_monitor.py, scalyr_agent/tests/configuration_docker_test.py, scalyr_agent/tests/configuration_k8s_test.py
We recently added expanded support to make global config params as well as k8s-related config params "environment-aware"
This needs to be expanded to docker config params as it is a major pain point for docker customers.
This PR makes docker config params environment-aware and also installs unit tests.
=> Make docker config params environment-aware

scalyr_agent/third_party/tcollector/tcollector.py
A customer's disk metrics were not being collected for kubelet mounts where the mount point included the tilde character and was thus rejected by tcollector regex.
=> AGENT-155: Allow tilde in tcollector metrics tags

docker/README.md, k8s/scalyr-agent-2-configmap.yaml
Recent agent-related document changes fail to account for EU customers who need to set scalyr-server. 
AFAICT the affected areas are:
1. k8s example config map
2. docker README
=> AGENT-174: Add SCALYR_SERVER to config map and docker readme

scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py
Due to how the marking process works, we cannot use the same
ControlledCacheWarmer instances between both the metric
fetching and the log container listing.  To fix this, I
created a separate instance for the metrics.
The longer term fix is to move to a single ContainerIterator
instance used by both metrics and logs.  However, that is more
work because we have to make that abstraction thread safe.
=> Create separate ControlledCacheWarmer instance for metrics

scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py
Testing the `already_warm` case is tricky because the test
thread is racing against the ControlledCacheWarmer thread.
In particular, once the ControlledCacheWarmer thread notices
there is a pod to warm (because it was returned from the
`pick_next_pod` method) it (A) first checks if it is already
in the cache and (B) requests it from the API.  For the
`already_warm` case, the entry must in the cache before (A).
Also, if the thread gets to (B), it will block indefinitely
until we simulate an API response.. which we don't do in this
test.  So, we need to make sure it is in the cache before (A).
The easiest way to do this is not invoke `end_marking` until
we simulate placing it in the cache, since `end_marking` is what
adds the pod to the warming list and makes it eligible to
be returned from …
=> Fix non-deterministic already_warm test failure

docker/docker-json-config/agent.d/docker.json, docker/docker-syslog-config/agent.d/docker.json, scalyr_agent/builtin_monitors/docker_monitor.py
The current docker agent defaults to the legacy `docker-api` mode whereby raw logs mounted on the agent container are not directly monitored, rather stdout/err logs are gotten via docker api, written to disk once more, and those files monitored.
We originally kept the legacy mode as default in order not to impact existing customers. However, that approach is not only suboptimal but the docker api is not 100% reliable. 
The better approach is to directly monitor mounted other-container logs (raw logs mode). 
This PR changes the default mode to that and also emits a warning whenever a mounted container log file is missing (e.g. in the case where customer fails to mount the docker storage directory per instructions).
Manually: 
1. ensured `Starting docker monitor (raw_logs=True)` is emitted …
=> AGENT-121: Change default docker mode to raw-logs

scalyr_agent/json_lib/parser.py, scalyr_agent/json_lib/tests/encode_decode_test.py, scalyr_agent/tests/configuration_k8s_test.py, scalyr_agent/tests/configuration_test.py, scalyr_agent/tests/linux_system_metrics_test.py
While attempting to remove rate limits on linux system metrics monitor for AGENT-175, I discovered that setting -1 for int config variables raises a type conversion error.   Apparently, -1s are parsed into longs and subsequently fail type-conversion to int.
This PR fixes the json parser library to handle negative ints.
=> AGENT-55: Negative int config variables are incorrectly parsed as longs.

scalyr_agent/platform_posix.py
Standalone agent creates files that are other and group writable (logfiles, temp status file, checkpoint files).
platform_posix.py:__daemonize() explicitly resets umask(0), thus causing agent python process to not inherit/honor environment umask settings.
k8s and docker agents do not daemonize(), hence are not subject to this code path. Therefore, they inherit default linux umask of 0022 and thus produce tighter permissions.
Solution is to simply set umask(0022) instead of umask(0), given that there was no intentional motivation behind setting umask(0) aside from copying the UNIX double-fork recipe.
Ran agent and verified files were correct permissions.
=> AGENT-182: Umask 0022 for posix systems

.circleci/config.yml, .circleci/smoketest_docker.sh, .circleci/smoketest_k8s.sh
K8s smoke test operational.
- starts an `agent` pod to monitor cluster
- starts an `uploader` pod that writes to stdout/stderr (uploader pod queries qatesting to verify agent is working before it starts uploading)
- starts a `verifier` pod that  (verifier pod queries qatesting to verify agent is working before then querying for uploader log data)
As before, these smoke/unit tests are not code-reviewed pending cleanup/organization of various scripts and Dockerfiles used to construct test docker images.
=> AGENT-122: K8s smoke test

scalyr_agent/test_base.py, scalyr_agent/tests/util_test.py, scalyr_agent/util.py
This is meant to investigate the case where the test process does
not exit because it is waiting for some thread to stop that will
never stop.
To implement this, I added the ability to set a name prefix for
all StoppableThreads created.  The test framework uses this to set
a prefix including the test case, so that all threads can be tied
back to the test case that created it.
Also created a thread in the testing framework which will wait
60s for the tests to finish.  If they do not (and hence hung),
it will print out all active thread names.
Hopefully this will help give information about which test case
is creating threads that hang the tests.
=> Added test feature to help investigate hung threads

scalyr_agent/configuration.py, scalyr_agent/scalyr_client.py, scalyr_agent/tests/util_test.py, scalyr_agent/util.py
Currently, the agent does not compress uploaded data by default. Even though it does _not_ affect customer billing, I propose changing this to use bz2 compression by default as there is no reason not to.
Some customer machines may not have requisite compression libraries installed on their systems. Therefore the agent must check to ensure compression works correctly.
- New unit tests that require positive confirmation of compression capabilities (not just import) before turning compression on.
- Smoketests verify upload works.
=> AGENT-166: Default compression_type to bz2

scalyr_agent/builtin_monitors/kubernetes_monitor.py
In a previous PR, this setting was inadvertently defaulted to False.
This PR restores it (and also harmonizes it with the documentation)
=> Restore report_k8s_metrics default to True

scalyr_agent/configuration.py
Now that we've concluded the main problem was likely big JSON requests and removed those, we can push the k8s api masters much more aggressively.
The ratelimiter was recently changed to consider existing rate in calculating the new rate.  As such, it will not simply double until reaching the configured max-rate.  Therefore, the more important rate to configure is the _initial_ rate.  In this PR I'm setting it to 1000 (Starting at 200 in a recent 1000-node cluster was just fine, so 1000 for less constrained clusters should be good).
The max rate is set to 1E9, which, is effectively infinity (in a 5K cluster, it'll be 200K rps, which is in the order of what we saw attained in the setting of a 1000-node cluster)
I am leaving the cacherwarmer retry settings unchanged as these pertain to …
=> AGENT-189: Make ratelimiter defaults more aggressive

scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/configuration.py, scalyr_agent/monitor_utils/k8s.py, scalyr_agent/monitor_utils/tests/k8s_test.py
This is part of the option-b -> master integration effort.
In this PR, I do the following:
Productize the saving of JSON responses, including various configuration settings as discussed
Restrict k8s /version check to every hour
Note: This PR/branch replaces the [original PR which was approved, but became difficult to merge when I rebased `option-b/master`](https://github.com/scalyr/scalyr-agent-2/pull/257). Please see that original PR for the review discussion.
=> AGENT-183:  Productize saving of k8s json responses. Version-check hourly.

scalyr_agent/tests/copying_manager_test.py, scalyr_agent/tests/scalyr_client_test.py
1.  Fix issue with the scalyr_client where the testing code was
not properly clearing out some global state.
2.  Fix the CopyingManager end-to-end tests.  The testing code has
several issues in its use of two condition variables.  Simplified
code so that there were no longer any race conditions.  Also
added in deadlines for waiting on the condition variable to
prevent the tests hanging indefinitely.
=> AGENT-64: Fix several skipped tests

.circleci/config.yml, .circleci/smoketest_docker.sh, .circleci/smoketest_k8s.sh, .circleci/smoketest_standalone.sh
This PR is the result of many iterations trying to unify unit/smoke tests.  Supporting older python versions is a real pain but I think this PR finally succeeds in doing so with a single docker image.  (Note the docker file for creating the test image will be in a separate repo). 
- Modify circleCI yaml to use new unified image
- Checkin standalone smoketest code into this repo
=> AGENT-187: Move standalone smoketest code into repo.  Unify unit/smoke tests into single image.

scalyr_agent/connection.py
I don't fully understand why it didn't manifest in the existing smoketest image (most likely due to the pre-built python 2.5 binary that is used in that image was compiled such that the bug did not manifest).  
I think what I've done in this PR is the correct thing to do though as it codes defensively against missing `_tunnel_host` (which we already do in other areas of the code but apparently miss 2 spots)
=> AGENT-186: Check for _tunnel_host

scalyr_agent/log_processing.py, scalyr_agent/tests/log_processing_test.py
total_bytes_skipped is reported incorrectly for k8s. Cause seems to be log_proccessing.perform_processing incorrectly calculates uploaded bytes from the log message without taking into account other json attributes.
Manifestation is very scary-looking agent_status lines that keep increasing in total_bytes_skipped.
=> AGENT-223: Fix total_bytes_skipped recording bug

scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/config_util.py, scalyr_agent/tests/configuration_k8s_test.py, scalyr_agent/tests/configuration_test.py
Empty string config params are currently treated identically as if they were not defined at all. 
This fails to allow customers to override config params that have default values (e.g. `k8s_ignore_namespaces` is currently set to `kube-system`). 
For example, a customer may want to include `kube-system` namespace and should be able to define `SCALYR_K8S_IGNORE_NAMESPACES`: ""` (empty string), thus allowing `kube-system` namespaced pods to be logged.
This PR changes the config param framework code to allow empty strings to be converted where it makes sense (for example if a config param is a `str` or `ArrayOfStrings` or `bool`).
Please see the new unit tests for clarity
This PR is based off [AGENT-236-k8s-ignore-namespaces](https://github.com/scalyr/scalyr-agent-2/pull/286) branch because …
=> AGENT-241: allow empty config params

scalyr_agent/builtin_monitors/kubernetes_events_monitor.py, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/config_util.py, scalyr_agent/configuration.py, scalyr_agent/json_lib/__init__.py, scalyr_agent/json_lib/objects.py, scalyr_agent/monitor_utils/k8s.py, scalyr_agent/scalyr_monitor.py, scalyr_agent/tests/configuration_k8s_test.py, scalyr_agent/tests/configuration_test.py, scalyr_agent/tests/scalyr_monitor_test.py
`k8s_ignore_namespaces` is inconsistently handled.  It should be typed as an `ArrayOfStrings`, which is comma-delimited.  This enables user to specify a single comma-separated string environment variable, consistent with some other parameters.
However, to preserve legacy behavior (splittable by whitespace), I define a new type `SpaceAndCommaSeparatedArrayOfStrings` which is a subclass of `ArrayOfStrings`.  (And necessary plumbing to make it work).
1. Make `k8s_ignore_namespaces` an SpaceAndCommaSeparatedArrayOfStrings.
2. Remove duplicate `k8s_ignore_namespaces` from `kubernetes_monitor.py`
- Augmented `_test_environment_aware_global_params` to handle ArrayOfString types.
- manual testing: Entered the following configmap entry:
`SCALYR_K8S_IGNORE_NAMESPACES: "kube-system a , b , c"`
- …
=> Make k8s_ignore_namespaces an ArrayOfStrings

scalyr_agent/configuration.py
Release 2.0.51 will contain several undocumented config params (to be used only in rare cases under direct guidance by Support).
This PR tags those params with a comment tag.
=> Mark undocumented config params

.circleci/config.yml, .circleci/docker_unified_smoke_unit/Dockerfile.unittest, .circleci/docker_unified_smoke_unit/smoketest/override_files/agent.json, .circleci/docker_unified_smoke_unit/smoketest/smoketest.py, .circleci/docker_unified_smoke_unit/unittest/unittest.sh
This PR checks in files for creating the unified docker image for unified smoke/unit test.  [ That image is already being used for unit and smoke tests but the code has been in a private repo. ]
Secondly, also checks in `smoketest.py` into this repo. [ `smoketest.py` is the python code that launches `Uploader` and `Verifier` processes to verify various forms of the agent (i.e. the smoketest logic)]
The smoketest is a distributed system test that follows the general strategy:
1. launch an agent
2. launch an `Uploader` process that generates data that the agent will ingest and upload.
3. launch a `Verifier` that queries the Scalyr backend for the Uploader data, thus confirming that the agent works overall.
1. First built a new version of the unified image with `docker build -f …
=> Unified smoke/unit test docker image and smoketest script

.circleci/docker_unified_smoke_unit/Dockerfile.sanity.centos, .circleci/docker_unified_smoke_unit/Dockerfile.sanity.ubuntu, .circleci/docker_unified_smoke_unit/Dockerfile.unittest, .circleci/docker_unified_smoke_unit/smoketest/smoketest.py, .circleci/smoketest_release_standalone.sh, .circleci/smoketest_standalone.sh
This PR adds a smoketest script and dockerfiles to run a release-related "sanity check" (smoketest).  Basically, instead of getting code from the agent git repo, it takes a provided artifact (rpm, debian, tarball etc), mimics the user installation procedure and runs the smoketest on the installed agent.
=> Smoketest and dockerfiles for Release automation

performance/kops_cluster_setup/agentscale.yaml, performance/kops_cluster_setup/create_agentscale_yaml.sh, performance/kops_cluster_setup/fivezones.yaml, performance/kops_cluster_setup/sample_commands.txt
This PR commits the kops script and customizations used to successfully create a kops-managed cluster (1000 nodes).   
The recent 2.0.51 agent release contains major code changes which were validated on this 1000-node cluster (primarily eliminate CPU and outbound network traffic due to 1000 agents accessing the api masters)
=> Kops setup scripts

scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py
The Scalyr UI "Log Sources" overview page has always listed out individual entries of  `serverHosts` of a k8s cluster.  For large clusters, this page becomes super long.  The fix is to attach a `_k8s_ver` attribute to events coming from k8s serverHosts.  This allows the UI to no longer display these serverHosts as individual items in the "Log Sources" overview.
Note: A side effect is from now on, you can no longer enter a k8s serverHost into the serverHost search box and expect the logFile search popdown to be populated with all logfiles from this serverHost.  
However, the `logfile` facet will still list out all logfiles, include agent.log
The k8s_ver attribute code change was committed previously but commented out because backend/api layer changes were not ready.  These dependencies are …
=> AGENT-249: Turn on k8s_ver

.circleci/docker_unified_smoke_unit/Dockerfile.sanity.centos, .circleci/docker_unified_smoke_unit/Dockerfile.sanity.ubuntu, .circleci/smoketest_release_standalone.sh
This PR fixes a bug where the smoketest of the primary `install-agent.sh` script was broken.
Also runs the script under `sudo` which avoids errors in ubuntu.
=> Fix bug in smoketest_release_standalone.sh

performance/kops_cluster_setup/README.md, performance/kops_cluster_setup/agentscale.yaml, performance/kops_cluster_setup/create_agentscale_yaml.sh, performance/kops_cluster_setup/fivezones.yaml, performance/kops_cluster_setup/sample_commands.txt
This PR replaces scalyr-specific kops settings (bucketname, cluster name) with placeholders to emphasize the need for users to customize these.
=> Replace scalyr-specific variables with placeholders

scalyr_agent/builtin_monitors/docker_monitor.py, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/tests/configuration_docker_test.py, scalyr_agent/tests/configuration_k8s_test.py
Testing for this has been done manually, both for the kubernetes and docker monitors.
One interesting thing when listing the individual cpus is that the kubernetes monitor specified an extra field of `dev`, while the docker monitor specifies `cpu`.
There was a bug with the docker monitor that prevented it from actually outputting that extra field, which I've now fixed, but perhaps we want to standardize on a single key for this field?
Also, it turns out the other cpu metrics *were* getting logged, just in a separate place (which is why I didn't notice previously).
Here's a snapshot of relevant entries in `kubernetes_monitor.log`:
=> AGENT-248 - put percpu metrics behind an option

docker/Dockerfile, docker/Dockerfile.build_from_source, docker/Dockerfile.k8s, docker/Dockerfile.syslog
There are some performance concerns for alpine image which uses musl instead of glibc
https://superuser.com/questions/1219609/why-is-the-alpine-docker-image-over-50-slower-than-the-ubuntu-image
We are changing to use `slim` image.
I ran `python build_package.py k8s_builder|docker_syslog_builder|docker_json_builder` and tested each docker image manually.  Also, the smoketests do these as well.
=> AGENT-252: Replace alpine with slim image for performance reasons

docker/Dockerfile, docker/Dockerfile.build_from_source, docker/Dockerfile.syslog
Due to an unfortunate merge sequence another branch that included a revert of this PR was merged to master after the original PR for this was made, thereby undoing this feature.
This is a cherry pick of the original commit, to replace alpine with slim.
=> Replace alpine with slim image for performance reasons

scalyr_agent/json_lib/serializer.py, scalyr_agent/json_lib/tests/serializer_test.py
I deleted one test because it relied on UTF-32 decoding to 32bit
characters, which is not a guaranteed in Python 2.7.  Unichrs
can be either 16bit or 32bit.  Since this is such a small case
and I couldn't find a way to determine if unichr where 32 or 16,
I just had to delete the test.
Medium term, we might just want to delete the slow encoding code
paths.  This JSON library should really only be used to talk to
the Scalyr server... and the Scalyr server relies on the fast
encoding code paths.  I see there are a few places in the code
where we still use this to serialize for places other than
/addEvents.  We should just move those to the standard json
libraries.
=> Make fixes to enable json slow encoding

scalyr_agent/tests/util_test.py, scalyr_agent/util.py
The primary issue was that some tests would check the current
time on a fake clock, if it wasn't great enough, wait until
the clock advanced by waiting for notifications on it.  However,
that first check was not atomic wrt to the waiting... so it was
possible for advances/notifications to be missed between the two
steps.
To fix this, we had to introduce a way to atomically check the
clock value while waiting for advances on it.
=> Fix some bugs that resulted in tests hanging.

scalyr_agent/__scalyr__.py
Due to pretty complicated reasons, on systems that already have
a backports module defined, we cannot override it with our own
from third_party, even if we put the third_party directory in the
front of the PYTHONPATH.
This hasn't impacted customers since only Docker relies on this
and for Docker, we control the version of Python installed in
the base image.  However, if you are running tests in your
local machine, you might hit this.
Added a hack to fix this issue.
=> Fix issue importing third_party backports

run_tests.py, scalyr_agent/all_tests.py, scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py, scalyr_agent/monitor_utils/tests/annotation_config_test.py, scalyr_agent/monitor_utils/tests/blocking_rate_limiter_test.py, scalyr_agent/monitor_utils/tests/k8s_test.py, scalyr_agent/monitor_utils/tests/server_processors_test.py, scalyr_agent/test_base.py, scalyr_agent/tests/agent_status_test.py, scalyr_agent/tests/auto_flushing_rotating_file_test.py, scalyr_agent/tests/configuration_test.py, scalyr_agent/tests/copying_manager_test.py, scalyr_agent/tests/linux_process_metrics_test.py, scalyr_agent/tests/log_processing_test.py, scalyr_agent/tests/platform_posix_test.py, scalyr_agent/tests/scalyr_client_test.py, scalyr_agent/tests/scalyr_logging_test.py, scalyr_agent/tests/syslog_monitor_test.py, scalyr_agent/tests/url_monitor_test.py, scalyr_agent/tests/util_test.py, scalyr_agent/util.py
This fixes the tests so that all output generated by our use
of the Python loggers will be captured during unittest execution.
To do this, needed to set the use of stdout for our logging whenever
we are about to run a test case.
Suggest review path:  Look at test_base.py first.  Almost all other changes are just to added in calling the inherited setUp method.
=> Fix unittest to capture output generated by loggers

scalyr_agent/builtin_monitors/linux_system_metrics.py, scalyr_agent/third_party/tcollector/collectors/0/dfstat.py, scalyr_agent/third_party/tcollector/tcollector.py
Tcollector's dfstat metrics specifically excludes non-local filesystems
(such as NFS mounted file systems).  We have some customers who would
like to include NFS mounts in the reported metrics.  Added an option
that would allow them to control this behavior.
=> Add option to linux_system_metrics for non-local filesystem metrics

.circleci/smoketest_k8s.sh, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/monitor_utils/k8s.py, scalyr_agent/tests/configuration_k8s_test.py
This adds a sidecar logging mode for use in Kubernetes, which can be necessary when sending a higher volume of log data than a single agent is able to keep up with.
This PR adds the environment variable `K8S_SIDECAR_MODE=` `true|false`.
When sidecar mode is enabled, the Kubernetes monitor uses additional logic in ContainerEnumerator.get_containers() to filter the container list to only those which belong to the Pod which the agent is running within. 
Additionally, the logic to avoid capturing the agent's own Kubernetes log file is disabled. This is because presently that is excluded by excluding the agent's own pod name, but in this case with sidecar mode, capturing the agent's own pod is desired. This was discussed and impact is seeing the agent container in the Scalyr UI, if the Agent …
=> Feature: Kubernetes Sidecar Mode for High Volume Logging

build_package.py
Intermediate certs were causing validation to fail for some reason.
=> #AGENT-283 Don't include intermediate certs in win32 build

scalyr_agent/log_processing.py, scalyr_agent/tests/log_processing_test.py, scalyr_agent/third_party/README.md, scalyr_agent/third_party/glob2/__init__.py, scalyr_agent/third_party/glob2/compat.py, scalyr_agent/third_party/glob2/fnmatch.py, scalyr_agent/third_party/glob2/impl.py, scalyr_agent/third_party/licenses/LICENSE_glob2.txt
Python's builtin glob module does not support recursive globbing with ** until Python 3.5.
As we presently support Python 2.7, this change moves to using the third-party library glob2 which supports **
(Resubmitting to fix CircleCI)
=> Bug: Fix Support for recursive ** globs by switching to glob2 library

scalyr_agent/log_processing.py, scalyr_agent/tests/log_processing_test.py
The test `test_matches_recursive_glob` in tests/log_processing_test.py was non-deterministic. 
This sorts the returned list of log processors to fix that. I've run it multiple times and seems to always pass now.
=> Bug: Fix non-deterministic glob2 test

scalyr_agent/scalyr_client.py
This was causing the new addEvents format to not be parsed by the server.
=> Fix issue where log id was missing for kubernetes logs

scalyr_agent/builtin_monitors/kubernetes_events_monitor.py, scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py, scalyr_agent/config_main.py, scalyr_agent/config_util.py, scalyr_agent/configuration.py, scalyr_agent/copying_manager.py, scalyr_agent/json_lib/exceptions.py, scalyr_agent/json_lib/tests/encode_decode_test.py, scalyr_agent/log_processing.py, scalyr_agent/run_monitor.py, scalyr_agent/scalyr_client.py, scalyr_agent/scalyr_logging.py, scalyr_agent/test_util.py, scalyr_agent/tests/annotation_config_test.py, scalyr_agent/tests/configuration_test.py, scalyr_agent/tests/copying_manager_test.py, scalyr_agent/tests/log_processing_test.py, scalyr_agent/tests/scalyr_client_test.py, scalyr_agent/tests/scalyr_monitor_test.py, scalyr_agent/tests/util_test.py, scalyr_agent/util.py
We will be deprecating the use key parts of json_lib such
as its own serialization to help reduce the amount of tricky
string Python 2 to 3 work we must do.
To help with this, this changes:
1.  Moves all references to the json_lib parsing and serialization
code to a few central methods in `util.py` so that we can
very easily see what is using the serialization.  Also added
more meaningful function names to capture why the parsing or
serialization is being used.
2.  Eliminates places where json_lib is used to parse or serialization
JSON objects when it is not really needed.  It really is only
need for parsing config files (which might have comments) and
serializing JSON for requests to Scalyr.  All other uses
have been eliminated.
Note:  Some "risky" changes are that the checkpoint files …
=> Refactor and reduce use of json_lib

pyproject.toml
Exclude third_party_python2, very small change.
=> Exclude third_party_python2 from black refactor.

scalyr_agent/log_processing.py, scalyr_agent/scalyr_client.py, scalyr_agent/tests/scalyr_client_test.py
The result of a missed case (log line specific attributes) during the changes to the addEvents format. This PR changes `add_missing_attributes` to act differently depending on if the attributes being added are log line specific or general to the log file overall.
=> AGENT-323: Missing `stream` event attribute in Docker and K8s

scalyr_agent/scalyr_logging.py, scalyr_agent/tests/scalyr_logging_test.py
Added ability to save the last record produced by a logger in order
to investigate a flaky logging test.
Hopefully this extra information will help debug the issue the next time it occurs.
=> #313 Investigate flaky logging test

scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/monitor_utils/k8s.py
Added extra logging to help investigate flaky K8s smoke
test when run in CircleCI.  It appears as if the container
runtime environment cannot be determined.
=> Investigate K8s flaky test

scalyr_agent/monitor_utils/k8s.py
We got some more information on what is causing the K8s flaky test.
Of course though, I didn't get everything I needed.  Here's
some more output.
=> Futher investigate flaky test

scalyr_agent/monitor_utils/k8s.py
Force retry of querying the agent's container's id if the API
server indicated the container is still not ready.  This would
result in the CRI determination failing and the K8s tests to
fail.
=> Fix flaky smoke-k8s test

.circleci/.coveragerc_ci, .circleci/config.yml, README.md, codecov.yml
Small change which updates existing ``coverage`` Circle CI job to submit combined / aggregated coverage data to codecov.io service.
This means that in addition to the raw plain text code coverage output which is currently displayed in the Circle CI job output we now also get nicer visualization such as this one - https://codecov.io/gh/scalyr/scalyr-agent-2/branch/submit_code_coverage_to_codecov.
In addition to the nice web based visualization, we also get two other things:
1. Pull request comments with information about coverage for a specific PR
2. Ability to define a coverage threshold (either absolute or relative) and fail a PR via Github status check if that threshold is not reached
=> Submit code coverage reports to codecov

scalyr_agent/scalyr_logging.py, scalyr_agent/tests/scalyr_logging_test.py, scalyr_agent/tests/util_test.py
While working on #377, I noticed ``ScalyrLoggingTest.test_rate_limit_no_write_rate`` tests fails very often.
After digging in, I believe I found an issue in the test itself and a potential fix / workaround.
Right now we set ``max_write_burst`` aka ``bucket_size`` to 250 bytes.
The problem is that the actual message string value we use when determining the message size is the fully formatted string and that string is much longer than the original string we pass to the logger method in the tests. 
Formatted string value also contains module name, timestamp and for the first successfully logged message after the rate limit being hit, it's also prefixed with a warning that a previous message has been rate limited.
For example:
```bash
.... Warning, skipped writing 1 log lines due to limit set …
```
=> Fix intermediately failing logging rate limit test

scalyr_agent/tests/url_monitor_test.py
Unfortunately, I missed another similar test that does not pass on python3.5 because of `dict` order..
=> Another Python 3.5 dict order related test fix.

scalyr_agent/json_lib/parser.py, scalyr_agent/json_lib/tests/parser_test.py
Return back the ability to pass bytes string to `json_lib.parse` where then it will be converted to unicode.
=> json_lib.parse converts byte strings to unicode before parsing.

README.md, docs/architecture.md
This pull request adds a document which describes agent architecture and core code abstractions.
It's mostly based on the notes I took yesterday during the brain dump from @czerwingithub.
I decided to add it here instead of internal wiki for 2 main reasons:
1. This document contains no proprietary or sensitive information. It just documents the concepts and components which are open-source and part of this repo.
2. I believe documentation should live as close to the source as possible. In this case, that's this repo.
I have bad experience with "central" wikis or similar. Usually when such information is not co-located with the code, it's a much higher chance it will get out of date.
And I would argue that out of date / wrong documentation is better than no documentation.
That's also the …
=> Add document which describes agent architecture and core code abstraction

scalyr_agent/scalyr_client.py, scalyr_agent/tests/configuration_test.py, scalyr_agent/util.py
I tried to run latest version of master under Python 2 and Python 3 while testing the signals change and I encountered some exceptions in the log related to mixing bytes and unicode.
This pull request fixes two small issues I've encountered.
There are likely many more which will only be uncovered only while running the agent and that's where a more systematic approach + end to end tests come into play.
Ideally as part of end to end tests, we would spin up an agent process under Python 2 Python 3 with some real life configuration and DEBUG level set and then we would grep agent.log and agent_debug.log for exceptions / errors and work from there.
=> Fix a couple of small Python 2 and 3 compatibility issues

codecov.yml
Just testing to see if this will help with the "Missing base report" codecov issues which appear to be related to our merging strategy (rebase with squash).
=> Test a codecov reporting change

scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/configuration.py, scalyr_agent/monitor_utils/k8s.py, scalyr_agent/tests/configuration_test.py
This adds in more diagnostic information describing why the K8s
cache fails to initialize.  This also changes the agent to
restart if it is not initialized within 2 minutes.  (Customers
reporting this issue say that restarting the agent usually solves
the problem)
=> AGENT-330  Add defensive code to investigate K8s initialization issues

k8s/scalyr-agent-2-envfrom.yaml
Mostly done through running `kubectl convert -f k8s/scalyr-agent-2-envfrom.yaml`, with some minor manual reordering.
From my testing this change should work just fine for Kubernetes versions 1.9 and higher, and our stats show no one using versions older than that.
=> Update the `envfrom` yaml to use `apps/v1` apiVersion

.circleci/config.yml
This pull request updates Circle CI usage report job to send email to the new mailing list used for build notifications.
=> Send Circle CI usage reports to the new mailing list

scalyr_agent/copying_manager.py, scalyr_agent/tests/copying_manager_test.py
This pull request updates copying manager to log the whole server response body in case server returns a non-successful response (aka ``status != 'success'``).
This now makes it possible to troubleshoot and track down issues when server returns a non-successful response or we fail to parse the response (previously it wasn't possible to track down some issues since we didn't have enough information in the logs and the only option would be to look up actual response in the API logs, but even then this wouldn't be enough in cases where the bug lies in the agent code).
See https://github.com/scalyr/scalyr-agent-2/commit/13ee02e4039a016660185c122411d2a3803fbb62 for some more context.
=> Improve response debug logging in the copying manager

scalyr_agent/builtin_monitors/linux_process_metrics.py, scalyr_agent/scalyr_monitor.py, scalyr_agent/tests/linux_process_metrics_test.py
This pull request fixes ``app.disk.requests`` (``type={read,write}``) metric type.
Those two metrics represent a total number of read / write requests (counter) so bytes is not a correct unit.
=> Fix metric types for "app.disk.requests" metrics

.pre-commit-config.yaml, README.md
This pull request updates pre-commit config file so it matches our lint configuration from ``tox`` config.
This means pre-commit now runs the same checks (with the same configuration) as running ``tox -e lint`` does.
By default, ``pre-commit`` creates virtual environment for each check / hook, but I wanted to avoid that since we already have a virtual environment with all the dependencies for out tox targets (not to mention that there are also dependency version and configuration issues there).
=> Update pre-commit configuration so it matches tox lint configuration

.circleci/modernize/modernize.py, .pre-commit-config.yaml, lint-configs/python/mypy.ini, tox.ini
This pull request contains three fixes / improvements to the pre-commit config:
1. Add missing ``types`` attribute to the pylint check. Without that, it will try to run pylint on all the files and not just Python ones.
2. Update ``black`` hook and make sure that also automatically formats the files and doesn't just perform a check.
Performing just a check is desired behavior for the CI, but pre-commit hook should also apply auto formatting fixes.
3. Make sure we run MyPy in incremental mode - this way it will use local cache and the runs will be faster.
Keep in mind that's it's desired that on the CI (such as ``tox -elint`` target) we don't use cache to avoid any stale cache related issues, but during local development where pre-commit runs, using cache is desired, otherwise MyPy check …
=> Small pre-commit config fixes and improvements

scalyr_agent/builtin_monitors/syslog_monitor.py, scalyr_agent/compat.py, scalyr_agent/json_lib/serializer.py, scalyr_agent/monitor_utils/server_processors.py, scalyr_agent/monitor_utils/tests/server_processors_test.py, scalyr_agent/platform_windows.py, scalyr_agent/test_util.py, scalyr_agent/tests/util/util_test.py, scalyr_agent/util.py
Fix struct wrapper in `compat` module, because the problem with unicode incompatible strung remains until python2.7.7.
=> fix struct.pack|unpack wrapper for python < 2.7.7

scalyr_agent/config_main.py
This pull request fixes an issue with system wide six library being used instead of the one we bundle with the package.
The reason for that was that we imported six before calling ``scalyr_init()`` which set ups ``PYTHONPATH`` and adds ``third_party/`` directory for it.
---
Catching such issues with tests is a bit hard since we would need to cover many different environments and it still wouldn't cover everything.
To avoid such issues in the future, I would recommend writing a lint / check script which checks all the Python files and fails with an error if any of the bundled library is imported anywhere before ``scalyr_init()`` is called.
I think it would be sufficient to just check the file header aka the top global part with imports.
=> Fix six import in config_main.py

.circleci/config.yml, scalyr_agent/scalyr_client.py, scalyr_agent/tests/scalyr_client_test.py
This pull request fixes increased memory usage under Python 2.7 we observed recently on our CodeSpeed instance.
A week or so ago after setting up CodeSpeed instance, we observed increased memory usage of the agent benchmark which runs loaded agent under Python 2.7. The issue didn't appear when running the agent under Python 3 or when running idle configuration (aka agent doesn't monitor any log files).
To put things into context - benchmarks which run under Python 3 show a couple of MB more memory usage compared to Python 2.7 pre-Python 3 changes, but that's expected and nothing to worry about. The problematic one was Python 2.7 where memory usage almost doubled (from around 30 MB to around 60 MB).
We originally thought it may be something related to unicode changes (under Python 2.7 …
=> Fix increased memory usage under Python 2.7 when debug log level 5 is set

scripts/circleci_usage_data.py
I noticed that usage cron job failed during the weekend (https://app.circleci.com/jobs/github/scalyr/scalyr-agent-2/19507/parallel-runs/0/steps/0-102) so I decided to add a bit more logging to the script.
I'm almost positive that the failure is related to a (temporary) issue with the Circle CI API, but it still doesn't hurt to have better logging in such scenarios.
=> Improve error handling in Circle CI usage data script

lint-configs/python/mypy.ini, scalyr_agent/configuration.py, scalyr_agent/json_lib/objects.py, scalyr_agent/tests/fixtures/configs/agent2.json, scalyr_agent/tests/test_memory_leaks.py, scalyr_agent/util.py, setup.cfg, tox.ini
This pull request fixes memory leak in the ``Configuration.parse()`` method.
---
I was tracking down memory leak in the agent and with various memory and GC instrumentation I got pointers to the agent main loop.
Each time the agent main loop ran and config was reloaded / re-read from disk, number of unreachable objects which can't be collected increased.
I confirmed that's indeed the root cause by adding ``continue`` statement to the main loop before ``self.__verify_config`` method call. With that continue statement in place, number of uncollectable objects stayed constant and didn't increase after each agent main loop run.
After diving in further, I found a memory leak inside ``Configuration.parse()`` method, more specifically, ``__perform_substitutions`` method which is called by …
=> Fix memory leak in the Configuration.parse() method (aka Configuration object)

scalyr_agent/third_party/tcollector/tcollector.py
I noticed that under Python 3, tcollector throws an exception when keys are to be evicted from the cache:
```bash
File "/home/kami/.pythonz/pythons/CPython-3.6.9/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/home/kami/w/scalyr/scalyr-agent-2/scalyr_agent/third_party/tcollector/tcollector.py", line 327, in run
col.evict_old_keys(now)
File "/home/kami/w/scalyr/scalyr-agent-2/scalyr_agent/third_party/tcollector/tcollector.py", line 235, in evict_old_keys
for key in self.values.keys():
RuntimeError: dictionary changed size during iteration
```
The issue is related to ``dict.keys()`` method in Python 3 returning a dictionary view object and not a simple list, which shouldn't be changed during the iterator.
To work around that, we create a simple list version of …
=> Fix Python 3 related errors in the tcollectors

lint-configs/python/mypy.ini, pylint_plugins/bundled_imports_checker.py, tox.ini
This pull request adds a pylint plugin which checks for the issues like the one fixed in #429.
It works by inspecting any file which calls ``scalyr_init()`` and ensures any import of a bundled module comes after that line.
Right now it's limited to the modules which call ``scalyr_init()`` directly and doesn't support indirect imports (e.g. module A calls scalyr_init() and imports module B and module B imports a bundled import).
This means it won't catch 100% of the edge cases, but it's better than nothing (implementing indirect import tracking would be much more involved).
Here is the error message pylint / build would fail with if we ran it on commit before #429 was merged:
```bash
************* Module scalyr_agent.config_main
scalyr_agent/config_main.py:40:0: E8002: Import "six" is on …
```
=> pylint plugin for checking / enforcing ordering of bundled third party module imports

build_package.py, scalyr_agent/tests/util/util_test.py, scalyr_agent/util.py
Fixed issue related to 2->3 strings and unicode.  We were not
properly using a binary string when concat'ing it with a UUID.
=> Fix string issue when building Windows package

lint-configs/python/mypy.ini, scalyr_agent/agent_main.py, scalyr_agent/configuration.py, scalyr_agent/profiler.py, scalyr_agent/tests/test_memory_leaks.py, scalyr_agent/third_party/tcollector/tcollector.py, scalyr_agent/util.py
This pull request adds memory profiler which is based on the pympler library (https://pythonhosted.org/Pympler/).
I followed the existing Profiler abstraction and made it "pluggable" so we now have two types of profilers - CPU profiler and Memory profiler.
To avoid introducing more configuration options (we already have many), I decided to use existing configuration options which are already used for the CPU profiler (enable_profiling, profile_duration_minutes, max_profile_interval_minutes, etc.).
In the future, if we want more flexibility (e.g. different profiling duration and interval for CPU and memory profiler) we can introduce additional configuration options for the memory profiler.
Memory profiling data is written to ``<data dir>/agent.meminfo`` file. Here is the example output - …
=> Add memory profiler

.circleci/config.yml, benchmarks/configs/agent.d/server.json, benchmarks/scripts/start-agent-and-capture-metrics.sh, scalyr_agent/config_util.py, scalyr_agent/configuration.py, scalyr_agent/tests/configuration_test.py
This pull request includes a couple of related changes:
1. Update agent config which is used with benchmarks to utilize production server instead of the qa testing one.
2. Make ``server_attributes`` config option environment aware. This allows us to dynamically set this value instead of relying on config rewrites (which is what smoketests currently do)
3. Update benchmark Circle CI jobs to use unique ``server_attributes.serverHost`` for each run to make troubleshooting / debugging easier.
=> Use production server for agent benchmark runs, make "server_attributes" config option environment aware

.circleci/config.yml, benchmarks/configs/agent.d/server.json, benchmarks/configs/agent_single_50mb_access_log_file_gc_metrics.json, benchmarks/scripts/common.sh, benchmarks/scripts/send-log-level-counts-to-codespeed.sh, benchmarks/scripts/send_usage_data_to_codespeed.py, benchmarks/scripts/start-agent-and-capture-metrics.sh, scalyr_agent/agent_main.py, scalyr_agent/agent_status.py, scalyr_agent/configuration.py, scalyr_agent/tests/configuration_test.py
This pull request adds new ``gc_stats.garbage`` metric to the agent status output (right now only to the machine readable aka json format).
This value contains a number of uncollectabe objects after a GC run (those are the objects which are not reachable anymore and can't be collected - due to a cyclic reference to itself or similar).
This will allow us to more easily detect regressions and catch memory leaks like 3 big ones which have been fixed in #435 
Do keep in mind though that this only reports uncollectable objects which are unreachable.
If some piece of code which is in use (aka reachable) incorrectly keeps a reference to some other object or similar, this won't be reported in that number.
---
The plan is to hook this metric to CodeSpeed to allow us to catch such memory leak …
=> Add (opt-in) Garbage Collection related metrics to the agent status output

scalyr_agent/profiler.py
Small fixed for the CPU profiler ``is_running()`` method which would throw if ``yappi`` module is not installed.
=> Fix is running method on the CPU profiler

scalyr_agent/agent_main.py, scalyr_agent/builtin_monitors/tests/docker_monitor_test.py, scalyr_agent/tests/test_memory_leaks.py
This pull request makes a small change to the GC profiler to make sure we only report on uncollectable objects (previously we also reported on collectable ones under some circumstances).
=> Update GC profiler and make sure we only report uncollectable objects

scalyr_agent/agent_main.py, scalyr_agent/tests/agent_main_test.py
This pull request should fix the issue @yanscalyr reported yesterday.
---
I updated the code so under dev installation we skip "cert files exists" checks.
Those bundle certificate files are created as part of the build process inside ``build_package.py`` so they will only be available in package installations.
In addition to that, I updated the code so we also skip "intermediate certs file exist" check on Windows installations since we don't include intermediate certs file there.
=> Make sure we skip "cert files exist" checks when running in a dev installation

.circleci/config.yml
This pull request updates a list of our CodeSpeed benchmarks and adds another "under load" benchmark which runs the agent under Python 2.7.
This benchmark runs longer than the other loaded ones, so it may give us some insight on the memory usage behavior when running agent under continuous load for a longer period of time.
=> Add longer running agent benchmarks

scalyr_agent/profiler.py, scalyr_agent/tests/test_profilers.py
This pull request adds some basic mocking based tests for the ScalyrProfiler abstraction.
Keep in mind that currently those tests are very basic and don't verify actual functionality and output format of the profilers.
At this point they only verify that the calling the methods which are part of the base API (update, start, stop) doesn't result in an exception (they would catch the issue such as the one fixed here #440).
=> Add basic tests for the Profiler abstraction

scalyr_agent/builtin_monitors/tests/docker_monitor_test.py, scalyr_agent/tests/monitors_manager_test.py
This pull request updates the test which occasionally fails on Circle CI to use longer max wait.
This should make test failure due to test timing less likely to occur.
=> Test race workaround

.circleci/config.yml, scripts/circleci_usage_data.py
This pull request updates Circle CI usage data script so it supports multiple workflows.
Now we have two workflows (unittest, benchmarks) and once #401 is merged, we will have on more.
With this change we now track usage data for all 3 workflows.
=> Update Circle CI usage data script to support multiple workflows

scalyr_agent/builtin_monitors/tests/docker_monitor_test.py, scalyr_agent/third_party/tcollector/__init__.py, scalyr_agent/third_party/tcollector/collectors/0/dfstat.py, scalyr_agent/third_party/tcollector/collectors/0/ifstat.py, scalyr_agent/third_party/tcollector/collectors/0/iostat.py, scalyr_agent/third_party/tcollector/collectors/0/netstat.py, scalyr_agent/third_party/tcollector/collectors/0/procstats.py, scalyr_agent/third_party/tcollector/tcollector.py, scalyr_agent/third_party/tcollector/test_collectors/0/random_collector.py, tox.ini
In #445, I noticed we don't run lint checks on tcollectors directory since it's located inside ``third_party/`` directory which contains other dependencies we want to ignore.
In ideal world, we would leave any third party dependencies as is and wouldn't touch it (so we can update it from upstream in the future, etc.), but sadly we don't have much choice here - we already made some functionality and other changes and fixes to tcollectors package (ideally, we should also try to get some of those accepted upstream).
=> Run lint checks on tcollector directory

.circleci/config.yml, benchmarks/configs/agent_single_50mb_access_log_file.json, benchmarks/configs/agent_single_growing_log_file_with_shell_and_url_monitor.json, scripts/circleci_usage_data.py
This pull request makes a small change to the loaded benchmark #2 to also utilize URL and shell monitors with more frequent sample interval.
This way the setup closer resembles our staging setup.
As discussed on slack (/cc @ArthurKamalov), we should also add the same (but longer running) benchmark to Kubernetes. 
This way we will cover both scenarios - short and longer running ones.
=> Utilize shell and URL monitors in the loaded benchmark #2

.circleci/config.yml, scripts/shell-scripts-lint.sh, scripts/submit-codecov-data.sh
Every now and then submitting report to codecov.io times out.
This pull request updates submit Circle CI job stop so we try to retry it up to 5 times in case it fails.
=> Retry codecov report upload in timeout / failure

.circleci/config.yml, smoke_tests/conftest.py, smoke_tests/package_smoke_tests/package_smoke_test.py, smoke_tests/tools/utils.py, tox.ini
This pull request includes some smoke test related improvements which will help us troubleshoot failed builds.
It updates Circle CI jobs so we correctly preserve agent logs on build failures which should help us with troubleshooting a failure.
=> Small smoke test improvements

.circleci/.coveragerc_ci, .coveragerc, build_package.py
This pull request enables branch level coverage tracking and reporting.
This should give a more real picture into code coverage compared to just a simple line based code coverage reporting we currently use.
See more info on branch coverage here - https://coverage.readthedocs.io/en/v4.5.x/branch.html.
Having said that, I'm not actually 100% sure if codecov.io supports branch level coverage tracking for Python projects (will soon see when the build finishes).
=> Enable branch level coverage tracking and reporting

lint-configs/python/mypy.ini, scalyr_agent/builtin_monitors/tests/test_tcollectors.py, scalyr_agent/tests/monitors_manager_test.py, scalyr_agent/third_party/tcollector/tcollector.py
This pull request updates tcollector so it uses the Python binary which is used to run the main process (aka gain in our case).
This way it works correctly when agent runs under Python 3, but ``/usr/bin/env python`` doesn't point to Python 3 binary.
In addition to that, this way it also works correctly under various virtual environment scenarios.
=> Update tcollector code so it uses Python binary which is used to run the main process

smoke_tests/tools/compat/__init__.py, smoke_tests/tools/package/__init__.py, tox.ini
Small change to make sure we also run lint checks on ``smoke_tests/`` directory.
In addition to that, I also added a change so user can specify on which files to run the lint check. This comes handy when you want to run lint check on a subset of files.
For example:
```bash
LINT_FILES_TO_CHECK=smoke_tests/ tox -elint
```
=> Run lint checks on smoke_tests/ directory

CHANGELOG.md, scalyr_agent/configuration.py, scalyr_agent/monitors_manager.py, scalyr_agent/platform_controller.py, scalyr_agent/platform_linux.py, scalyr_agent/platform_windows.py, scalyr_agent/scalyr_logging.py, scalyr_agent/scalyr_monitor.py, scalyr_agent/tests/configuration_test.py, scalyr_agent/tests/linux_system_metrics_test.py, scalyr_agent/tests/monitors_manager_test.py, scalyr_agent/tests/scalyr_logging_test.py
This pull request implements a change which allows user to define a blacklist of metrics name (new ``metric_name_blacklist`` configuration option) which allows user to define which metric names should not be logged and shipped to Scalyr (as per discussion in #402).
There are many ways to tackle this problem and I decided to go with a simple "metric name" blacklist based approach.
I think this should work reasonable well for most common use cases and it also introduces the smaller performance penalty compared to a more complex approach which may utilize globs, other fields, etc.
Another thing worth noting is that this is really the "last resort" approach - ideally those metrics should be filtered out at the source - via monitor configuration or similar. But where there is not possible / …
=> Allow user to specify a blacklist of metric names which shouldn't be logged and shipped to Scalyr

.circleci/.coveragerc_ci, .coveragerc, codecov.yml, scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py, scalyr_agent/monitor_utils/tests/k8s_test.py, scalyr_agent/test_base.py
I noticed codecov started tracking coverage for new top level ``tests/`` directory (introduced in #463 ) for which we currently don't track coverage.
This pull request updates codecov config so we ignore that directory since it otherwise skews the stats and doesn't provide any value until we also enable coverage for those tests.
=> Udpate codecov config to ignore top level tests/ directory

.circleci/config.yml, tests/utils/dockerized.py
I added a new test in #472 and new package tests started to fail on master (they were all passing locally).
It looks like there is an issue where we incorrectly handle Docker image caching so the tests are using old and out of date agent_source/ directory.
This is a short term workaround (don't use cache), but in the future we need to figure out a better approach and solution that since re-building whole image on any change in the agent repo is unacceptable (and wasteful).
=> Workaround for master build failure (don't use built image cache)

build_package.py
This is a fix for an issue that came up when testing Ubuntu 18 and 16 AMI images.  Out of the box, the install-scaly-agent was partially succeeding in installing the Scalyr Agent.  The install would be left in a usable state (the Scalyr Agent could be started, etc) but the system would not have the Scalyr Agent configured as a service and therefore not be set up to launch at system start.
It turns out, there is some weird (and unexplained) issue with having our multiple symlinks and conf file structure.  If the `/etc/init.d/scalyr-agent-2` symlink is marked as a conf file and it points to  the `/usr/share/scalyr-agent-2/bin/scalyr-agent-2` symlink (which is also marked as a conf file), then the symlink in `/etc/init.d` is not present on the filesystem when the post install script is run …
=> Disable default conf files in Debian

.circleci/config.yml, tests/distribution/python_version_change_tests/common.py, tests/smoke_tests/package_test.py
This pull request fixes tests which have started failing after #477 has been merged.
In addition to that, I updated existing ``common_test_python_{2,3}`` test to verify that rc*.d symlinks are correctly created as part of the package postinst step.
Those tests would have caught the issue we've spent so much time tracking down (but obviously not the root cause) so it should serve as a regression test / protection for the future.
I ran them under all the distros (atm we only run tests on Circle CI on CentOS 8 and Ubuntu 18.04) and they pass with the latest master.
Keep in mind that those tests don't really belong into ``python_version_change_tests`` distribution tests, but we can clean this up and move them in a more appropriate place once we start working on more end to end package tests …
=> Fix failing tests, add new rc*.d symlinks tests

scalyr_agent/monitors_manager.py, scalyr_agent/tests/empty_monitor.py, scalyr_agent/tests/util/util_test.py, scalyr_agent/util.py, tox.ini
This pull request fixes ``isAlive()`` implementation under Python 3.
The issue was related to our Python 3 compatibility change (renaming ``_is_stopped`` instance variable on which parent ``isAlive()`` relied on) and ``Thread.is_alive()`` implementation changing under Python 3.
To make it work, I used middle of the ground approach.
Under Python 2, we leave it as it was before and under Python 3 we check ``self._run_state`` and ``self._started`` class instance variable.
This should work under all scenarios, but it still means our ``StoppableThread`` is not 100% compliant with the base Thread API.
Making it compliant will require more changes (RunState should default to ``False`` inside the constructor and only get changed to ``True`` when theread.run/start method is called, etc.), but …
=> Fix a bug with status report incorrectly listing running monitors as dead

setup.py
Due to importing some modules indirectly via six, the Windows
executable is not properly including some required python libraries.
The fix is to manually include them when performing the py2exe
freezing.
=> Fix issue causing Windows executable to be missing Python modules

tests/distribution/python_version_change_tests/ubuntu1404_test.py, tests/distribution/python_version_change_tests/ubuntu1404_with_py3_test.py, tests/distribution/python_version_change_tests/ubuntu1604_test.py, tests/distribution/python_version_change_tests/ubuntu1804_test.py, tests/utils/dockerized.py
This pull request fixes small regression from #485 and makes sure we correctly preserve deb and rpm artifacts from Python version change package tests.
It also fixes some duplicate targets and invalid function names.
=> Make sure we preserve artifacts for package tests

.circleci/config.yml, scripts/circleci/copy-docker-images-to-cache.sh
Small fix for master build failing.
Our Circle CI job added in #490 didn't correctly handle a scenario where a cached image file doesn't exist yet.
This pull request fixes that.
=> Fix master build

scalyr_agent/builtin_monitors/tests/linux_process_metrics_test.py, scalyr_agent/builtin_monitors/tests/linux_system_metrics_test.py, scalyr_agent/tests/agent_main_test.py
This pull request fixes two potential test failures on OS X.
In first case, the problem was that depending on how tests run, the test would load and read ``.pyc`` instead of ``.py`` file.
This issue would only manifest itself when running tests under different Python versions (e.g. .pyc file was generated under one version and tests run under a different version).
And in other case, we simply skip Linux specific tests on OS X.
=> Fix unit test failures on OS X

.circleci/config.yml
This pull request updates Circle CI config so we also run unit tests on OS X using Python 3.5.
We don't officially support running agent on the OS X (although it more or less works out of the box), but some developers use OS X for development so we should also run at least unit tests on OS X to detected issues like the one in #499 early.
=> Run unit tests on Mac OSX

.circleci/config.yml
This fixes inadvertent regression with redundant jobs introduced in #497.
For information why that job is redundant on master merge, please see the code / circle ci config comment.
=> Only run package-build-* jobs on non-master builds

tox.ini
Pylint fails when you run it by itself (such as `tox -e pylint`).
This is because `tests/ami` introduced a requirement on `libcloud`
that was not reflected in the `pylint` target.  The normal
`tox -e lint` did not fail because the appropriate dependencies
were added there.
=> Fix missing dependency causing pylint to fail

.circleci/config.yml, scalyr_agent/tests/util/json_util_test.py, tox.ini
This pull request includes the following changes:
1. Fix ``coverage`` tox target to make sure we run all the unit tests.
2. Update unit-test and coverage tox targets to generate junit XML report files. Those reports files are then used by Circle CI to provider a nicer visualization on test results, including test timing.
3. If there is a Circle CI job failure on master run, we will now get notified on Slack.
4. Pushing to a special ``automated_tests/`` prefixed branch will trigger builds for all the jobs (including the ones which only run on master). This will be used by our automated final sanity test which will be triggered by a Github PR / issue comment.
=> Circle CI and tox.ini updates

.circleci/config.yml
This pull request fixes PYTHONPATH for benchmarks Circle CI job (it was broken accidentally by #489).
In addition to that, it also fixes CodeSpeed executable name (previous one was too long).
=> Fix PYTHONPATH for agent benchmarks Circle CI job

scalyr_agent/agent_main.py, scalyr_agent/tests/util/util_test.py
After #495 has been merged, I started to notice errors like this in the log:
```bash
2020-04-21 14:36:53.500Z ERROR [core] [scalyr_logging.py:603] [error="failedAgentMain"] Main run method for agent failed due to exception :stack_trace:
Traceback (most recent call last):
File "scalyr_agent/agent_main.py", line 992, in __run
config_change_check_interval
File "/home/kami/w/scalyr/scalyr-agent-2/scalyr_agent/util.py", line 708, in sleep_but_awaken_if_stopped
self._wait_on_condition(timeout)
File "/home/kami/w/scalyr/scalyr-agent-2/scalyr_agent/util.py", line 792, in _wait_on_condition
self.__condition.wait(timeout)
File "/home/kami/.pythonz/pythons/CPython-3.6.9/lib/python3.6/threading.py", line 299, in wait
gotit = waiter.acquire(True, timeout)
File …
```
=> Fix callback registration for the RunState on_stop handler

scalyr_agent/agent_main.py, scalyr_agent/configuration.py, scalyr_agent/log_processing.py, scalyr_agent/scalyr_client.py, scalyr_agent/tests/log_processing_test.py, scalyr_agent/tests/scalyr_client_test.py
This PR removes code from the agent that ensures all logs have a monotonically increasing timestamp.
Now, if the agent is in standalone mode, timestamps will be set to the current time when reading bytes from disk, or if the agent is in k8s, docker or any other mode that parses lines as json, then the agent will try to extract a timestamp from the json and use that.
This has been tested manually using a script that generates logs with timestamps offset from the current time, and/or timestamps that go backward and forwards in time.
=> Remove monotonically increasing timestamps from the agent

.circleci/config.yml, .gitignore, benchmarks/scripts/send_microbenchmarks_data_to_codespeed.py, tox.ini
This pull request includes the following fixes / improvements to the micro benchmarks job:
1. Fixes the result submission script so it supports non-UTC timestamp. I noticed there was a build failure (https://circleci.com/gh/scalyr/scalyr-agent-2/34236?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification) and it appears the author_time timestamp string contains a local (non-UTC) time string.
2. Update Circle CI job so we also preserve raw benchmark result JSON files. This will make it easier to troubleshoot issues like the one above in the future.
3. Store benchmark results files in ``benchmark_results/`` directory instead of the in the repo root.
=> Fix submit microbenchmarks result script to support non-UTC timezones

.circleci/config.yml
Small fix for the build - we weren't using the correct cache key for micro benchmarks dependency cache so dependencies weren't reinstall when running the Circle CI job.
=> Use correct cache key for micro benchmarks cache

.circleci/config.yml
This pull request updates Circle CI job config for micro benchmarks jobs to notify us on master failure on Slack (same as for most other jobs).
This way it will be harder to miss failures on master merge.
=> Update Circle CI job config for micro benchmarks to notify us on slack on build failure

scalyr_agent/monitor_utils/k8s.py
`warning` doesn't expect loglevel as first parameter
=> Fix logging

scalyr_agent/builtin_monitors/apache_monitor.py
The `apache_monitor.py` file was left unchanged during codebase migration to python3 compatibility. There were some configuration fields with `str`(`six.text_type` is expected), it caused an error during configuration validation.
=> Add string compatibility for apache monitor.

scalyr_agent/agent_main.py, scalyr_agent/configuration.py, scalyr_agent/tests/configuration_test.py
This commit will cause the agent to print various useful configuration options to
`agent.log` at startup or whenever the configuration changes.
This will be useful in determining the values of the configuration options when
diagnosing customer issues
=> Print useful config settings to agent.log

scalyr_agent/builtin_monitors/kubernetes_events_monitor.py, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py, scalyr_agent/configuration.py, scalyr_agent/monitor_utils/k8s.py, scalyr_agent/monitor_utils/tests/k8s_test.py, scalyr_agent/tests/configuration_k8s_test.py
Adds in a namespace whitelist capability to Kubernetes in addition to blacklist.  This allows customers to only collect logs from pods running from a specific set of namespaces.
Note, I have not finished writing all of the test cases but I wanted you to get an early review of this because I'll need to merge this in later tonight.
=> Add namespace whitelist capability for Kubernetes

scalyr_agent/monitor_utils/k8s.py, scalyr_agent/monitor_utils/tests/k8s_test.py, tox.ini
Tests for monitors utils were not added into tox targets, so it could not calculate coverage for them too.
Also, there is a small fix that does sorting of the namespaces in `K8sNamespaceFilter` before creating a string from it, to provide stable results.
=> Add monitor utils tests to tox targets.

codecov.yml
The `verify-codecov-config.sh` script is failing.  I believe this
is the change that will fix it, but not completely confident.
=> Fix invalid code coverage config

.circleci/config.yml, py26-unit-tests-requirements.txt, tests/unit/builtin_monitors/linux_process_metrics_test.py, tests/unit/linux_process_metrics_test.py
This pull request fixes unit tests and smoke tests build failures when running under Python 2.6.
For the past day or so, Python 2.6 tests have been failing with this error:
```
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
build-essential : Depends: gcc (>= 4:9.2) but it is not going to be installed
Depends: g++ (>= 4:9.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
It looks like a new version of one of the conflicting dependencies has been pushed to an upstream deb repo and that version conflicts with a version which is installed inside the Docker container image we use.
I …
=> Fix unit and smoke tests failure under Python 2.6

scalyr_agent/agent_main.py, scalyr_agent/config_main.py, scalyr_agent/configuration.py, tests/unit/configuration_test.py
Under kubernetes, it is not convenient to specify custom configuration snippets in the agent.d directory without overriding core configuration snippets.
This PR allows users to keep the default configuration snippets we provide, but also provide their own configuration snippets in an additional configuration directory.
This additional configuration directory is specified via an environment variable or a command line parameter.
If present, the agent will process all .json files in this directory and add them to its current configuration.
This only applies to the main agent, and not the agent config scripts.
=> Add additional config path as an option

scripts/circleci/verify-codecov-config.sh
This pull request contains small improvement to the verify circle ci script so it prints curl output (aka response body) on validation failure.
In addition to that, we now only try to retry on a timeout and abort immediately on actual fatal error (such as the config validation failed).
This should make troubleshooting slightly faster and easier.
Before:
```bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1225  100    83  100  1142   2548  35068 --:--:-- --:--:-- --:--:-- 35687
Command exited with non-zero, retrying in 5 seconds...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1225  100    83  100  1142   3077  42344 --:--:-- …
```
=> Update verify codecov config script to print response on failure and abort immediately on fatal error

.circleci/config.yml, dev-requirements.txt, scripts/submit-codecov-data.sh
This pull request fixes codecov coverage data uploads.
Codecov coverage upload started to fail with "400 bad request" error a couple of days ago (https://app.circleci.com/pipelines/github/scalyr/scalyr-agent-2/2930/workflows/05136b23-cf27-41ed-8b69-74bce5c4cdec/jobs/40054/parallel-runs/0/steps/0-108).
It looks like it's an issue with the version of the client we are currently using and a new one should fix it - https://github.com/codecov/codecov-python/pull/268.
One of the reasons why we didn't spot this issue earlier was that we didn't consider "codecov data upload fatal" error as fatal.
I fixed that by adding ``--required`` flag to ``codecov`` binary which will make it return with non-zero if the upload fails. This way we will spot issues like that sooner.
=> Fix codecov coverage data upload

.circleci/config.yml, scripts/circleci/run-ami-tests-in-bg.sh, tests/ami/packages_sanity_tests.py, tests/ami/scripts/test_deb.sh.j2, tests/ami/scripts/test_rpm.sh.j2, tests/smoke_tests/verifier.py
This pull request updates AMI-tests script and Circle CI job so we also run install only tests which utilize latest stable version of the installer script to verify that installation of the latest stable agent package using the installer script works correctly.
---
We already have upgrade tests which also tests the install scenario / path, but it also doesn't hurt to have additional separate tests for the install only path (at least right now when we run those jobs in parallel and costs are very low).
=> Also run install only tests inside the AMI tests job

.circleci/config.yml, scripts/circleci/run-ami-tests-in-bg.sh, tests/ami/README.md, tests/ami/packages_sanity_tests.py
This pull request updates install and upgrade AMI package end to end tests so they also run under Debian 10.
As discussed before, we run tests for various distros in parallel so adding another distro doesn't increase overall build time as long as those distro tests don't take longer than the slowest distro tests (which is Windows at this point - it can take up to 4 minutes whereas most other distros finish in 2 minutes or less).
=> Also run AMI end to end package tests in Debian 10 & Amazon Linux 2

docker/README.md
Add instructions for building the Scalyr Agent Kubernetes Docker image in `docker/README.md`.
=> AGENT-413 Update Docker README for instructions building agent K8S image

.circleci/config.yml, scripts/circleci/run-ami-tests-in-bg.sh
This pull request adds regression test for a scenario where there is Ubuntu system with yum-utils package installed.
Before my fixes to the installer script, the script didn't correctly handle that scenario (it incorrectly detected package manager as being yum instead of apt).
I already ran those tests manually locally before, but it also makes sense to have it hooked up to the CI.
=> Update AMI tests to cover Ubuntu system with yum-utils package scenario

docs/monitors/redis_monitor.md, scalyr_agent/builtin_monitors/redis_monitor.py
This commit enables current redis monitor to log replication information of redis cluster.
Specifically, if the agent is running on a redis cluster master, redis
monitor will log replication offsets of both master and replica, as well
as offset differences and how many seconds the replica is falling behind
=> Log redis cluster replication offsets

.circleci/config.yml, dev-requirements.txt, tox.ini, windows-unit-tests-requirements.txt
This pull request fixes "Run Unit Tests under Python 3.5" step not terminating and timing out in the ``unittest-35-windows`` job.
Troubleshooting it was slow and painful since I needed to push commits and changes one by one to test various things (SSH debugging didn't work).
I assume the issue is related to some upstream change and not our code.
It basically causes Circle CI job which runs tox command to not correctly exit even though the tox command itself correctly exits (I verified that with various commits and changes, the step also hangs even if we just run echo command as part of a tox target and nothing else).
I thought it may be something related to file descriptors not getting correctly closed or similar and this does seem to be the case since using the output redirect workaround …
=> Workaround for Circle CI unittest step timing out in the unittest-35-windows job, upgrade dependencies, re-enable coverage for windows unittest job

.circleci/.coveragerc_ci, .coveragerc, .sonarcloud.properties
This pull request updates ``.coveragerc`` file used by Circle CI jobs to correctly exclude some test directories from coverage reports.
This is needed because paths on Windows and Linux are different and after re-enabling code coverage for Windows unit tests, some directories were now being incorrectly included in the reports.
=> Correctly exclude some tests directories from coverage data on Windows.

RELEASE_NOTES.md
The expected configuration for stdout_severity in k8s is set in our own Dockerfile for it, which customers may not be using. Adding a note about this to the release it was added in.
=> Add a release note about possibly not having expected configuration in custom docker images.

.circleci/config.yml, CHANGELOG.md, RELEASE_NOTES.md, benchmarks/micro/results/compression_algorithms.txt, codecov.yml, scalyr_agent/agent_main.py, scalyr_agent/agent_status.py, scalyr_agent/util.py, tests/distribution/basic_sanity_deb.py, tests/distribution/basic_sanity_rpm.py, tests/unit/agent_status_test.py, tests/unit/copying_manager_test.py, tests/utils/agent_runner.py, tox.ini
This pull request updates default value for ``compression_level`` configuration option to ``6`` from ``9`` when using ``compression_type: deflate``.
Based on our compression level algorithm benchmarks (https://gist.github.com/Kami/75f76b69d68351cd77a24346b1cf8394) 6 offers a best trade off between compression ratio and CPU usage.
9 usually results in a very small increase in the compression ratio, but takes much longer / uses more CPU time (this is especially true for highly loaded scenarios and large requests).
With this change, this value is now also in sync with the article in our knowledge base - https://support.scalyr.com/hc/en-us/articles/360043295814-Optimized-Settings-for-the-Scalyr-Agent.
=> Default compression_level value to 6 (from 9) when using "deflate" compression_type

scalyr_agent/log_processing.py, tests/unit/log_processing_test.py
Turns out if `re` tries to use an optional group that it never matched it will throw an exception instead of just using an empty string like most other implementations, which causes us to not upload a lot of logs if a customer trips over it. This PR makes us handle that case a bit more gracefully, only not uploading the one log that actually had the issue and giving a hopefully helpful error.
=> CT-109: Unmatched group error

scripts/circleci/upload_circleci_artifacts.py, tests/ami/packages_sanity_tests.py
Add token to download artifacts.
Increase timeout for the AMI tests, because they still fail with timeout error sometimes.
=> Use token in artifact downloading

.circleci/config.yml, CHANGELOG.md, tests/ami/packages_sanity_tests.py, tests/ami/requirements.txt, tests/ami/scripts/test_windows.ps1.j2, win32/ScalyrShell.cmd
This pull request fixes a bug (syntax error) in Windows cmdlet script which prevents it from running with the latest version of the agent.
Sadly the issue was never caught by our AMI end to end tests since they don't use cmdlet but start the agent directly using the binary.
This has now been fixed. Having said that, I would still like to merge #608 into master and them merge it into this branch so I can add some additional assertions and improvements (without changes in #608, Windows AMI tests script has a bunch of short comings).
=> Fix a bug in Windows cmdlet script

tests/ami/packages_sanity_tests.py
This pull request contains a small change to the AMI tests script so we fail early if the provided path for the package source doesn't exist or it's not valid.
This way we avoid unnecessary wait in this scenario which would only cause the script to fail after the node has been provisioned and when we try to upload the package file.
=> Update AMI tests script to throw early if invalid path or similar is provided for the package source

scalyr_agent/agent_main.py, tests/ami/packages_sanity_tests.py
This pull request updates agent start up line to also log OpenSSL version against which Python binary which the agent is using to run is linked to.
This change should make it easier for us to troubleshoot some type of issues.
=> Log OpenSSL version against which Python is linked to in the agent start up line

benchmarks/micro/conftest.py, scalyr_agent/pytest_util.py
Small change to ``pytest_util`` module to also define and export ``pytest_benchmark_scale_unit`` function even if the corresponding environment variable is not defined.
This way, the function can more easily be re-used by other projects which rely on ``pytest_util`` module.
=> Also define pytest_benchmark_scale_unit function even if the nvironment variable is not set

dev-requirements.txt, scalyr_agent/builtin_monitors/postgres_monitor.py, scalyr_agent/util.py, scripts/submit-codecov-data.sh, tests/image_builder/monitors/base/Dockerfile, tests/image_builder/monitors/common/pg_init.sql, tests/smoke_tests/monitors_test/mysql_test.py, tests/smoke_tests/monitors_test/nginx_test.py, tests/smoke_tests/monitors_test/postgres_test.py, tests/smoke_tests/monitors_test/shell_monitor_test.py, tests/smoke_tests/monitors_test/syslog_test.py, tests/smoke_tests/monitors_test/url_monitor_test.py, tests/unit/util/json_util_test.py, tests/utils/log_reader.py, tests/utils/tests/test_log_reader.py, tox.ini, windows-unit-tests-requirements.txt
* Fix postgres_monitor error caused by wrong type conversion during the parsing of the config file.
* Fall back to native json library if orjson can not handle unsigned 64bit integers. 
Monitor tests and log analyzing tools were also improved.
=> Postgres and mysql monitors fix

.circleci/config.yml, tests/smoke_tests/standalone_test.py, tests/smoke_tests/verifier.py
The query caching issue has been fixed on the server side so the temporary changes which were made to get the smoke tests passing can now be reverted.
=> Revert temporary smoke tests timeout increases change

CHANGELOG.md, scalyr_agent/builtin_monitors/kubernetes_monitor.py
This pull request includes the following logging changes to the Kubernetes monitor:
1. "Cluster name detected" message is now logged under INFO log level
2. Monitor start up info log line now also containers the value for the following monitor config options: ``log_mode``, ``report_k8s_metrics``
3. On monitor start up we now also print the values of the following environment variables: ``SCALYR_REPORT_CONTAINER_METRICS``, ``SCALYR_REPORT_K8S_METRICS``
Those changes may make it a bit easier and faster for us to troubleshoot some user issues in the future since it may allow us to skip asking the user for their config file in some scenarios.
=> Kubernetes monitor INFO level logging improvements

CHANGELOG.md, docs/monitors/kubernetes_monitor.md, scalyr_agent/builtin_monitors/kubernetes_monitor.py, tests/unit/configuration_k8s_test.py
In autoscaling k8s environments it's not impossible that a pod will start and fail before the k8s monitor is able to start up and catch it, meaning those logs will not be uploaded. This change will make the monitor accept dead pods of a configurable age to have their logs uploaded on the first iteration of the container checking loop, aka when it starts up.
=> CT-207: Configurable time range to accept old and dead k8s containers on monitor startup

CHANGELOG.md, scalyr_agent/builtin_monitors/windows_system_metrics.py, tests/unit/builtin_monitors/linux_system_metrics_test.py, tests/unit/builtin_monitors/test_windows_system_metrics.py
This small PR adds another check for an error caused by disabled "diskperf". This error may happen on older versions of windows and the existing exception catch does not work.
=> New diskperf error check

.circleci/config.yml, CHANGELOG.md, scalyr_agent/agent_main.py, scalyr_agent/util.py, tests/ami/scripts/test_deb.sh.j2, tests/ami/scripts/test_rpm.sh.j2, tests/ami/scripts/test_windows.ps1.j2, tests/smoke_tests/verifier.py, tests/unit/test_util_test.py, tests/unit/util/json_util_test.py
This pull request updates the agent start up code to log a warning if non ``UTF-8`` coding / locale is detected.
I was troubleshooting a customer issue and noticed multiple issues which could arise when locale / coding under which the agent is running is not set to UTF-8 and user is trying to monitor files with non-ascii characters in the file names / content.
Ultimately, if we encounter this scenario this represents a misconfiguration on the user side so there is not much we can do beyond warning the user and advising them to change the locale to UTF-8 (I mean in theory we could try setting locale using ``locale.setlocale``, but I'm worried this may open a can of worms and is something we should avoid - just the other day I was reading this "rant" wrt to locale mess on POSIX systems - …
=> Warn user on non-UTF-8 coding / locale and other locale related improvements

CHANGELOG.md
During the merge conflict resolution, some changelog entries were accidentally removed.
This PR fixes that and adds them back.
=> Add missing changelog entries for v2.1.14

CHANGELOG.md, scalyr_agent/builtin_monitors/linux_process_metrics.py, scalyr_agent/compat.py, scalyr_agent/line_matcher.py, scalyr_agent/log_processing.py, scalyr_agent/platform_posix.py, scalyr_agent/test_util.py, scalyr_agent/util.py, tests/unit/builtin_monitors/docker_monitor_test.py, tests/unit/log_processing_test.py
This pull request fixes ``LineGrouper`` class and makes sure we ignore any decoding errors we get when we try to decode bytes to utf-8 string.
Previously, this code would throw on partial / bad / corrupted unicode sequences.
A user reported an issue with agent throwing ``UnicodeDecodeError`` inside the line matcher code.
After digging in, I saw our code doesn't correctly handle and ignore bad unicode sequences, but it fails on decode.
Keep in mind that this issue would only affect users which had line grouping rules defined.
There are some more places in our code base where we rely on a default "strict" behavior of ``bytes.decode()``.
To be on the safe side, I think we should update all of those places to gracefully handle unicode decoded errors.
=> Fix invalid handling of bad / partial unicode sequences in the LineGrouper

scalyr_agent/configuration.py, scalyr_agent/scalyr_monitor.py, tests/unit/scalyr_monitor_test.py
This pull request fixes a bug in functionality added in #660.
The code was incorrectly inside the whole loop while it should have been outside it :facepalm:
I also added some initial basic mock based regression unit tests which would have caught this issue. Full blown end to end tests would take more work.
=> Fix bug in the sleep before initial sample gather code

CHANGELOG.md, docs/monitors/kubernetes_monitor.md, scalyr_agent/builtin_monitors/kubernetes_monitor.py
We seem to detect docker vs containerd correctly, so the only thing that needed to change to get this working was to move the docker API socket check to after we are sure we are running in docker. Also this PR changes the default CRI behavior to check the filesystem, as this works better in AKS and is likely to work better in a lot of environments.
One concern left: Incorrect docker sockets would crash the agent causing pod restart with a nice message before, but after this change the pod stays running but not working. the `terminate_agent` method other exception catching uses in the same code seems to not actually terminate the agent and cause a pod restart as anticipated. This probably needs to be fixed.
=> CT-264: Support both Docker and containerd without configuration

.circleci/config.yml, .circleci/docker_unified_smoke_unit/smoketest/smoketest.py, CHANGELOG.md, docs/monitors/docker_monitor.md, scalyr_agent/builtin_monitors/docker_monitor.py, scalyr_agent/builtin_monitors/windows_event_log_monitor.py, scripts/circleci/run-ami-tests-in-bg.sh
A while back in #647, I fixed "docker_raw_logs: false" functionality of Docker monitor which has been broken for a while now.
Looking at the commit history, it appears that bug has been inadvertently introduced in cb4f9030455875a8b4619b794736a55a988436b7.
When fixing that functionality for #647, I originally thought we intentionally only retrieve stdout so I didn't add tests for stderr code path, but do think we want to ingest stderr as well since we do that when running in docker_raw_logs mode.
As part of this PR, I also added tess which verify that both container stdout and stderr are ingested and also verified it myself.
=> Make sure Docker monitor also ingests container stderr logs when running in non-raw log file mode

.circleci/config.yml
This fixes the issue with event log Windows AMI tests failure which started happening 2 days ago.
It looks like my suspicion was correct and the root cause was indeed change / update in the Circle CI Windows executor image.
I still don't know exactly what changed (which lib, perhaps vs studio version or similar), but it's better than nothing.
I hope I also get access to actual version string to which ``previous`` version currently refers to to avoid surprises and breakages in the near future.
Some context at https://twitter.com/CircleCI/status/1337438659344293891.
=> Workaround for Windows event log AMI test failure

scalyr_agent/copying_manager/worker.py, scalyr_agent/util.py
I've tested #667 and everything seems to be working correctly :+1: 
I just added two additional log statements so we also log a message when sending SIGTERM and SIGKILL to the child worker process.
Keep in mind that those represent edge case which is triggered when parent is kill -9'ed so using info log level is fine.
=> Log a message when sending SIGTERM and SIGKILL to the child worker process

.circleci/config.yml, tests/ami/packages_sanity_tests.py, tests/ami/scripts/partial/verify_deb_files_ownership.sh.j2, tests/ami/scripts/partial/verify_rpm_files_ownership.sh.j2, tests/ami/scripts/test_deb.sh.j2, tests/ami/scripts/test_rpm.sh.j2
This pull request includes two changes:
1. Change resource class for micro benchmarks to large to make that job less flaky and finish faster. Those jobs only run on merge to master so it shouldn't have large impact on credits usage. If it does, we can revert it.
2. Add additional safety check to AMI tests which verifies file ownership inside the deb package is correct. This check will allow us to catch builder VM and other invalid package file ownership permissions early on.
=> Add additional file ownership checks to deb AMI tests

.circleci/config.yml, build_package.py, tests/ami/scripts/partial/verify_deb_files_ownership.sh.j2
This pull request adds a workaround which makes sure file permissions and ownership is correct when building deb packages on builder VM with ``--deb-use-file-permissions`` flag.
It relies on making sure package content which is packaged up is owner by root user (0:0 uid:gid) and running fpm using sudo.
We only apply this workaround when building packages on builder VM and only for deb packages.
=> Add workaround when building debian packages on builder VM

py26-unit-tests-requirements.txt, scalyr_agent/configuration.py, scalyr_agent/scalyr_client.py, tests/unit/configuration_test.py, tests/unit/scalyr_client_test.py
This pull request updates ``User-Agent`` string sent by the agent so it also includes a value which indicates if sharded copy manager functionality is used and total number of workers and unique API keys configured.
Possible values for this header fragment are documented here - https://github.com/scalyr/scalyr-agent-2/compare/user_agent_mpw?expand=1#diff-4cb9befeecb4697d270768d8487b47aa20810c540fa7a9b6c86800735e7927a2R951.
This will provide us with a better insight on usage of this functionality.
=> Include information on configured number of workers and unique API keys in the User-Agent header

docker/Dockerfile.docker_monitor_testing_config, scalyr_agent/builtin_monitors/docker_monitor.py
This pull request updates Docker monitor to log some container + logger related information for newly started containers.
I had some problems with using labels as configs and having some log statements like that would make troubleshooting easier.
It's worth noting that this code only runs when a new container is found so it shouldn't add tons of overhead. I'm debating if I should use info log level with rate limit key being a container name (or perhaps log path / similar) or using debug level 1.
We probably can't just use straight up INFO without any rate limit since it would cause havoc in scenarios where a lot of short lived containers are started.
=> Update docker monitor to log labels + container info when starting a logger for a new container

CHANGELOG.md, docs/monitors/syslog_monitor.md, scalyr_agent/builtin_monitors/syslog_monitor.py, scripts/print_monitor_doc.py, tests/unit/syslog_monitor_test.py
This pull requests adds support for two new experimental syslog request parsers for syslog TCP monitor.
Both of those parsers should offer much better throughput than the current default parser which supports framed and line delimited syslog messages.
We've done some benchmarking in the past and currently syslog monitor in TCP mode can only handle ~3 MB/s of data before it saturates all the CPU available to the syslog monitor thread.
I wanted to find the root cause for this poor performance so I've done some more profiling.
Based on the profiling results, the main bottleneck is calling ``handle_frame()`` function for each processed syslog message (frame / line).
Basically what that function does is calls scalyr logger method which writes data to a file on disk.
To be able to work around …
=> Improve throughput of TCP syslog monitor with the new experimental config options

CHANGELOG.md, scalyr_agent/builtin_monitors/docker_monitor.py
This pull request updates Docker monitor to not-log some non fatal errors under warning log level.
When using Docker container monitor and consuming logs from the Docker streaming HTTP API, you will often see errors like this in the agent log when restarting / upgrading the agent:
```bash
File "/usr/share/scalyr-agent-2/py/scalyr_agent/third_party/requests/packages/urllib3/response.py", line 333, in _error_catcher
self._original_response.close()
File "/usr/lib/python3.8/http/client.py", line 416, in close
super().close() # set "closed" flag
File "/usr/lib/python3.8/http/client.py", line 429, in flush
self.fp.flush()
ValueError: I/O operation on closed file.
2020-12-27 19:55:09.098Z INFO [core] [connection.py:218] HttpConnection uses native os ssl
2020-12-27 19:55:09.099Z INFO [core] …
```
=> Don't log non-fatal errors in the Docker monitor under warning log level

CHANGELOG.md, scalyr_agent/configuration.py, scalyr_agent/scalyr_client.py, scalyr_agent/util.py, tests/unit/configuration_test.py, tests/unit/scalyr_client_test.py, tests/unit/util/util_test.py
This pull request adds support for fully disabling compression for outgoing requests by setting ``compression_type: none`` config option.
As profiled many times in the past already, currently one of the main bottlenecks in the agent when dealing with high volume / throughput scenarios is the compression operation itself.
As benchmarked yesterday, disabling compression can increase to large increase in overall throughput (e.g. yesterday with 4 workers and medium line size we've seen around ~50 MB/s with deflate level 6 aka default and ~80 MB/s with compression disabled).
As they say - there is no such thing as free lunch and the same thing applies here as well. Disabling compression will in most cases result in larger egress traffic on the servers where the agent is running and this may …
=> Add support for disabling compression for outgoing requests

CHANGELOG.md, scalyr_agent/builtin_monitors/linux_system_metrics.py
This pull request updates Linux system metrics monitor to ignore two additional mount point globs by default - ``/var/lib/docker/*`` and ``/snap/*``.
First one represents Docker overlay volume mounts which size and other values will always match the values of the mount point where ``/var/lib/docker`` lives on and the second one represents read-only mount points for snap packages.
Metrics for those mount points provide no additional insight to the end user and just result in unnecessary network traffic and storage usage (albeit very small one).
Keep in mind that this change will only affect deployments where the agent is running on the host where docker containers run and deployments which utilize snap packages.
=> Update Linux System metrics monitor to also ignore /var/lib/docker/* and /snap/* mount points by default

scalyr_agent/scalyr_monitor.py
This pull request fixes ``run_monitor.py`` script so it doesn't throw an exception when ``-c`` argument is used.
#660 inadvertently broke that script when ``-c`` flag is used aka when config is provided as JSON string on the command line.
=> Fix run_monitor.py so it works when -c flag is provided

scalyr_agent/agent_main.py, scalyr_agent/agent_status.py, scalyr_agent/builtin_monitors/linux_process_metrics.py, scalyr_agent/configuration.py, scalyr_agent/copying_manager/copying_manager.py, scalyr_agent/copying_manager/worker.py, scalyr_agent/platform_linux.py, scalyr_agent/scalyr_client.py, tests/unit/linux_process_metrics_test.py
This PR adds periodical stats logging for all workers in separate process'. 
The agent's `linux process monitor` also aggregates all metrics from the child worker process'. 
**Things to do/discuss:**
Create a separate app for the `linux process monitor` for each worker process to be able to monitor them separately.
In this case, we need to create a new instance if the `LinuxProcessMonitor` for each worker.
=> Add worker log status

.circleci/config.yml, CHANGELOG.md, build_package.py, scalyr_agent/agent_main.py, scalyr_agent/copying_manager/worker.py
This PR fixes the changelog build warnings for the debian. It seems like those warnings were there for  a long time (the `dpkg-parsechangelog` throws them since agent version 2.0.1)
First issue: The first level entries(e.g. Features, Improvements) begin with only one space character. Because of that, those entries are not shown.
Second issue:  the release author entry also does not have extra space.
The changelog before the PR:
```
Source: scalyr-agent-2
Version: 2.1.16
Distribution: stable
Urgency: low
Changes:
scalyr-agent-2 (2.1.16) stable; urgency=low
.
- Add copy truncate log rotation support. This is enabled by default.  It does not support copy truncate with compression unless the `delaycompress` option is used.  This feature can be disabled by setting …
```
=> Fix debian change log build and small fixes

.circleci/config.yml, CHANGELOG.md, scalyr_agent/builtin_monitors/syslog_monitor.py, scripts/circleci/validate-deb-changelog.sh, scripts/circleci/validate-rpm-changelog.sh, tests/unit/syslog_monitor_test.py
This pull request adds small change on top of #692 so we also validate syntax / conformance of changelog file / content which is embedded into the builtrpm package.
RPM seems to be much less strict with changelog formatting than deb, but it also doesn't hurt to have this validation.
In addition to that change, I also moved validation logic into a standalone script file.
=> Also validate changelog syntax / formatting in the RPM package

.circleci/config.yml
It looks like one of the Ruby dependencies fpm depens on has been updated and doesn't work with Ruby 2.1 which ships on Debian 8 anymore.
As a fix / workaround, I updated Docker image we use to Debian Buster (10) which ships with Ruby 2.5.
New version of Debian also ships with a more recent version of gnupg which has some backward incompatible changes which means I also needed to update some gpg commands we use.
TBH, we should have done that sooner or later anyway since Ruby 2.1 has been EOL for a while now. Same story for gpg (better to use more recent version due to security fixes).
I also pinned fpm, but not all fpm dependencies are pinned to a specific version so it things could break again in the future if some transitive dependency is updated...
=> Fix "create deb and rpm packages for installer" Circle CI build job

CHANGELOG.md, scalyr_agent/scalyr_logging.py, tests/unit/scalyr_logging_test.py
This pull request updates ``emit_value()`` method so any extra field values are always sorted alphabetically by the field name when being appended to the metric log line.
This ensures consistent and stable ordering for those monitor metrics log lines.
Before:
```bash
2021-01-20 21:53:03.737Z [foo(1)] test_name 5 g=9 a=7 c=5 b=8 
```
(This line is really just given for demonstration, actual order is not guaranteed and could be different for each monitor gather sample run).
After:
```bash
2021-01-20 21:53:03.737Z [foo(1)] test_name 5 a=7 b=8 c=5 g=9
```
I was verifying / testing agent-metrics parser fixes on the server side. It turns out that issue appeared less frequent on our accounts compared to my personal account.
The reason for that is that I'm using Python 3 where dict ordering is …
=> Sort extra field names in log lines for monitor metrics log lines with extra fields

.github/workflows/codeql-analysis.yml
This pull request adds a CI check which runs CodeQL static security analysis on the code once a day.
It utilizes Github workflow since it's a bit PITA to hook it up all the way using Circle CI.
=> Add CodeQL static analysis CI check

.circleci/config.yml, .github/workflows/codeql-analysis.yml, CHANGELOG.md, dev-requirements.txt, docker/requirements.txt, scalyr_agent/agent_main.py, scalyr_agent/compat.py, scalyr_agent/configuration.py, scalyr_agent/connection.py, scalyr_agent/platform_windows.py, setup.cfg, tests/image_builder/monitors/base/Dockerfile, tests/unit/builtin_monitors/docker_monitor_test.py, tests/unit/configuration_test.py, tests/unit/connection_test.py, tests/unit/test_platform_windows.py, tests/unit/util/json_util_test.py, tox.ini, windows-unit-tests-requirements.txt
This pull request fixes a bug which would result in an exception being thrown if user tried to start agent on Windows with a non-admin user.
An exception would be thrown during permissions escalation phase due to the code not handling that scenario correctly.
While troubleshooting this issue, I also encountered various other scenarios related to incorrect permissions which result in non-user friendly exceptions being thrown.
I tried to update all of those places to throw more explicit and user-friendly error messages.
I already mentioned this in YT issue - our current AMI based Windows end to end tests run in shell / non-gui mode which means there is no easy way to write automated test which would have caught the permission escalation issue since that code path depends on GUI.
Technically …
=> Various Windows fixes and improvements

tests/image_builder/distributions/amazonlinux2/Dockerfile.base, tests/image_builder/distributions/centos6/Dockerfile.base, tests/image_builder/distributions/centos7/Dockerfile.base, tests/image_builder/distributions/centos8/Dockerfile.base, tests/image_builder/distributions/ubuntu1604/Dockerfile.base, tests/image_builder/distributions/ubuntu1804/Dockerfile.base
Fix for CI tests failure.
Old versions of pip don't support more recent manylinux2014 wheel format so the tests fail when trying to compile ``orjson`` dependency instead of using the pre-built wheel.
=> Test a fix for tests failure

.circleci/config.yml, .sonarcloud.properties, CHANGELOG.md, scalyr_agent/configuration.py, scalyr_agent/util.py, tests/unit/configuration_test.py
This pull request updates config parsing code to warn user if ``k8s_logs`` config option is configured, but Kubernetes monitor is not enabled / configured.
This "issue" was originally reported by Wei Liu. I believe he configured ``k8s_logs`` config option, but not the Kubernetes monitor itself so the ``k8s_logs`` config option had no affect.
I do think this config option is somewhat confusing - it's a top level config option, but (afaik, please correct me if I'm wrong), it's used by Kubernetes monitor so it has no affect without that monitor being configured. I assume we made it a top-level option for "simplicity" reasons, but dunno.
In other cases we don't have such issues since monitor-specific config options go under that monitor config entry.
I also asked @weilliu to confirm this and …
=> Warn if "k8s_logs" config option is configured, but Kubernetes monitor is not configured / enabled

CHANGELOG.md, scalyr_agent/configuration.py, scalyr_agent/copying_manager/copying_manager.py, scalyr_agent/copying_manager/worker.py, tests/unit/configuration_test.py, tests/unit/copying_manager_tests/common.py, tests/unit/copying_manager_tests/copying_manager_new_test.py, tests/unit/copying_manager_tests/test_environment.py
This PR fixes worker session checkpoints consolidation bug, where the copying manager also was deleting the monitor checkpoint files.
The worker session checkpoint files now have the format - `checkpoints-worker-<worker_id>`. 
THe consolidation logic is also changed to use the glob that only matches the checkpoint files from the worker sessions.
=> rename worker checkpoint files.

.circleci/config.yml, tests/ami/scripts/test_deb.sh.j2, tests/ami/scripts/test_rpm.sh.j2
This pull request updates ``ami-tests-stable`` job to ensure that the URL in the installer script indeed points to the correct stable repo.
In the past we had a bug when it could incorrectly point to internal instead of stable repo.
=> Add additional safety checks to the ami-tests-stable job

CHANGELOG.md, docs/monitors/kubernetes_events_monitor.md, scalyr_agent/builtin_monitors/kubernetes_events_monitor.py
A customer reported that `Endpoint` event `involvedObject` `kind` was not sent by default.  Add `Endpoint` kind to event_object_filter default.
=> CT-298 Add Endpoint kind to event_object_filter default

CHANGELOG.md, scalyr_agent/agent_status.py, scalyr_agent/configuration.py, tests/unit/agent_status_test.py
This pull request includes two changes.
This should make building various 3rd party monitoring / similar scripts on top of agent status output easier (technically pid file for main process is available via other means, but it's located in /var/log/scalyr-agent-2/agent.pid which is really not a standard location for pid files, pid files should really live in /var/run or similar).
Before:
```bash
Scalyr Agent status.  See https://www.scalyr.com/help/scalyr-agent-2 for help
Current time:            Fri Sep  5 23:14:13 2014 UTC
Agent started at:        Thu Sep  4 23:14:13 2014 UTC
Version:                 2.0.0.beta.7
VCS revision:            git revision
Python version:          3.6.8
....
````
After:
```bash
Scalyr Agent status.  See https://www.scalyr.com/help/scalyr-agent-2 for help …
```
=> Update agent status output to include pids, fix / remove warnings logged in status output

.circleci/config.yml, CHANGELOG.md, examples/systemd/scalyr-agent-2.service, installer/scripts/postinstall.sh, scalyr_agent/config_main.py, tests/ami/packages_sanity_tests.py, tests/ami/scripts/partial/ssl_checks.sh.j2, tests/ami/scripts/test_deb.sh.j2, tests/ami/scripts/test_rpm.sh.j2
This pull request adds a sample systemd service config file for the agent with information on how to install / use it.
The "setup process" does include some additional steps which need to be taken care of after agent install and upgrade (aka rc.d symlinks need to be manually removed on install / upgrade because they are created automatically in ``postinst`` script).
We do plan to work on distribution specific packages in the future, but that will take a while and this example config is to service as a stop gap in the mean time.
I tested various situations, including multiple worker processes and verified it works correctly.
As mentioned above, we do plan to ship packages which will utilize distro specific service managers such as systemd in the future, but this will take a while.
To …
=> Add sample systemd service config file for the agent

.circleci/docker_unified_smoke_unit/smoketest/smoketest.py, scalyr_agent/builtin_monitors/kubernetes_monitor.py, tests/unit/builtin_monitors/kubernetes_monitor_test.py
This PR adds support for capturing k8s container names in log event metadata. I implemented Imron's suggestion of providing a generic way to add any k8s data we have. In order to add k8s container names to log event metadata the following config is required:
"k8s_logs": [
{
"attributes": { "container_name": "${k8s_container_name}" }
}
]
=> CT-77 capture k8s container names

dev-requirements.txt, docker/requirements.txt, win32/windows-build-requirements.txt, windows-unit-tests-requirements.txt
This pull request updates orjson to latest stable version (https://github.com/ijl/orjson/blob/master/CHANGELOG.md).
That version includes pre-built wheels for more platforms so hopefully this will make it easier to run various tox targets locally which depend on Python libraries with C extensions (since we will be able to use wheels in more situations instead of needing to compile extensions locally).
=> Upgrade orjson to latest stable version

CHANGELOG.md, benchmarks/micro/test_calculate_hash_digest.py, scalyr_agent/monitor_utils/k8s.py, tests/unit/builtin_monitors/kubernetes_monitor_test.py
This pull request addresses issue described here - https://github.com/scalyr/scalyr-agent-2/pull/725#discussion_r596725698.
That PodInfo digest code relied on dictionary item ordering which is not guaranteed to be deterministic and stable in Python. 
This mean that in some situations when different dictionary ordering for the same values is used, code would incorrectly assume that the pod information has changed which would have caused unnecessary log config and log watcher churn (but it shouldn't have any other negative implications besides that potential overhead).
=> Ensure digest on PodInfo is stable and deterministic

CHANGELOG.md, scalyr_agent/builtin_monitors/kubernetes_events_monitor.py
This error occurs if the Kubernetes events API returns an event for a pod that is already gone, common if the agent is restarted, this does not affect us in any meaningful way and goes away on its own but makes a big red error for the user. This PR will make that error only get logged as a debug log to not spook anybody.
=> CT-384: Downgrade missing pod exception to a debug log

CHANGELOG.md, scalyr_agent/builtin_monitors/kubernetes_monitor.py
This PR does two things:
1. Changes the return value of get_containers in the CRIEnumerator on error to `None`, which matches the Docker enumerator and is something we expect for error handling.
2. Enables `force_add` in the k8s monitor when adding new tracked logs. This is needed in case we lose and find logs in rapid succession which may happen with when get_containers fails. (With change #1 I guess it actually won't happen, it would be an extra layer of protection in case there are other routes to reach this scenario.)
=> CT-394, CT-395: Fix repeating and missing logs when get_containers is unstable

CHANGELOG.md, scalyr_agent/util.py
As discussed, we don't want to emit an EOL warning when running agent under Python 2.7 just yet.
=> Don't emit EOL warning under Python 2.7 yet

docker/scripts/container_builder_base.sh
- Uses docker buildx 
- Publish to both linux/arm64 and linux/amd64 
- Noticed about a 60-70 second build increase time when a buildx builder e.g. (`docker buildx create`), but if the Jenkins agent has a multi-architecture builder installed and reused this build time goes down to 20-30 seconds, so that increase in build time should only happen the first time an Jenkins agent runs this build
=> Adding Docker buildx to support arm64 docker builds

k8s/default-namespace/scalyr-agent-2.yaml, k8s/no-kustomize/scalyr-agent-2.yaml, k8s/scalyr-agent-2.yaml
As a workaround to CT-418 and a general fix to the k8s liveness probe setup we need to specify a probe timeout of greater than 5 seconds or so, going with 10 seconds to be safe.
This issue is partially due to what is mentioned in the note here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
Before k8s 1.20 the timeout configuration wasn't respected and basically didn't exist, after the fix it now defaults to 1 second which is lower than `status -H`'s wait time of 5 seconds.
When you combine that with this issue: https://github.com/kubernetes/kubernetes/issues/92464
The liveness probe will not restart the pod if the probe timeout runs out, because of this stuck pods were never restarted as we never managed to reach the …
=> Update k8s livenessprobe timeout to 10s

.circleci/config.yml
Pyenv had an update that stopped adding packages to the PATH by default on OSX. A change to the cli options fixes this.
=> Fix issue with osx unit test

.circleci/config.yml, tests/ami/packages_sanity_tests.py
This PR updates AMI tests script to use new security group ID and re-enabled them.
=> Re-enable AMI tests

CHANGELOG.md, scalyr_agent/copying_manager/worker.py, scalyr_agent/log_processing.py, tests/unit/copying_manager_tests/copying_manager_test.py, tests/unit/copying_manager_tests/copying_manager_worker_test.py
This PR fixes a very nasty bug that was introduced with sharded copying manager. 
The copying manager does not put the 'time' field (it was also added with the copying manager) to the checkpoint object for the files which are immediately removed (by some monitor, as fact). Because of the missing 'time' field, another step - merging checkpoints from all workers, also works wrong and loses such checkpoints. This makes the copying manager reuse the older checkpoint when the log file was removed and added back, and old log lines may be re-uploaded.
The copying manager support tho ways to remove a file from being copied:
1.  To schedule it for removal and so it waits for EOF. 
2.  Remove immediately. 
The first case worked as it should but the second produced checkpoints without a 'time' …
=> Fix missing timestamp in file processors checkpoint.

docker/scripts/container_builder_base.sh
There was a bug in the existing checker (checked if a variable was
non-zero length instead of zero length).  I fixed that but also
made the check a little more robust.
=> Implement more robust check if buildx is supported by docker

.github/workflows/packages-build.yml, agent_build/Dockerfile, agent_build/build_package.py, agent_build/common.py, agent_build/linux/k8s_and_docker/container_requirements.txt, agent_build/linux/prepare_build_environment.sh, agent_build/monitors_requirements.txt, agent_build/requirements.txt, docker/Dockerfile, docker/Dockerfile.k8s, docker/scripts/container_builder_base.sh, scalyr_agent/__scalyr__.py, tests/package_tests/common.py, tests/package_tests/docker_test.py, tests/package_tests/k8s_test.py, tests/package_tests/package_test.py, tests/package_tests/package_test_runner.py
This pull request adds a new build process for the Kubernetes and Docker images of the Scalyr Agent.
**Important notion:** Kubernetes and docker images still rely on the source code. Due to the nature of the docker images, we can bundle all dependencies during the image build so we don't have to use frozen binaries. This, in turn, should help to support multi-architecture docker builds easier, without building architecture-specific frozen binaries.
=> Frozen binaries/k8s and docker builder

.circleci/config.yml, benchmarks/configs/agent_single_50mb_genlog_500k_line_file.json
This PR adds and hooks up new benchmark to CodeSpeed.
This benchmark measures agent resource utilization for an existing which ingests existing 50 MB log file with 500k log lines (generated with scalyr-genlog) log file on disk.
=> New process level agent benchmark with 500k log line size

CHANGELOG.md, scalyr_agent/builtin_monitors/kubernetes_monitor.py
This pull request updates Kubernetes monitor to print a message which warns used that some metrics won't be reported / available when container level metrics reporting is enabled and containerd runtime is detected.
This message is logged under INFO and not WARN log level since it's an informational message and there isn't anything we or user can do at the moment since this data is not available through Kubelet metrics API when using containerd runtime.
=> Update Kubernetes monitor to log INFO message when containerd runtime environment is detected

scalyr_agent/builtin_monitors/graphite_monitor.py, tests/unit/builtin_monitors/graphite_monitor_test.py
This pull request fixes a bug in Graphite monitor where we didn't correctly convert incoming request data (metric name) from bytes to unicode type which is expected by the ``emit_value()`` method.
In addition to that, I added some test cases since we had none. There is a simple test case where we just exercise the parsing code path and there is a bit more involved one which starts actual TCP servers so we also exercise the TCP server request processing code.
Tests are still not exhaustive and don't cover all the possible scenarios and edge cases, but it's a start.
=> Fix graphite monitor

.circleci/config.yml, dev-requirements.txt
Looks like at least one transitive dependency (``more-itertools``) got updated and doesn't support Pythoin 3.5 anymore.
This PR attempts to fix the build by pinning the dependency.
We also need to work on dropping support and related code for Python < 3.7 since it's getting increasingly harder and requires more and more workarounds to get everything to pass.
=> Fix build failure

CHANGELOG.md, docker/requirements.txt
This pull request updates Docker requirements file so we also include ``pympler`` dependency which is used for memory profiling.
Profiling functionality is opt-in via scalyr agent config option. We already include dependency which is used for CPU profiler in the Docker Image, but we don't include one which is used for memory profiling.
Including it makes it easier to troubleshoot (profile) for the end user since they can just turn on the corresponding config option and there is no need to re-build and modify Docker images to get that dependency installed.
=> Include pympler dependency for memory profiling as part of the Docker Image

docs/monitors/mysql_monitor.md, scalyr_agent/builtin_monitors/mysql_monitor.py
This pull request updates MySQL monitor docs and clarifies which permissions are needed for the user which is used for monitoring purposes.
Sadly there are some differences between MySQL versions and implementations so we can't offer a single solution which would work in all the scenarios and grant correct permission for ``SHOW SLAVE STATUS`` command.
=> Update MySQL monitor docs, clarify which permissions are needed

.github/workflows/agent-build.yml, .github/workflows/docker-and-k8s.yml, CHANGELOG.md, agent_build/package_builders.py, agent_build/tools/constants.py, build_package_new.py, docker/requirements.txt
This pull request adds support for ``linux/arm`` architecture.
This architecture includes ``linux/armv7`` which is an architecture used by Raspberry Pi and some other lower powered embedded ARM and IoT devices.
Older versions of Raspberry Pi used ``armv6``, but not many places support this architecture anymore so I didn't add support for it.
Overall, this PR includes the following changes:
- Support for building and pushing ``linux/armv7`` images
- Add new ``--reuse-local-cache`` argument to the build script. This comes handy when building the image locally (outside CI) to speed up the builds.
- Fix tag name when using custom registry. Previous code wouldn't not work correctly when using custom registry when the user / org name is not ``scalyr``. Constructed URL would end up being …
=> Docker imate support for linux/armv7 platform

agent_build/package_builders.py
Small fix that also sets permissions for all files inside `agent.d` folder.
=> Set permission inside agent.d folder.

.github/workflows/agent-build.yml, .github/workflows/docker-and-k8s.yml, tests/package_tests/internals/common.py, tests/package_tests/internals/k8s_test.py
Change to use self hosted runners for new Docker image build jobs.
=> Use self hosted runners for Docker build jobs

scalyr_agent/builtin_monitors/kubernetes_openmetrics_monitor.py, tests/unit/builtin_monitors/kubernetes_openmetrics_monitor_test.py
This config option allows us to enable debug level using new ``debug_level_logger_names`` global config option for all the monitor instances without needing to know the node name up front.
=> Add "logger_include_node_name" config option to K8s Open Metrics Monitor

CHANGELOG.md, scalyr_agent/builtin_monitors/url_monitor.py, tests/unit/builtin_monitors/url_monitor_test.py, tests/unit/url_monitor_test.py
This pull request fixes URL monitor so it works correctly under Python 3 when the POST method is used and the request data is specified.
Previously under Python 3, user would see errors like this when specifying POST data:
```bash
'failed', extra_fields={'url': 'http://127.0.0.1:11505/200_post', 'status': 0, 'length': 0, 'unknown_error': 'POST data should be '}
```
In addition to that, I also included two other improvements:
* If the error message is truncated, indicate that with ``...`` and include 30 characters instead of 20 by default. Previously we didn't indicate that a message has been truncated which would result in "weird" errors such as``'POST data should be '``.
* On unknown errors, also log the whole traceback. This should help with troubleshooting (and unknown errors would …
=> Fix URL monitor handling of request data for POST requests under Python 3

CHANGELOG.md, scalyr_agent/configuration.py
This pull request updates the code so we ingest memory profiling dump / data by default when profiling is enabled (``enable_profiling`` configuration option).
We already do that by default for CPU profiling data, but we haven't do it for memory profiling data. This way the behavior should be consistent and it should also help with the end user experience.
NOTE: I also changed the parser name we attach to the profiler data - I checked the (server side code) and it doesn't seem we define any parser for this name on the server side, but in case I missed something, please let me know.
On a somewhat related note - in the future it may make sense for us to define server side parser / line join rule for those two parsers to provide a better user experience.
=> Ingest memory profiling data by default when profiling is enabled

scalyr_agent/configuration.py, tests/unit/agent_main_test.py
This pull request fixes a small regression and makes sure we don't log any messages when ``status -v`` and other commands are used - we only want to log that message when using a regular entry point and starting the agent.
=> Fix small config parse log regression

CHANGELOG.md, agent_build/requirement-files/docker-image-requirements.txt, benchmarks/micro/test_date_parsing.py, scalyr_agent/date_parsing_utils.py, scalyr_agent/third_party/README.md, scalyr_agent/third_party/dateutil/__init__.py, scalyr_agent/third_party/dateutil/_common.py, scalyr_agent/third_party/dateutil/easter.py, scalyr_agent/third_party/dateutil/parser/__init__.py, scalyr_agent/third_party/dateutil/parser/_parser.py, scalyr_agent/third_party/dateutil/parser/isoparser.py, scalyr_agent/third_party/dateutil/relativedelta.py, scalyr_agent/third_party/dateutil/rrule.py, scalyr_agent/third_party/dateutil/tz/__init__.py, scalyr_agent/third_party/dateutil/tz/_common.py, scalyr_agent/third_party/dateutil/tz/_factories.py, scalyr_agent/third_party/dateutil/tz/tz.py, scalyr_agent/third_party/dateutil/tz/win.py, scalyr_agent/third_party/dateutil/tzwin.py, scalyr_agent/third_party/dateutil/utils.py, scalyr_agent/third_party/dateutil/zoneinfo/__init__.py, scalyr_agent/third_party/dateutil/zoneinfo/rebuild.py, tests/unit/util/date_utils_test.py
This pull request updates our internal date and time parsing library which is used to parse timestamps from the container logs (used by the Docker and Kubernetes monitor) to support non-UTC timestamps with custom time zones.
This issue was reported by our user.
Before, we simply assumed everyone is using UTC on their servers / containers (which is indeed very common and best practice for various reasons - always have servers set to UTC timezone, always store date time values in UTC and then only perform UTC -> selected / local timezone conversion and formatting when data is being displayed).
In the past we performed multiple benchmarks (IIRC, we also have micro benchmarks for it) and it turned out that time parsing takes a non-trivial amount of time in high load situations (which is to be …
=> Add support for non-UTC timestamps in the container log lines

.circleci/config.yml, build_package.py, installer/scripts/scalyr-switch-python.sh, scripts/circleci/run-ami-tests-in-bg.sh, tests/distribution/python_version_change_tests/amazonlinux2_test.py, tests/distribution/python_version_change_tests/centos7/centos7_with_py3_test.py, tests/distribution/python_version_change_tests/centos8_test.py, tests/distribution/python_version_change_tests/common.py, tests/distribution/python_version_change_tests/ubuntu1404/ubuntu1404_test.py, tests/distribution/python_version_change_tests/ubuntu1604/ubuntu1604_test.py, tests/distribution/python_version_change_tests/ubuntu1804/ubuntu1804_test.py, tests/utils/image_builder.py
This PR adds other small fixes to the package tests to make them work after the `scalyr-agent-2-config` file was replaced with a shell script.
PS. Also disabled AMI test for centos 8 because of the bad vault repo availability.
=> Fix package tests

scalyr_agent/util.py
This pull request fixes a small formatting / typo (missing whitespace) in the agent start up line.
=>  Fix typo in the agent start up message

build_package.py
Fixes a small bug in build_package.py which is causing Jenkins CI failure.
```bash
12:12:47  Creating build_info for new build
12:12:47  Traceback (most recent call last):
12:12:47    File "build_package.py", line 1928, in <module>
12:12:47      write_to_file(get_build_info(), "build_info")
12:12:47    File "build_package.py", line 1349, in write_to_file
12:12:47      dest_fp.write(string_value.rstrip())
12:12:47  AttributeError: 'dict' object has no attribute 'rstrip'
12:12:47  Could not create build_info
```
=> Fix bug in build_package.py

.circleci/config.yml, build_package.py
This PR fixes the `set_build_info` function in the `build_package.py` script, so now it handles input as JSON. Before that, it accepted build info as a string. Our release pipeline relies on this function and keeps writing build info as a string, which leads to type error.
I Also reverted some last changes that add back build info file, because it seems that wasn't a root cause.
Another change is that now we use a stable install script in AMI tests even in internal Jenkins build. Before that, we used install script that downloaded packages from an internal repository.
=> Fix package build info

.circleci/config.yml
This pull request updates our Circle CI config to use new and non-deprecated base Docker container images (https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/).
Images we were previously using were deprecated in December - https://circleci.com/docs/2.0/circleci-images.
=> Update to non-deprecated Circle CI base docker images

.github/actions/install-k8s-agent-daemonset/action.yml, .github/actions/setup-minikube-cluster/action.yml, .github/workflows/agent-build.yml, .github/workflows/end_to_end_tests.yml, .github/workflows/publish-docker-images.yml, BUILD.md, CHANGELOG.md, agent_build/package_builders.py, agent_build/tools/environment_deployments/steps/build_base_docker_image/build_base_images_common_lib.sh, build_package_new.py, docker/Dockerfile.docker_monitor_testing_config, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/builtin_monitors/kubernetes_openmetrics_monitor.py, scalyr_agent/copying_manager/copying_manager.py, scalyr_agent/monitor_utils/k8s.py, scripts/cicd/publish-docker-images-tags.py, tests/e2e/k8s_k8s_monitor/std_printer_deployment.yaml, tests/e2e/k8s_om_monitor/scalyr-agent-2-daemonset.yaml, tests/e2e/scalyr-agent-2-daemonset.yaml, tests/unit/builtin_monitors/kubernetes_monitor_test.py, tox.ini
This pull request fixes Kubernetes monitor to correctly handle dynamic pod metadata updates when Kubernetes cluster is using containerd container run time.
When using containerd runtime, scalyr agent would not automatically pick up any pod metadata changes (e.g. adding or changing Scalyr related annotation) without the agent pod restart.
This issue only affected containerd runtime. When using Docker runtime, `ControlledCacheWarmed` abstraction which dynamically populates the cache in background is used.
This fix involves making sure we don't always use locally cached value - now when retrieving pod information from the ``KubernetesCache`` object, we will query Kubernetes API in case the cached entry is stale / expired.
An alternative would be utilize ``ControlledCacheWarmer`` abstraction …
=> Fix dynamic pod metadata updates in the Kubernetes monitor, additional debug level logging, new GHA based Kubernetes end to end tests

.circleci/config.yml, .github/actions/install-k8s-agent-daemonset/action.yml, .github/workflows/end_to_end_tests.yml, scalyr_agent/builtin_monitors/kubernetes_openmetrics_monitor.py, tests/e2e/k8s_om_monitor/scalyr-agent-extra-config-configmap.yaml, tests/unit/builtin_monitors/kubernetes_openmetrics_monitor_test.py, win32/windows-build-requirements.txt
This pull request includes a small changes which allows user to configure the new Kubernetes Open Metrics monitor to include Kubernetes cluster name with each of the emitted metrics log lines.
It follows the same approach as we already follow for the node name inclusion.
=> Optionally include cluster name with all the Kubernetes Open Metrics monitor log lines

scalyr_agent/builtin_monitors/openmetrics_monitor.py, scalyr_agent/scalyr_logging.py, tests/unit/builtin_monitors/openmetrics_monitor_test.py, tests/unit/scalyr_logging_test.py
This pull request allows monitor developer to specify a custom timestamp which is used for the emitted metric log line when using `logger.emit_value()`.
By default, if that value is not specified, timestamp of the time when a ``Record`` object is created is used (same as before).
Right now we use a timestamp when a log ``Record`` object is created when writing a metric log line into a file. 
In most cases that works fine, but in some cases we want to use exactly the same value for multiple metrics to make some server side processing easier.
An example of that is Open Metrics monitor - here we want to use the same timestamp for all the metrics which are scraped and parsed as part of the same scrape / gather sample cycle. T
his makes some server side operations such as joins as easier - …
=> Allow custom timestamp to be specified for emitted metric log lines

.circleci/config.yml, scripts/circleci/run-ami-tests-in-bg.sh, tests/ami/packages_sanity_tests.py, tests/ami/requirements.txt, tests/ami/scripts/test_rpm.sh.j2
This pull request upgrades paramiko and libcloud dependency used by the AMI tests.
New version of paramiko supports newer public key algorithms (e.g. Ubuntu 22.04) and the WIP version of Libcloud includes a workaround / fix so the deployment code still works correctly with older OpenSSH versions which don't support SHA2 based algorithms (e.g. Ubuntu 14.04).
This is needed due to the breaking change in paramiko >= 2.9.0.
=> Upgrade paramiko, libcloud dependency used by the AMI tests

.github/workflows/end_to_end_tests.yml, installer/scripts/check-python.sh
Small change in the pre/post install script to make the output a bit more concise by removing two line breaks.
Before:
```bash
Preparing to unpack .../scalyr-agent-2_2.1.29.pre30.1_all.deb ...
. Searching for python in Path:
/usr/sbin:/usr/bin:/sbin:/bin
- command python not found.
. Searching for python2 in Path:
/usr/sbin:/usr/bin:/sbin:/bin
- command python2 not found.
. Searching for python3 in Path:
/usr/sbin:/usr/bin:/sbin:/bin
+ command python3 [3.8.10] is found and matches the minimum required version - Success!
Unpacking scalyr-agent-2 (2.1.29.pre30.1) over (2.1.29) ...
Setting up scalyr-agent-2 (2.1.29.pre30.1) ...
. Searching for python3 in Path:
/usr/sbin:/usr/bin:/sbin:/bin
+ command python3 [3.8.10] is found and matches the minimum required version - Success!
```
After: …
=> Change formatting of check-python step in pre/post install script

scalyr_agent/scalyr_client.py
From [CT-540](https://scalyr.myjetbrains.com/youtrack/issue/CT-540):
- Change re-attempt log entries to be warnings
- Note there are other re-attempt entries in both scalyr_agent/scalyr_client.py and scalyr_agent/connection.py but they are currently log.exceptions() (untouched)
=> Update re-attempt log entries to be warnings

.github/workflows/end_to_end_tests.yml, scalyr_agent/builtin_monitors/kubernetes_openmetrics_monitor.py, scalyr_agent/builtin_monitors/openmetrics_monitor.py, tests/e2e/k8s_om_monitor/java_app_deployment.yaml, tests/unit/builtin_monitors/kubernetes_openmetrics_monitor_test.py, tests/unit/builtin_monitors/openmetrics_monitor_test.py
This pull request updates Kubernetes Open Metrics monitor and allows user to define arbitrary attributes (key value pairs) which are included with every metric log line as part of labels / extra fields.
Attributes are defined using pod annotations. The actual value needs to be a serialized JSON string where a key is a string and a value is a string (complex / nested objects are not supported).
This comes handy in scenarios where user wants to add additional context (e.g. app name) to the metric to make querying easier.
Example configuration:
```yaml
...
template:
metadata:
labels:
app.kubernetes.io/component: exporter
app.kubernetes.io/name: node-exporter
annotations:
prometheus.io/scrape:                          'true'
prometheus.io/port:                            '9100' …
```
=> Add support for defining arbitrary attributes which are included with every metric in the Open Metrics monitor

CHANGELOG.md, scalyr_agent/scalyr_logging.py, tests/unit/scalyr_logging_test.py
This pull request updates ``emit_value()`` agent logger code which is used by all the monitors to emit metric values to escape / sanitize metric field names which are considered special / reserved (logfile, monitor, metric, value, instance, severity).
This is needed to avoid collisions with special / reserved event attribute names which are set by the server side agent metrics parser code and are needed for various tsdb queries to work correctly.
Those reserved field names are sanitized by suffixing them with `_` (e.g. ``metric`` becomes ``metric``). This suffix was chosen for consistency with the existing server-side parsing behavior (in some situations server side parsing code adds `_` to original field values, e.g. `timestamp_`, ``message_``, etc.).
=>  Escape special metric field names which are considered special / reserved

.circleci/config.yml, CHANGELOG.md, scalyr_agent/builtin_monitors/syslog_monitor.py, tests/unit/syslog_monitor_test.py
This pull request fixes a bug in syslog monitor when running in TCP mode on Windows under Python 3.
When running syslog monitor on Windows under Python 3 in TCP mode, this error would be throw when trying to read data from a socket in non-blocking mode:
```bash
2022-05-31 10:29:12.682Z WARNING [monitor:syslog_monitor] [syslog_monitor.py:873] Error handling request: [WinError 10035] A non-blocking socket operation could not be completed immediately
Traceback (most recent call last):
File "scalyr_agent\builtin_monitors\syslog_monitor.py", line 855, in handle
File "scalyr_agent\builtin_monitors\syslog_monitor.py", line 537, in read
File "scalyr_agent\builtin_monitors\syslog_monitor.py", line 520, in read
BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed …
```
=> Fix for syslog monitor issue on Windows when using TCP protocol

scalyr_agent/agent_main.py, scalyr_agent/builtin_monitors/kubernetes_openmetrics_monitor.py, scalyr_agent/configuration.py, scalyr_agent/metrics/base.py, scalyr_agent/metrics/functions.py, scalyr_agent/scalyr_logging.py, scalyr_agent/scalyr_monitor.py, tests/unit/builtin_monitors/kubernetes_openmetrics_monitor_test.py, tests/unit/scalyr_logging_test.py, win32/dynamic_modules.py
This pull request implements client (agent) side per second rate calculation for "counter" metric types (metric types which values increase over time).
Having this functionality done on the client and not on the server will give us more flexibility and also works better with the new future "stateless" ingestion API.
I went with an implementation where per second rate is calculated inside the ``emit_value()`` method where metric values are emitted. This implementation is the simplest and doesn't require any large refactoring.
---
If in the future we will want to perform more client side aggregations and transformations we may want to change and refactor the code then - perhaps also do that in another background thread so we don't "block" writing metrics to monitor log file on disk in case …
=> Client side rate calculation for counter metrics

scalyr_agent/copying_manager/copying_manager.py, tests/unit/copying_manager_tests/copying_manager_new_test.py
This PR has a potential fix for issues that potentially happened to some of our customers and on our staging servers as well.
The general problem is that in some circumstances, on start, the agent reuploads old logs causing a spike in log volume. I wasn't able to reproduce the customer's issue, but I found several places in our code, which may lead to similar behavior. 
The proposed changes fix:
*  Bug with not picking `active` checkpoint when `full` checkpoints are not presented.
*  Now, the "freshest" checkpoint for a log file that is presented in multiple checkpoint files is selected according to its own timestamp, not by the write timestamp of the whole checkpoint file. That should avoid the situation where a checkpoint file with the most recent checkpoint has been written earlier …
=> Fix copying manager checkpoints selecting logic 

.circleci/config.yml, .github/workflows/agent-build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/end_to_end_tests.yml, .github/workflows/publish-docker-images.yml
This pull request is an attempt at reducing the permissions for Github token used by the GHA workflows to the minimum.
By default, token gets assigned broad set of permissions and for security reasons, we want to reduce those to the bare minimum which is needed for the workflows to run.
Default permissions (from https://github.com/scalyr/scalyr-agent-2/runs/6904005239?check_suite_focus=true job)
```bash
GITHUB_TOKEN Permissions
Actions: write
Checks: write
Contents: write
Deployments: write
Discussions: write
Issues: write
Metadata: read
Packages: write
Pages: write
PullRequests: write
RepositoryProjects: write
SecurityEvents: write
Statuses: write
```
NOTE: The permissions YAML syntax is a bit weird and in case only a single permission is specified, rest of the permissions will default …
=> Reduce permissions for GHA token used by GHA workflows to the minimum

CHANGELOG.md, agent_build/docker/Dockerfile.base
Disable orjson library  in arm64 alpine docker image due to upstream issues with its build.
=> disable orjson for alpine arm64, since its build fails with memory leak.

CHANGELOG.md, scalyr_agent/json_lib/parser.py, tests/unit/configuration_test.py, tests/unit/json_lib/parser_test.py
Our custom JSON parser does check for the end of the document after its parsing. For example ,if we put extra closing curly brackets in the middle of the object, it doesn't raise any error and just returns "incomplete" object.
Here the result object will miss the `filed2` filed and won't raise anything.
```
{
api_key: ",key."
field1: 1,
}
filed2: 2
}
```
There's also the case where the customer accidentally commented out the beginning of the nested object:
```
{
api_key: ",key."
// server_attributes: {       // the beginning of the nested object is commented.
serverHost: "HOST",        // the 'serverHost' field is wrongly parsed as a filed of outer object.
}                             // this brackets are treated as end of the whole JSON document.
// Everything that remains is just …
```
=> Fix invalid end of the json parsing.

CHANGELOG.md, agent_build/docker/Dockerfile.base, agent_build/requirement-files/main-requirements.txt
This pull request upgrades orjson dependency used by Docker images to 3.7.3 (https://github.com/ijl/orjson/blob/master/CHANGELOG.md#373---2022-06-23).
=> Upgrade orjson dependency used by Docker images to 3.7.3

.github/workflows/end_to_end_tests.yml
This pull request adds missing GHA token permission which is needed for skip duplicate actions job to run (https://github.com/fkirc/skip-duplicate-actions).
> 
> For GitHub repositories where [default permissions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository) for GITHUB_TOKEN has been set to "permissive (read-only)", the following lines must be included in the workflow (see [permissions syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions)):
> 
> # Minimum permissions required by skip-duplicate-actions
> permissions:
>   actions: write
> …
=> Add missing GHA token permission

CHANGELOG.md, agent_build/requirement-files/main-requirements.txt
Primarily pulling in a segfault on dealloc fix:
https://github.com/ijl/orjson/commit/4d2011931947d4b5dd355d9fd0d562ee6cc5dff9
https://github.com/ijl/orjson/pull/273
Need to jump to 3.7.5 though since it fixes a bug included in 3.7.4.
=> Bump orjson version to pull in upstream fixes

.github/dependabot.yml
This pull request adds dependabot config which instructs dependabot to also try to keep Github actions referenced in Github Action workflows up to date.
Reference: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> Add dependabot config 

.github/workflows/publish-docker-images.yml
Currently the release is blocked by the image publish workflow breaking.
The agent-build.yml workflow calls the version of
publish-docker-images.yml workflow from the master branch, and the
publish-docker-images.yml workflow runs a python script that is present
in the branch the workflow is being run from (which is not necessarily
the master branch). We're running the python script with arguments it
doesn't recognize, and then it crashes.
To unblock the release without having to resort to merging workflow
changes into the release branch (which would be tantamount to creating a
new release), remove the openmetrics monitor target from the matrix
build. Once the images have been published, this change can be reverted.
=> Unblock release by removing openmetrics monitor from workflow

.github/workflows/publish-docker-images.yml
Reverts scalyr/scalyr-agent-2#923
The release workflow completed successfully. This can be added back.
=> Revert "Unblock release by removing openmetrics monitor from workflow"

.github/workflows/agent-build.yml, docker/k8s-config/agent.d/k8s_open_metrics_monitor.json, scalyr_agent/builtin_monitors/kubernetes_events_monitor.py, scalyr_agent/builtin_monitors/kubernetes_openmetrics_monitor.py, scalyr_agent/configuration.py, tests/e2e/k8s_om_monitor/scalyr-agent-2-daemonset.yaml, tests/unit/builtin_monitors/kubernetes_openmetrics_monitor_test.py, tests/unit/configuration_k8s_test.py
This pull request adds new ``k8s_explorer_enable`` config option which enables additional metrics collection which is needed for Kubernetes Explorer functionality.
Right now Kubernetes Explorer also depends on some metrics from Kubernetes Events Monitor so when ``k8s_exlorer_enable`` is True, kubernetes events monitor is enabled as well.
For now, this PR also disables building ``k8s-with-openmetrics-monitor`` images (with those changes, those are not needed anymore, but I left code in place in case we may need them in the future - e.g. if we want to release new explorer agent version without main agent release).
=> Enable additional Kubernetes metrics collection via global config option

CHANGELOG.md, scalyr_agent/builtin_monitors/windows_process_metrics.py, scalyr_agent/builtin_monitors/windows_system_metrics.py, tests/unit/builtin_monitors/test_windows_process_metrics.py, tests/unit/builtin_monitors/test_windows_system_metrics.py
This pull request fixes a bug in Windows System and Windows Process monitor which didn't allow user to override / change the default sample interval of 30 seconds using ``sample_interval`` monitor config option.
=> Fix sample interval overriding in the Windows System and Windows Process monitor

CHANGELOG.md, conftest.py, scalyr_agent/agent_main.py, scalyr_agent/configuration.py, tests/unit/configuration_test.py, tests/unit/log_processing_test.py, tests/unit/util/json_util_test.py
This pull request fixes bug in the ``import_vars`` functionality which would not work correctly when multiple variables used the same common prefix (e.g. ``SCALYR_FOO, SCALYR_FOO_BAR, SCALYR_FOO_BAZ``).
Proposed fix in this PR includes sorting variable names by length in the descending order (from the longest to the shortest) when applying variable substitutions. This way we make sure that the correct and most "specific" variable is used when common prefix is shared by multiple variables.
It's worth noting that we can't use regular expressions directly since we support partial / inline substitutions, e.g. (``foo$VARIABLE_BARbaz``).
=> Fix a bug with "import_vars" functionality which would not work correctly when multiple variables used the same common prefix

CHANGELOG.md, agent_build/requirement-files/compression-requirements.txt, agent_build/requirement-files/docker-image-requirements.txt, agent_build/requirement-files/main-requirements.txt, agent_build/requirement-files/testing-requirements.txt, lint-requirements.txt
This pull request updates the following dependencies used by the Docker images:
* orjson - https://github.com/ijl/orjson/blob/master/CHANGELOG.md#377---2022-07-06
* requests - https://github.com/psf/requests/blob/main/HISTORY.md#2281-2022-06-29
* docker - https://docker-py.readthedocs.io/en/stable/change-log.html#
* zstandard
* lz4 - https://github.com/python-lz4/python-lz4/releases/tag/v4.0.1
* yappi (debug dependency) - https://github.com/sumerc/yappi/blob/master/CHANGELOG#L4
* pympler (debug dependency) - https://github.com/pympler/pympler/blob/master/CHANGELOG.md#101---2021-12-22
NOTE: Right now our dependencies are a bit of a mess and docker dependencies are also installed by different test targets (including Python 2.7 unit tests) which means I needed to use environment markers.
=> Upgrade dependencies used by the Docker images

agent_build/requirement-files/testing-requirements.txt, benchmarks/scripts/send_usage_data_to_codespeed.py, tests/conftest.py, windows-unit-tests-requirements.txt
This pull request makes ``pyyaml`` dependency optional since it's not used by any code out of the box (it's only used when ``--test-config`` config option is specified and that doesn't seem to be used by any automated tests right now).
This allows us to simplify our requirements files and get rid of vulnerable (test only) dependency under Python < 3.8.
=> Remove optional pyyaml dependency used by tests

scalyr_agent/builtin_monitors/kubernetes_openmetrics_monitor.py, scalyr_agent/configuration.py, scalyr_agent/instrumentation/decorators.py, scalyr_agent/instrumentation/timing.py, scalyr_agent/metrics/base.py, scalyr_agent/metrics/functions.py, scalyr_agent/scalyr_logging.py, scalyr_agent/timing.py, scalyr_agent/util.py, tests/unit/builtin_monitors/kubernetes_openmetrics_monitor_test.py, tests/unit/scalyr_logging_test.py, tests/unit/test_instrumentation.py, tests/unit/test_metrics_functions.py, tests/unit/test_timing_module.py, tests/unit/test_util_test.py
This pull request includes some improvements and fixes for the client side rate calculation functionality to make sure it works correctly when metric contains additional labels (``extra_fields``).
Monitor can produce metrics which look like this:
```bash
process_cpu_seconds_total app="app-1" node="node-1" 155
process_cpu_seconds_total app="app-2" node="node-1" 155
process_cpu_seconds_total app="app-3" node="node-1" 155
process_cpu_seconds_total app="app-3" node="node-3" 155
```
In this case all the metrics have the same name (``process_cpu_seconds_total``), but they represent different metrics and we need to track rate separately for each of those (for each ``(metric name, unique extra fields / labels)`` pair).
In addition to fixing and making sure we currently handle high cardinality …
=> Improvements for the client (agent) side rate calculation

CHANGELOG.md, agent_build/package_builders.py, build_package.py, scalyr_agent/config_main.py, tests/package_tests/internals/docker_test.py, tests/unit/agent_main_test.py
Fix `--import-config`, `--export-config` options of the `scalyr-agent-2-config` comand which is caused by Python2,3 incompatibility.
I also noticed, that docker images don't have `scalyr-agent-2-config` compatibility script, which caused errors on docker images when running config commands.
=> Fix config export config

scalyr_agent/agent_main.py, scalyr_agent/builtin_monitors/kubernetes_events_monitor.py, scalyr_agent/configuration.py, scalyr_agent/instrumentation/constants.py, scalyr_agent/metrics/base.py, scalyr_agent/metrics/functions.py, tests/unit/builtin_monitors/kubernetes_openmetrics_monitor_test.py, tests/unit/scalyr_logging_test.py, tests/unit/test_metrics_functions.py
This pull request includes two small improvements:
1. Make sure Kubernetes Events monitor only logs message on initialize when monitor is disabled via environment variable or config option. I also added rate limit for that log call to avoid duplicate messages under some scenarios.
2. Allow user to change logging interval which is used to log instrumentation related statistics to agent.log using INFO log level. This can come handy in various troubleshooting scenario, but most users should leave this value as is on production deployments (since low value could add a lot of overhead).
Since code where those messages are logged doesn't have direct access to global Configuration object instance (technically, I could access it via ``monitor._global_config``, but I'm not 100% sure this is always …
=> Instrumentation logging improvements

scalyr_agent/configuration.py, scalyr_agent/metrics/base.py, scalyr_agent/metrics/functions.py, tests/unit/scalyr_logging_test.py, tests/unit/test_metrics_functions.py
This pull request includes two changes:
1. Fix invalid ``log.info()`` function call arguments order
2. Introduce clean up routine for the ``RateMetricFunction`` function which periodically cleans up old / stale values.
We need periodic clean up routine to ensure internal data structure which stores metric values doesn't grow too large and that stale / unused values are correctly removed (a lot of stored metrics will become stale and unused over time since they will refer to resources which are now gone - imagine metric which refer to old containers, old nodes, etc.)
NOTE: In the future I may refactor some of that functionality and instead of having a global singleton instance of ``RateMetricFunction`` move it to an approach where we have an instance per ``ScalyrMonitor`` (I think this …
=> Introduce clean up routine for RateMetricFunction, fix log function argument order

CHANGELOG.md, scalyr_agent/scalyr_logging.py, tests/smoke_tests/monitors_test/postgres_test.py, tests/unit/builtin_monitors/kubernetes_monitor_test.py, tests/unit/scalyr_logging_test.py, tests/utils/log_reader.py
This pull request updates ``AgentLogFormatter`` to include full module name (previously only the file name was included).
This allows us to disthinghuish between different modules which use the same name (but belong to a different package).
Before:
```bash
2022-07-24 13:15:19.697Z WARNING [monitor:linux_system_metrics()] [tcollector.py:148] iostat.py: b'Traceback (most recent call last):'
```
After:
```bash
2022-07-24 13:15:19.697Z WARNING [monitor:linux_system_metrics()] [scalyr_agent.third_party.tcollector.tcollector:148] iostat.py: b'Traceback (most recent call last):'
```
=> Include full module name in the agent log messages

tests/unit/scalyr_logging_test.py
This pull request adds some unit tests for changes in #946 (some how I missed that in #946).
=> Add tests for AgentLogFormatter.format() fqname handling

CHANGELOG.md, scalyr_agent/builtin_monitors/docker_monitor.py, scalyr_agent/monitor_utils/k8s.py
log warning error instead of error on non-critical docker container metric stat request. Our tests  parse agent log for errors and this error may happen often due to some race condition, but it is recoverable so it shouldn't be considered as ERROR/
=> Turn container metrics request error to warning.

scalyr_agent/agent_status.py, scalyr_agent/monitors_manager.py, scalyr_agent/scalyr_monitor.py, tests/unit/agent_status_test.py
This PR adds logging on startup for the monitor 'stop_agent_on_failure' option and adds 'stop_agent_on_failure' info for the monitor in agent status output.
Here's how monitor startup log line has to look like if monitor has 'stop_agent_on_failure' enabled:
```
2022-08-08 12:25:48.333Z INFO [core] [scalyr_agent.monitors_manager:379] Starting monitor test_monitor(essential). Config option 'stop_agent_on_failure' is enabled.
2022-08-08 12:25:48.333Z INFO [core] [scalyr_agent.monitors_manager:379] Starting monitor test_monitor(not_essential).
2022-08-08 12:25:48.333Z INFO [core] [scalyr_agent.monitors_manager:379] Starting monitor test_monitor(not_essential_default).
2022-08-08 12:25:48.334Z INFO [core] [scalyr_agent.monitors_manager:186] Starting Scalyr Monitors manager thread
```
Agent …
=> Add logging on startup for the monitor 'stop_agent_on_failure' option.

scalyr_agent/metrics/functions.py, tests/unit/scalyr_logging_test.py, tests/unit/test_metrics_functions.py
This pull request fixes a bug / edge case with the client side rate calculation where metric extra_field (label / tag) contains a special ``timestamp`` value which changes during each gather sample interval.
This ``timestamp`` extra field value is special because it changes during each sample gather interval and we don't want to include it when calculating unique identifier for high cardinality metric (including it would means that during each new sample gather we would create a new unique id for a high cardinality metric which has all the fields except ``timestamp`` the same, but that's not something we want).
This pull request fixes this edge case and makes sure ``timestamp`` extra field value is not used when calculating unique id for a high cardinality metric. This value itself is …
=> Fix an edge case with the client side metric rate calculation

CHANGELOG.md, scalyr_agent/scalyr_client.py
Make this exception log message as warning to calm down our tests, since they look for any ERROR log messages and this particular error is not fatal.
NOTE: Since it caches unknown error, we still have to provide exception traceback.
=> Log warning message in case of unknown connection error

.github/workflows/codespeed.yml
Adds codespeed workflow and micro-benchmark job to GHA.
The value of `CODESPEED_ENVIRONMENT` does not match what is used in CircleCI. I did this because the hardware configuration is different, so I thought it made sense to reflect that. I had to create the Environment database record by hand in the codespeed django admin interface.
CT-578
=> CT-578 Add codespeed workflow for GHA

.github/workflows/lint.yml, .github/workflows/unittests.yml
Create cron jobs and slack notifications on failure for new GHA
workflows as requested in #961 
CT-573
=> Configure cron job and slack notifications for new GHA workflows

.gitignore, agent_build/requirement-files/compression-requirements.txt, agent_build/requirement-files/docker-image-requirements.txt, agent_build/requirement-files/main-requirements.txt, agent_build/requirement-files/testing-requirements.txt
This pull request updates various dependencies before the release:
* orjson - https://github.com/ijl/orjson/blob/b9e8e7f88715b897c7f2b4cd15d1872c67240a06/CHANGELOG.md#3712---2022-08-14
* lz4 - https://github.com/python-lz4/python-lz4/releases/tag/v4.0.2
* docker - https://docker-py.readthedocs.io/en/stable/change-log.html
=> Pre release dependencies update

.coveragerc, .github/workflows/end_to_end_tests.yml, codecov.yml
This PR is to fix the issue identified in the following comment:  https://github.com/scalyr/scalyr-agent-2/pull/961#issuecomment-1216311694
The problem was the sed processing of the coverage files was creating bad paths. Instead of fixing the issue, I decided to use the same coverage reporting pattern used in the unittests workflow. Changes made:
- Add agent code path in smoke test docker image to .coveragerc and
codecov fixes config.
- Use same coverage reporting pattern as unittests (as we know that
workflow works).
- Remove manual processing of coverage files via sed.
CT-573
=> CT-573 Fix coverage issues with smoke tests

.github/workflows/codespeed-agent-benchmarks.yaml, .github/workflows/codespeed.yml, benchmarks/scripts/requirements.txt
Port codespeed agent benchmark jobs from circleci to GHA.
FYI the job fails unless it is run on the master branch or release branch due to codespeed not accepting results for any other branch.
CT-577
=> CT-577 Add codespeed agent benchmark jobs to GHA

scalyr_agent/builtin_monitors/windows_event_log_monitor.py
Changed the Windows event monitor NewJsonApi parser to be dottedEscapedJson to accommodate embedded double quotes.
More notes/details in [DSET-355](https://jira-ng.sentinelone.com/browse/DSET-355)
=> Windows event monitor json api to use dottedEscapedJson parser

CHANGELOG.md, scalyr_agent/builtin_monitors/syslog_monitor.py, tests/unit/syslog_monitor_test.py
This pull request updates ``SyslogRequestParser`` class in the syslog monitor to ignore errors which may error when trying to decode byte sequence into utf-8 unicode string. This class is used when TCP transport is used and when ``tcp_request_parser`` parser is set to ``default`` (aka default behavior).
Previously an exception would be thrown in case we encountered invalid utf-8 sequence, but now we simply ignore non valid utf-8 data.
It's worth noting that exactly the same thing already happens inside ``SyslogBatchedRequestParser`` class which is used when ``tcp_request_parser`` is set to ``batch``.
=> Update syslog monitor to ignore invalid utf-8 byte sequences

.github/actions/setup-minikube-cluster/action.yml, .github/workflows/agent-build-refactored.yml, .github/workflows/codespeed.yml, .github/workflows/end_to_end_tests.yml, .github/workflows/unittests.yml, scripts/cicd/scalyr-query.sh
I noticed some of the Github action jobs were being incorrectly skipped on master branch runs (e.g. https://github.com/scalyr/scalyr-agent-2/runs/8068790013).
We always want to run jobs on master branch merge / push and only skip duplicate / redundant jobs on pull request.
This pull request fixes all the jobs to make sure we don't skip run on master branch and also fixes the conditional which were likely unintentionally changed from "or" to "and" which won't produce the desired behavior.
```dif
-    if: ${{ needs.pre_job.outputs.should_skip != 'true' || github.ref == 'refs/heads/master' }}
+    if: ${{ needs.pre_job.outputs.should_skip != 'true' && (github.ref == 'refs/heads/master' || github.base_ref == 'master') }}
```
We always want to run checks on master branch to catch any issues …
=> Don't skip Github Action job runs on master branch merge / push

.github/workflows/agent-build.yml, .github/workflows/codespeed-agent-benchmarks.yaml, .github/workflows/codespeed.yml, .github/workflows/end_to_end_tests.yml, .github/workflows/lint.yml, .github/workflows/publish-docker-images.yml, .github/workflows/unittests.yml
The cloud-tech channel was renamed a while ago. Update the GHA workflows
with the current channel name to fix notifications.
=> Update slack channel for GHA notifications to renamed channel

docs/monitors/windows_event_log_monitor.md, scalyr_agent/builtin_monitors/windows_event_log_monitor.py
From DSET-368, note that the existing implementations (ie OldApi, NewApi) already set the monitor field via scalyr_logging.AgentLogger.emit_value
(ref: https://app.scalyr.com/y/2eXCRLjoJjF)
Changes:
- Set the monitor field in NewJsonApi for each event
- Added a define_log_field entry for monitor (for consistency with other monitors)
=> Window event log monitor NewJsonApi to set monitor field

scalyr_agent/builtin_monitors/windows_event_log_monitor.py
Notes in DSET-528
Wrapping the call to EvtOpenPublisherMetadata call in a try/except block to allow the publisher metadata to be null/None (which would occur for forwarded events).  Verified this will not cause problems downstream, worst case scenario is that the RenderingInfo section will be mostly empty, moreover this is the approach being done for the older non-json implementation in the monitor (ie NewApi)
=> DSET-528: Windows event log monitor NewJsonApi metadata fix

scripts/check-bundled-ca-certs-expirations.py
Lint check has recently started failing with this error:
```bash
(2028-12-31 23:59:59)
Traceback (most recent call last):
File "./scripts/check-bundled-ca-certs-expirations.py", line 91, in <module>
main()
File "./scripts/check-bundled-ca-certs-expirations.py", line 86, in main
cert_path, expire_in_threshold_timedelta=DEFAULT_EXPIRE_THRESHOLD_TIMEDELTA
File "./scripts/check-bundled-ca-certs-expirations.py", line 56, in fail_if_cert_expires_in_timedelta
% (cert_path, expire_in_days, cert.not_valid_after)
Exception: Certificate /home/runner/work/scalyr-agent-2/scalyr-agent-2/certs/scalyr_agent_ca_root.pem will expire in 703 days (2024-09-06 21:52:05), please update!
ERROR: InvocationError for command /usr/bin/bash -c 'python ./scripts/check-bundled-ca-certs-expirations.py' (exited with code …
```
=> Decrease cert expiration alerting threshold from 2 years to 1 year

.circleci/config.yml, CHANGELOG.md, agent_build/docker/Dockerfile.base
This PR updates Docker images to use latest Python 3.8 version (3.8.4). There was a highly debated bug / potential security issue fixed recently in that release - https://www.python.org/downloads/release/python-3814/.
> CVE-2020-10735: converting between int and str in bases other than 2 (binary), 4, 8 (octal), 16 (hexadecimal), or 32 such as base 10 (decimal) now raises a ValueError if the number of digits in string form is above a limit to avoid potential denial of service attacks due to the algorithmic complexity.
In addition to that, it also updates Windows binary to use latest Python 3.10 version (3.10.7) - https://docs.python.org/release/3.9.14/whatsnew/changelog.html. This version includes fix for the same CVE.
=> Upgrade Python version uses by Docker images, Windows binary

CHANGELOG.md, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/configuration.py, scalyr_agent/scalyr_client.py
This pull request updates scalyr client code to log how long it takes to read / process the response from the socket.
This will hopefully make it slightly easier to see what is going on when we see connection reset by peer / connection timeout and similar errors.
It also includes some other changes:
* Log which version of docker-py and requests library is used so we can see if it's using system version or bundled / vendored one
* Allows user to configure Docker client library connection timeout and maximum connection pool size when using Docker container enumerator via new `k8s_docker_client_timeout` and `k8s_docker_client_max_pool_size` config option.
=> Agent connection logging improvements and misc changes

CHANGELOG.md, agent_build/requirement-files/docker-image-requirements.txt, agent_build/requirement-files/testing-requirements.txt
This PR updates docker-py dependency to the latest stable version v6.0.0 (https://github.com/docker/docker-py/releases/tag/6.0.0).
=> Upgrade docker-py to 6.0.0

scalyr_agent/builtin_monitors/kubernetes_monitor.py
Small logging change to also log the value of ``SCALYR_K8S_EVENTS_DISABLE`` environment variable in the Kubernetes monitor to make it more easy to see which value is currently in effect.
=> Update k8s monitor to also log value of SCALYR_K8S_EVENTS_DISABLE environment variable

tests/ami/scripts/test_windows.ps1.j2
The intention here was to add an additional test to help cover the change introduced by DSET-355 / PR #983 
However the DSET-355 change doesn't manifest until after the event has been received by the Scalyr servers (because it relies on a specific parser), so it's debatable whether this added check is worth including as it is.
Alternatively a check could be added to the ami test script that queries for the event from Scalyr and verifies it's what is expected.  There are some challenges associated with this:
- Will need to make the server hostname & api key available to the powershell script
- Will need to take care that simultaneous executions don't interfere with each other (by introducing a random value in the checked message?)
Let me know what you think
=> Added quoted text to windows event log monitor ami test

.github/actions/execute-runner/action.yml, .github/actions/perform-deployment/action.yml
This pull request updates our custom GHA actions to use Node.js 16 instead of Node.js 12 which is EOL and unsupported.
More context - https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
=> Use non-EOL Node.js 16 instead of Node.js 12 in our custom GHA actions

windows-unit-tests-requirements.txt
Small change to use newer requests version inside Windows unit tests. Older version we previously used has known security vulnerabilities.
=> Use non vulnerable requests version in the windows unit tests

CHANGELOG.md, k8s/default-namespace/scalyr-agent-2.yaml, k8s/no-kustomize/scalyr-agent-2.yaml, k8s/scalyr-agent-2-envfrom.yaml, k8s/scalyr-agent-2.yaml, tests/e2e/scalyr-agent-2-daemonset.yaml
This pull request adds ``securityContext.allowPrivelegeEscalation: false`` annotation to the agent container in the Kubernetes DaemonSet definition file to see if it works (best practice, least privilege mantra - albeit this is a bit moot here since agent is considered as a privileged process).
I don't think it would work with regular installation (iirc, tcollectors rely on setuid, but those don't run in k8s images), but we will see if tests pass or not.
=> Try adding "securityContext.allowPrivelegeEscalation: false" to the agent container

.github/workflows/codespeed-microbenchmarks.yml, .github/workflows/codespeed.yml, agent_build/requirement-files/compression-requirements.txt, agent_build/requirement-files/docker-image-requirements.txt, agent_build/requirement-files/testing-requirements.txt, benchmarks/micro/test_compression_algorithms.py, benchmarks/scripts/requirements.txt, tox.ini
This pull request updates micro + process level benchmarks to also run under new Python 3.11 to see how it impacts those benchmarks.
=> Also run some micro + process level benchmarks under Python 3.11

CHANGELOG.md, RELEASE_NOTES.md, scalyr_agent/builtin_monitors/kubernetes_monitor.py
From DSET-840:
The memory usage metric retrieved from the Docker api has the filesystem cache included, this change removes the cache value (if present) for consistency with the Kubelet api (kubectl top) / metrics-server, docker stats, etc
Ref: https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerStats
```
import docker
client = docker.APIClient(base_url='unix://var/run/docker.sock', version='auto')
client.stats(container='<container-id>', stream=False)['memory_stats']
```
=> DSET-840: Adjust memory_stats.usage for consistency with other tools

.github/actions/install-k8s-agent/action.yml, .github/actions/setup-minikube-cluster/action.yml, .github/workflows/end_to_end_tests.yml
This pull request makes small changes to 2 actions which are currently bundled with this repo so they are a bit more generic and can be re-used outside of this repo.
In ideal world, those actions would live in a separate re-usable repo, but setting this up + whole infrastructure for that would take quite some time.
=> Make 2 bundled Github actions more generic and re-usable

docs/monitors/windows_event_log_monitor.md, scalyr_agent/builtin_monitors/windows_event_log_monitor.py, tests/unit/cache_test.py
- Added debug logs for couple scenarios
- Periodically (every 12 hours) log cache usage stats
- Ensured safe to call `_DLL.__del__` multiple times
- Added support for entry ttl in Cache, added unit test
- Made cache sizes and ttls configurable
=> DSET-1106: PR 1024 feedback

.github/actions/setup-minikube-cluster/action.yml
This pull request updates ``manusa/actions-setup-minikube`` action to the latest version which supports Ubuntu 22.04.
Builds in other repos which utilize Ubuntu 22.04 runner started failing and hopefully this change will fix it.
=> Update setup minikube GHA action to latest version

CHANGELOG.md, agent_build/docker/Dockerfile.base, agent_build_refactored/tools/run_in_ec2/boto3_tools.py
Small change on top of #1066 so we also upgrade ``setuptools`` in Alpine based Docker images to avoid setuptools related security alert.
In addition to that, I also pinned setuptools to a fixed version (latest stable) to ensure build is more reproducible.
=> Also upgrade setuptools in the Alpine Docker image, pin setuptools

.github/workflows/codespeed-agent-benchmarks.yaml, .github/workflows/codespeed-microbenchmarks.yml, .github/workflows/end_to_end_tests.yml, benchmarks/micro/test_syslog_parsing.py, scalyr_agent/builtin_monitors/syslog_monitor.py, tests/end_to_end_tests/run_in_remote_machine/__init__.py, tox.ini
This pull request includes initial very basic baseline micro benchmark for the new extended syslog message parsing code which is exercised when message templates functionality is used.
Right now this is just an initial benchmark which measures overhead of message parsing. In the future we should extend it so it also covers / measures the following scenarios:
* Exercise various difference message formats
* Also take into account / measure log watcher management and log file creation (for that we will also need to use dynamic protos, src ips, etc. and parameterize those values)
=> [DSET-1379] [DSET-1600] Add initial baseline microbenchmarks for syslog parsing code

scripts/cicd/scalyr-query.sh
This pull request makes a small change to the scalyr query script which is used by end to end tests so we can specify the actual query as a single command line argument or as multiple ones.
Previously, only notation like this was supported:
```bash
./scalyr-agent-2/scripts/cicd/scalyr-query.sh '$serverHost="'${SCALYR_AGENT_SERVER_HOST}'" $logfile="/var/log/scalyr-agent-2/agent.log" "Starting scalyr agent..."'
```
And now we can also do things like this:
```bash
./scalyr-agent-2/scripts/cicd/scalyr-query.sh \
'$serverHost="'${SCALYR_AGENT_SERVER_HOST}'"' \
'$logfile="/var/log/scalyr-agent-2/agent.log"' \
'"Starting scalyr agent..."'
```
This allows us to split long queries over multiple lines to make things a bit more readable.
It's worth noting that somewhat similar thing could already be …
=> Update scalyr query utility script

benchmarks/micro/test_syslog_parsing.py, scalyr_agent/builtin_monitors/syslog_monitor.py
- Pass the global config from SyslogMonitor (via SyslogServer) to SyslogHandler
- Then match current log path with potential log config from the global config
- This is needed to know which parser & attributes to apply when creating the logger
=> DSET-1628: message_log_template & attributes not applied without checkpoint

.github/workflows/codespeed-agent-benchmarks.yaml, .github/workflows/codespeed-microbenchmarks.yml, benchmarks/micro/test_syslog_parsing.py
It looks like #1078 inadvertedly broke syslog micro benchmark.
This PR fixes it.
In the past we intentionally only ran benchmark jobs for master branch and not for every PR branch since that would be too slow, but maybe it make sense to also run microbenchmarks on all the PRs now that we have trimmed down the Python version matrix, but only submit results to CodeSpeed on master branch.
=> Fix syslog micro benchmark, also run micro benchmarks on non-master branches

.pre-commit-config.yaml, tox.ini
When I was following README.md how to test scalyr agent, I was not able to finish it for the following reasons:
1. Configuration `passenv`: Values cannot no longer be separated by spaces - https://github.com/tox-dev/tox/issues/2615
2. Configuration `whitelist_externals`: This config option no longer exists and was replaces with `allowlist_externals` - https://github.com/tox-dev/tox/pull/2134 + https://github.com/tox-dev/tox/pull/2600
When I was trying to commit changes, it has failed since `pre-commit` was configured to use `Python 3.6` - https://devguide.python.org/versions/ - which is no longer supported. So I have bumped it to `3.10`.
=> Fix tox.ini to be compatible with latest version

.github/workflows/agent-build-new.yml, .github/workflows/reusable-agent-build-windows.yml, agent_build_refactored/managed_packages/files/bin/agent-libs-config, agent_build_refactored/managed_packages/install-scriptlets/preuninstall.sh, agent_build_refactored/managed_packages/managed_packages_builders.py, tests/end_to_end_tests/managed_packages_tests/test_packages.py, tests/end_to_end_tests/tools.py
This PR, to reduce noise, removes some warnings that are produced during the package uninstallation. 
Other changes: 
* It also disables check of the new version of the pip, so the update suggestion message won't shown every time.
* Also corrected venv removal during the `pre-uninstall` script execution.
* Retries added to the package status tests to reduce overall flakiness.
=> Fix post-uninstall warnings

CHANGELOG.md, scalyr_agent/builtin_monitors/docker_monitor.py
This PR ensures we have a rate limit in place for the ``No timestamp found on line:`` log message in the Docker monitor.
Agent on one of my servers some how ended up in a bad state where ``No timestamp found on line:`` log message would get logged very often. This would cause the agent to exhaust all the CPU cycles just by logging this message.
I don't know the exact root cause for that edge case (it could be something related to Docker daemon upgrade or similar), but it doesn't matter that much since we need a rate limit (aka this fix) regardless.
Here is the message which appeared in the logs:
> 21:33:12.017​nuc.tomaz.me​/var/log/scalyr-agent-2/agent.log​2023-02-25 20:33:12.017Z ERROR [monitor:docker_monitor] [scalyr_agent.builtin_monitors.docker_monitor:1637] No timestamp found on …
=> Fix logging bug in the Docker monitor

agent_build_refactored/tools/run_in_ec2/cleanup_ec2_objects.py
This small PR handles edge case in ec2 cleanup script when running instance does not have any tags.
=> fix empty tags error on ec2 instances cleanup.

CHANGELOG.md, docs/monitors/postgres_monitor.md, scalyr_agent/builtin_monitors/postgres_monitor.py
Support SSL connections to PostgreSQL. Enable by setting `use_ssl` to `True` in the `postgres_monitor` config.
DSET-2112
=> DSET-2112 Support SSL connections to PostgreSQL

.github/workflows/end_to_end_tests.yml, .github/workflows/unittests.yml, agent_build/requirement-files/testing-requirements.txt, dev-requirements-new.txt, windows-unit-tests-requirements.txt
This pull request fixes a build which was failing due to the missing ``codecov`` PyPi package / dependency.
codecov Python package has been deprecated for a while and replaced by the codecov uploader GHA action (https://docs.codecov.com/docs/deprecated-uploader-migration-guide#python-uploader). Now the package has been fully removed from PyPi which started to cause build failures.
=> Fix build due to the missing codecov dependency

.github/workflows/unittests.yml
This PR is attempt to fix unit and smoke tests to get them running under Python 2.7 again.
In fact I can't get it to work in an hour or two, I will likely just remove those tests - we have already spend tons of time on it in the past and it's been a massive head ache trying to get tests to still work with Python 2.7 which has been EOL for 3+ years and removed from most platforms and dependencies we use.
Github recently removed support for Python 2.7 from their cloud runners and setup-python action (https://github.com/actions/setup-python/issues/672#issuecomment-1589120020) so those tests started failing.
=> Try running Python 2.7 unit tests in a container to work around removal

.github/workflows/agent-build.yml
This pull request updates Docker Image Build workflow trigger to make sure it's also triggered on push to a tag (which happens as part of the release process).
=> Update workflow trigger to make sure Docker image build is also triggered on push to a tag

dev-requirements-new.txt, tests/unit/scalyr_client_test.py
https://sentinelone.atlassian.net/browse/DTIN-2974
requests==2.31.0 - in order to get certifi==2023.7.22
docker==6.1.3 - version compatible with the new requests
pysnmp==4.4.12 - to in order to fix the pycrypto vulnerability
All effective changes:
```
2,3c2,3
< charset-normalizer==2.1.1
< docker==6.0.0
---
> charset-normalizer==3.2.0
> docker==6.1.3
4a5,6
> lz4==4.0.2
> orjson==3.8.0
10c12
< pycrypto==2.6.1
---
> pycryptodomex==3.18.0
13c15
< pysnmp==4.3.0
---
> pysnmp==4.4.12
17c19
< requests==2.28.1
---
> requests==2.31.0
21c23
< urllib3==1.26.16
---
> urllib3==2.0.4
22a25
> zstandard==0.19.0
```
=> Packages updated to fix vulnerabilities.

agent_build_refactored/container_images/image_builders.py
The old version was deleted from quay.
https://sentinelone.atlassian.net/browse/DTIN-3088
=> Skope version upgraded

.github/workflows/reusable-agent-build-container-images.yml, agent_build_refactored/container_images/base_images/ubuntu-fips.Dockerfile, scalyr_agent/builtin_monitors/__init__.py, scalyr_agent/builtin_monitors/apache_monitor.py, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/builtin_monitors/kubernetes_openmetrics_monitor.py, scalyr_agent/builtin_monitors/nginx_monitor.py, scalyr_agent/builtin_monitors/openmetrics_monitor.py, scalyr_agent/builtin_monitors/tomcat_monitor.py, scalyr_agent/builtin_monitors/url_monitor.py, scalyr_agent/configuration.py, scalyr_agent/scalyr_monitor.py, tests/unit/configuration_test.py, tests/unit/test_monitor.py
Implementation of https://sentinelone.atlassian.net/browse/DTIN-3192.
For FIPS compliant environments we want to have a config (env) flag that will force HTTPS configuration on all relevant monitors.
I've used the same patten as allow_http does.
=> allow_http_monitors config implementation

scalyr_agent/builtin_monitors/syslog_monitor.py, scalyr_agent/builtin_monitors/thread_pool.py, scalyr_agent/builtin_monitors/thread_pool_dummy.py, scalyr_agent/configuration.py, scalyr_agent/monitors_manager.py, scalyr_agent/platform_posix.py, tests/unit/builtin_monitors/syslog_monitor_test.py, tests/unit/builtin_monitors/syslog_template_test.py
This PR fixes the issue of agent not stopping gracefully and producing logs only for one syslog monitor under load:
https://sentinelone.atlassian.net/browse/DTIN-3231
*  processing_threads set to 4 and reading_threads  to auto (that was the intention from the start, I just mixed it up)
* Thread pool is not shared anymore, but one per syslog server. When share it the threads were not being evenly distributed across monitors and one monitor under load caused other monitors to stop producing any logs. 
* Removed ThreadPoolExecutorFactory
* queue.task_done call added to avoid any future regression bugs when expecting the consistency of the queue object
* Extended the time to wait for the agent to stop gracefully before killing it.
=> Thread pool per monitor, so monitors don't block each other

scalyr_agent/builtin_monitors/syslog_monitor.py
Removing unused queue import, which is not supported in python2. 
concurrent.futures imported only for PY3
=> Python2 fixes

.github/workflows/reusable-agent-build-linux-packages-new.yml, docs/monitors/kubernetes_monitor.md, scalyr_agent/builtin_monitors/kubernetes_monitor.py, scalyr_agent/monitor_utils/k8s.py, scripts/cicd/common/scalyr_query.py, scripts/cicd/verify-k8s-labels-filtered.py, scripts/cicd/verify-multiaccount-records-have-been-ingested.py, tests/e2e/k8s_k8s_monitor/pods-with-labels.yaml, tests/e2e/scalyr-agent-2-daemonset.yaml, tests/unit/builtin_monitors/container_checker_test.py, tests/unit/builtin_monitors/container_checker_test.py.py, tests/unit/configuration_k8s_test.py
From documentation:
| `k8s_label_include_globs`                     | Optional, (defaults to ['*']). Specifies a list of K8s labels to be added to logs. | 
| `k8s_label_exclude_globs`                     | Optional, (defaults to []]). Specifies a list of K8s labels to be ignored and not added to logs. |
Follows the same logic as label_include_globs and label_exclude_globs from the docker_monitor.
Implements:
https://sentinelone.atlassian.net/browse/DTIN-3678
As part of this PR I've added some multiaccount documentation from the generated md file to the kubernetes_monitor.py mondule.
=> Options to omit labels in K8s pod logs

scalyr_agent/copying_manager/copying_manager.py, tests/unit/copying_manager_tests/copying_manager_test.py
* Fixes https://sentinelone.atlassian.net/browse/DTIN-4631
* __lock has been change to reentrant RLock. 
Based on the comments the lock was initially meant to lock status fields used in generate_status.
Now it ensures synchronized access to fields needed for asynchonous workflow of log files. 
This is already causing a timeout when retrieving status from the agent (https://sentinelone.atlassian.net/browse/DTIN-4769) and will be handled in another PR.
**The Bug:**
When a log file (path, worker_id) is scheduled for removal, the removal is done in two separate steps:
*  **__remove_logs_scheduled_for_deletion**
* Instructs all matchers from **__logs_pending_removal** to finish
* Clears **__logs_pending_removal**
* **__purge_finished_log_matchers**
* Removes all finished matchers from …
=> Fix - Race condition when trying to add a log file that's been scheduled for removal

.circleci/smoketest_k8s.sh, scalyr_agent/agent_main.py, scalyr_agent/configuration.py
Introducing a a new config key “agent_status_timeout” and setting it to 30s by default.
When the agent is under a heavier load it can take more than 5 seconds to generate status.
It's caused by thread switching. I've noticed such a switch is usually triggered by IO operations. Reading a 4 byte file can take 3 seconds in wall time.
Unfortunatelly there's no way in python to prioritize a thread.
=> Agent status timeout configurable
